//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class AnKomponente : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBeschreibung;
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        bool fMesspunkt;
        public bool Messpunkt
        {
            get { return fMesspunkt; }
            set { SetPropertyValue<bool>("Messpunkt", ref fMesspunkt, value); }
        }
        AnKomponentenTyp fKomponententyp;
        [Association(@"AnKomponenteReferencesAnKomponentenTyp")]
        public AnKomponentenTyp Komponententyp
        {
            get { return fKomponententyp; }
            set { SetPropertyValue<AnKomponentenTyp>("Komponententyp", ref fKomponententyp, value); }
        }
        boAnlagenArt fAnlagenart;
        [Association(@"AnKomponenteReferencesboAnlagenArt")]
        public boAnlagenArt Anlagenart
        {
            get { return fAnlagenart; }
            set { SetPropertyValue<boAnlagenArt>("Anlagenart", ref fAnlagenart, value); }
        }
        [Association(@"AnAnlagenKomponenteReferencesAnKomponente")]
        public XPCollection<AnAnlagenKomponente> AnAnlagenKomponentes { get { return GetCollection<AnAnlagenKomponente>("AnAnlagenKomponentes"); } }
        [Association(@"AnPruefPunktReferencesAnKomponente")]
        public XPCollection<AnPruefPunkt> AnPruefPunkts { get { return GetCollection<AnPruefPunkt>("AnPruefPunkts"); } }
    }

}
