//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class Attachment : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string ffilename;
        public string filename
        {
            get { return ffilename; }
            set { SetPropertyValue<string>("filename", ref ffilename, value); }
        }
        string fextension;
        public string extension
        {
            get { return fextension; }
            set { SetPropertyValue<string>("extension", ref fextension, value); }
        }
        DateTime fuploaddate;
        public DateTime uploaddate
        {
            get { return fuploaddate; }
            set { SetPropertyValue<DateTime>("uploaddate", ref fuploaddate, value); }
        }
        DateTime flastchangedate;
        public DateTime lastchangedate
        {
            get { return flastchangedate; }
            set { SetPropertyValue<DateTime>("lastchangedate", ref flastchangedate, value); }
        }
        int ffilesize;
        public int filesize
        {
            get { return ffilesize; }
            set { SetPropertyValue<int>("filesize", ref ffilesize, value); }
        }
        FileData ffile;
        [Association(@"AttachmentReferencesFileData")]
        public FileData file
        {
            get { return ffile; }
            set { SetPropertyValue<FileData>("file", ref ffile, value); }
        }
    }

}
