//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boAdresse : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fFremdsystemId;
        public string FremdsystemId
        {
            get { return fFremdsystemId; }
            set { SetPropertyValue<string>("FremdsystemId", ref fFremdsystemId, value); }
        }
        string ffirmenname;
        public string firmenname
        {
            get { return ffirmenname; }
            set { SetPropertyValue<string>("firmenname", ref ffirmenname, value); }
        }
        string fhausnummer;
        public string hausnummer
        {
            get { return fhausnummer; }
            set { SetPropertyValue<string>("hausnummer", ref fhausnummer, value); }
        }
        boLand fland;
        [Association(@"boAdresseReferencesboLand")]
        public boLand land
        {
            get { return fland; }
            set { SetPropertyValue<boLand>("land", ref fland, value); }
        }
        string fnachname;
        public string nachname
        {
            get { return fnachname; }
            set { SetPropertyValue<string>("nachname", ref fnachname, value); }
        }
        string fstrasse;
        public string strasse
        {
            get { return fstrasse; }
            set { SetPropertyValue<string>("strasse", ref fstrasse, value); }
        }
        string fvorname;
        public string vorname
        {
            get { return fvorname; }
            set { SetPropertyValue<string>("vorname", ref fvorname, value); }
        }
        string flongitude;
        public string longitude
        {
            get { return flongitude; }
            set { SetPropertyValue<string>("longitude", ref flongitude, value); }
        }
        string flatitude;
        public string latitude
        {
            get { return flatitude; }
            set { SetPropertyValue<string>("latitude", ref flatitude, value); }
        }
        string fNotizen;
        public string Notizen
        {
            get { return fNotizen; }
            set { SetPropertyValue<string>("Notizen", ref fNotizen, value); }
        }
        boAnrede fAnrede;
        [Association(@"boAdresseReferencesboAnrede")]
        public boAnrede Anrede
        {
            get { return fAnrede; }
            set { SetPropertyValue<boAnrede>("Anrede", ref fAnrede, value); }
        }
        boOrt fort;
        [Association(@"boAdresseReferencesboOrt")]
        public boOrt ort
        {
            get { return fort; }
            set { SetPropertyValue<boOrt>("ort", ref fort, value); }
        }
        boOrtsteil fOrtsteil;
        [Association(@"boAdresseReferencesboOrtsteil")]
        public boOrtsteil Ortsteil
        {
            get { return fOrtsteil; }
            set { SetPropertyValue<boOrtsteil>("Ortsteil", ref fOrtsteil, value); }
        }
        string fZusatz;
        public string Zusatz
        {
            get { return fZusatz; }
            set { SetPropertyValue<string>("Zusatz", ref fZusatz, value); }
        }
        string finternet;
        public string internet
        {
            get { return finternet; }
            set { SetPropertyValue<string>("internet", ref finternet, value); }
        }
        boMandant fMandant;
        [Association(@"boAdresseReferencesboMandant")]
        public boMandant Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<boMandant>("Mandant", ref fMandant, value); }
        }
        string fFremdsystemCode;
        public string FremdsystemCode
        {
            get { return fFremdsystemCode; }
            set { SetPropertyValue<string>("FremdsystemCode", ref fFremdsystemCode, value); }
        }
        [Association(@"boADRKommunikationReferencesboAdresse")]
        public XPCollection<boADRKommunikation> boADRKommunikations { get { return GetCollection<boADRKommunikation>("boADRKommunikations"); } }
        [Association(@"boAnlageReferencesboAdresse")]
        public XPCollection<boAnlage> boAnlages { get { return GetCollection<boAnlage>("boAnlages"); } }
        [Association(@"boAnlageReferencesboAdresse1")]
        public XPCollection<boAnlage> boAnlages1 { get { return GetCollection<boAnlage>("boAnlages1"); } }
        [Association(@"boAnlageReferencesboAdresse2")]
        public XPCollection<boAnlage> boAnlages2 { get { return GetCollection<boAnlage>("boAnlages2"); } }
        [Association(@"boHausverwalterReferencesboAdresse")]
        public XPCollection<boHausverwalter> boHausverwalters { get { return GetCollection<boHausverwalter>("boHausverwalters"); } }
        [Association(@"boKontaktReferencesboAdresse")]
        public XPCollection<boKontakt> boKontakts { get { return GetCollection<boKontakt>("boKontakts"); } }
        [Association(@"boLiegenschaftReferencesboAdresse")]
        public XPCollection<boLiegenschaft> boLiegenschafts1 { get { return GetCollection<boLiegenschaft>("boLiegenschafts1"); } }
        [Association(@"boMandantReferencesboAdresse")]
        public XPCollection<boMandant> boMandants { get { return GetCollection<boMandant>("boMandants"); } }
        [Association(@"boMitarbeiterReferencesboAdresse")]
        public XPCollection<boMitarbeiter> boMitarbeiters { get { return GetCollection<boMitarbeiter>("boMitarbeiters"); } }
        [Association(@"DebitorenkontoReferencesboAdresse")]
        public XPCollection<Debitorenkonto> Debitorenkontoes { get { return GetCollection<Debitorenkonto>("Debitorenkontoes"); } }
        [Association(@"fiGebaeudeReferencesboAdresse")]
        public XPCollection<fiGebaeude> fiGebaeudes { get { return GetCollection<fiGebaeude>("fiGebaeudes"); } }
        [Association(@"HausbetreuerReferencesboAdresse")]
        public XPCollection<Hausbetreuer> Hausbetreuers { get { return GetCollection<Hausbetreuer>("Hausbetreuers"); } }
        [Association(@"KreditorenkontoReferencesboAdresse")]
        public XPCollection<Kreditorenkonto> Kreditorenkontoes { get { return GetCollection<Kreditorenkonto>("Kreditorenkontoes"); } }
        [Association(@"KwpWartungsAnlageReferencesboAdresse")]
        public XPCollection<KwpWartungsAnlage> KwpWartungsAnlages { get { return GetCollection<KwpWartungsAnlage>("KwpWartungsAnlages"); } }
    }

}
