//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boAnlagenArtlstAnlagenArten2_boAnlagenArtlstAnlagenArten1 : XPBaseObject
    {
        boAnlagenArt flstAnlagenArten1;
        [Indexed(@"lstAnlagenArten2", Name = @"ilstAnlagenArten1lstAnlagenArten2_boAnlagenArtlstAnlagenArten2_boAnlagenArtlstAnlagenArten1", Unique = true)]
        [Association(@"boAnlagenArtlstAnlagenArten2_boAnlagenArtlstAnlagenArten1ReferencesboAnlagenArt")]
        public boAnlagenArt lstAnlagenArten1
        {
            get { return flstAnlagenArten1; }
            set { SetPropertyValue<boAnlagenArt>("lstAnlagenArten1", ref flstAnlagenArten1, value); }
        }
        boAnlagenArt flstAnlagenArten2;
        [Association(@"boAnlagenArtlstAnlagenArten2_boAnlagenArtlstAnlagenArten1ReferencesboAnlagenArt1")]
        public boAnlagenArt lstAnlagenArten2
        {
            get { return flstAnlagenArten2; }
            set { SetPropertyValue<boAnlagenArt>("lstAnlagenArten2", ref flstAnlagenArten2, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
