//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boAnlage : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fNotiz;
        public string Notiz
        {
            get { return fNotiz; }
            set { SetPropertyValue<string>("Notiz", ref fNotiz, value); }
        }
        byte[] fMainImageOriginal;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] MainImageOriginal
        {
            get { return fMainImageOriginal; }
            set { SetPropertyValue<byte[]>("MainImageOriginal", ref fMainImageOriginal, value); }
        }
        boAdresse fAnlagenbetreuer;
        [Association(@"boAnlageReferencesboAdresse1")]
        public boAdresse Anlagenbetreuer
        {
            get { return fAnlagenbetreuer; }
            set { SetPropertyValue<boAdresse>("Anlagenbetreuer", ref fAnlagenbetreuer, value); }
        }
        boAdresse fRechnungsadresse;
        [Association(@"boAnlageReferencesboAdresse2")]
        public boAdresse Rechnungsadresse
        {
            get { return fRechnungsadresse; }
            set { SetPropertyValue<boAdresse>("Rechnungsadresse", ref fRechnungsadresse, value); }
        }
        int fBaujahr;
        public int Baujahr
        {
            get { return fBaujahr; }
            set { SetPropertyValue<int>("Baujahr", ref fBaujahr, value); }
        }
        DateTime fEinbaudatum;
        public DateTime Einbaudatum
        {
            get { return fEinbaudatum; }
            set { SetPropertyValue<DateTime>("Einbaudatum", ref fEinbaudatum, value); }
        }
        string fTypbezeichnung;
        public string Typbezeichnung
        {
            get { return fTypbezeichnung; }
            set { SetPropertyValue<string>("Typbezeichnung", ref fTypbezeichnung, value); }
        }
        fiHerstellerProdukt fTyp;
        [Association(@"boAnlageReferencesfiHerstellerProdukt")]
        public fiHerstellerProdukt Typ
        {
            get { return fTyp; }
            set { SetPropertyValue<fiHerstellerProdukt>("Typ", ref fTyp, value); }
        }
        boHersteller fHersteller;
        [Association(@"boAnlageReferencesboHersteller")]
        public boHersteller Hersteller
        {
            get { return fHersteller; }
            set { SetPropertyValue<boHersteller>("Hersteller", ref fHersteller, value); }
        }
        int fZustand;
        public int Zustand
        {
            get { return fZustand; }
            set { SetPropertyValue<int>("Zustand", ref fZustand, value); }
        }
        boLiegenschaft fLiegenschaft;
        [Association(@"boAnlageReferencesboLiegenschaft")]
        public boLiegenschaft Liegenschaft
        {
            get { return fLiegenschaft; }
            set { SetPropertyValue<boLiegenschaft>("Liegenschaft", ref fLiegenschaft, value); }
        }
        boAnlagenArt fAnlagenArt;
        [Association(@"boAnlageReferencesboAnlagenArt")]
        public boAnlagenArt AnlagenArt
        {
            get { return fAnlagenArt; }
            set { SetPropertyValue<boAnlagenArt>("AnlagenArt", ref fAnlagenArt, value); }
        }
        boAnlagenGruppe fAnlagenGruppe;
        [Association(@"boAnlageReferencesboAnlagenGruppe")]
        public boAnlagenGruppe AnlagenGruppe
        {
            get { return fAnlagenGruppe; }
            set { SetPropertyValue<boAnlagenGruppe>("AnlagenGruppe", ref fAnlagenGruppe, value); }
        }
        string fFremdsystemId;
        public string FremdsystemId
        {
            get { return fFremdsystemId; }
            set { SetPropertyValue<string>("FremdsystemId", ref fFremdsystemId, value); }
        }
        boAnlage fParentAnlage;
        [Association(@"boAnlageReferencesboAnlage")]
        public boAnlage ParentAnlage
        {
            get { return fParentAnlage; }
            set { SetPropertyValue<boAnlage>("ParentAnlage", ref fParentAnlage, value); }
        }
        byte[] fMainimage;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Mainimage
        {
            get { return fMainimage; }
            set { SetPropertyValue<byte[]>("Mainimage", ref fMainimage, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        boAdresse fAnlagenAdresse;
        [Association(@"boAnlageReferencesboAdresse")]
        public boAdresse AnlagenAdresse
        {
            get { return fAnlagenAdresse; }
            set { SetPropertyValue<boAdresse>("AnlagenAdresse", ref fAnlagenAdresse, value); }
        }
        string fAnlagencode;
        public string Anlagencode
        {
            get { return fAnlagencode; }
            set { SetPropertyValue<string>("Anlagencode", ref fAnlagencode, value); }
        }
        string fAnlagenNummer;
        public string AnlagenNummer
        {
            get { return fAnlagenNummer; }
            set { SetPropertyValue<string>("AnlagenNummer", ref fAnlagenNummer, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        fiGebaeude fGebaeude;
        [Association(@"boAnlageReferencesfiGebaeude")]
        public fiGebaeude Gebaeude
        {
            get { return fGebaeude; }
            set { SetPropertyValue<fiGebaeude>("Gebaeude", ref fGebaeude, value); }
        }
        fiEbene fEbene;
        [Association(@"boAnlageReferencesfiEbene")]
        public fiEbene Ebene
        {
            get { return fEbene; }
            set { SetPropertyValue<fiEbene>("Ebene", ref fEbene, value); }
        }
        fiRaum fRaum;
        [Association(@"boAnlageReferencesfiRaum")]
        public fiRaum Raum
        {
            get { return fRaum; }
            set { SetPropertyValue<fiRaum>("Raum", ref fRaum, value); }
        }
        string fSeriennummer;
        public string Seriennummer
        {
            get { return fSeriennummer; }
            set { SetPropertyValue<string>("Seriennummer", ref fSeriennummer, value); }
        }
        LgHaustechnikKomponente fHaustechnikKomponente;
        [Association(@"boAnlageReferencesLgHaustechnikKomponente")]
        public LgHaustechnikKomponente HaustechnikKomponente
        {
            get { return fHaustechnikKomponente; }
            set { SetPropertyValue<LgHaustechnikKomponente>("HaustechnikKomponente", ref fHaustechnikKomponente, value); }
        }
        int fAnlagenstatus;
        public int Anlagenstatus
        {
            get { return fAnlagenstatus; }
            set { SetPropertyValue<int>("Anlagenstatus", ref fAnlagenstatus, value); }
        }
        [Association(@"AnAnlagenKomponenteReferencesboAnlage")]
        public XPCollection<AnAnlagenKomponente> AnAnlagenKomponentes { get { return GetCollection<AnAnlagenKomponente>("AnAnlagenKomponentes"); } }
        [Association(@"boANAttachmentReferencesboAnlage")]
        public XPCollection<boANAttachment> boANAttachments { get { return GetCollection<boANAttachment>("boANAttachments"); } }
        [Association(@"boANDatenEntryReferencesboAnlage")]
        public XPCollection<boANDatenEntry> boANDatenEntries { get { return GetCollection<boANDatenEntry>("boANDatenEntries"); } }
        [Association(@"boAnlageReferencesboAnlage")]
        public XPCollection<boAnlage> boAnlageCollection { get { return GetCollection<boAnlage>("boAnlageCollection"); } }
        [Association(@"boAnlagenBildReferencesboAnlage")]
        public XPCollection<boAnlagenBild> boAnlagenBilds { get { return GetCollection<boAnlagenBild>("boAnlagenBilds"); } }
        [Association(@"boAnlagenServiceReferencesboAnlage")]
        public XPCollection<boAnlagenService> boAnlagenServices { get { return GetCollection<boAnlagenService>("boAnlagenServices"); } }
        [Association(@"boANMassnahmeReferencesboAnlage")]
        public XPCollection<boANMassnahme> boANMassnahmes { get { return GetCollection<boANMassnahme>("boANMassnahmes"); } }
        [Association(@"boMessungReferencesboAnlage")]
        public XPCollection<boMessung> boMessungs { get { return GetCollection<boMessung>("boMessungs"); } }
        [Association(@"fiAnlagenfeldReferencesboAnlage")]
        public XPCollection<fiAnlagenfeld> fiAnlagenfelds { get { return GetCollection<fiAnlagenfeld>("fiAnlagenfelds"); } }
        [Association(@"fiAnlagenGeraetReferencesboAnlage")]
        public XPCollection<fiAnlagenGeraet> fiAnlagenGeraets { get { return GetCollection<fiAnlagenGeraet>("fiAnlagenGeraets"); } }
        [Association(@"fiZugangAnlageReferencesboAnlage")]
        public XPCollection<fiZugangAnlage> fiZugangAnlages { get { return GetCollection<fiZugangAnlage>("fiZugangAnlages"); } }
    }

}
