//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelder : XPBaseObject
    {
        boANDatenItem flstDatenFelder;
        [Indexed(@"lstAnlagenArt", Name = @"ilstDatenFelderlstAnlagenArt_boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelder", Unique = true)]
        [Association(@"boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelderReferencesboANDatenItem")]
        public boANDatenItem lstDatenFelder
        {
            get { return flstDatenFelder; }
            set { SetPropertyValue<boANDatenItem>("lstDatenFelder", ref flstDatenFelder, value); }
        }
        boAnlagenArt flstAnlagenArt;
        [Association(@"boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelderReferencesboAnlagenArt")]
        public boAnlagenArt lstAnlagenArt
        {
            get { return flstAnlagenArt; }
            set { SetPropertyValue<boAnlagenArt>("lstAnlagenArt", ref flstAnlagenArt, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
