//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boANDatenItem : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boDatenItem fDatenItem;
        [Association(@"boANDatenItemReferencesboDatenItem")]
        public boDatenItem DatenItem
        {
            get { return fDatenItem; }
            set { SetPropertyValue<boDatenItem>("DatenItem", ref fDatenItem, value); }
        }
        int fSortindex;
        public int Sortindex
        {
            get { return fSortindex; }
            set { SetPropertyValue<int>("Sortindex", ref fSortindex, value); }
        }
        [Association(@"boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelderReferencesboANDatenItem")]
        public XPCollection<boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelder> boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelders { get { return GetCollection<boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelder>("boAnlagenArtlstAnlagenArt_boANDatenItemlstDatenFelders"); } }
    }

}
