//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boAttachmentkategorie : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        bool fOnline;
        public bool Online
        {
            get { return fOnline; }
            set { SetPropertyValue<bool>("Online", ref fOnline, value); }
        }
        [Association(@"boAttachmentReferencesboAttachmentkategorie")]
        public XPCollection<boAttachment> boAttachments { get { return GetCollection<boAttachment>("boAttachments"); } }
        [Association(@"boAttachmentReferencesboAttachmentkategorie1")]
        public XPCollection<boAttachment> boAttachments1 { get { return GetCollection<boAttachment>("boAttachments1"); } }
    }

}
