//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boCheckliste : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        bool fAktiv;
        public bool Aktiv
        {
            get { return fAktiv; }
            set { SetPropertyValue<bool>("Aktiv", ref fAktiv, value); }
        }
        boFIObjekt fObjekttyp;
        [Association(@"boChecklisteReferencesboFIObjekt")]
        public boFIObjekt Objekttyp
        {
            get { return fObjekttyp; }
            set { SetPropertyValue<boFIObjekt>("Objekttyp", ref fObjekttyp, value); }
        }
        [Association(@"boChecklisteCheckListe_boCheckItemCheckItemsReferencesboCheckliste")]
        public XPCollection<boChecklisteCheckListe_boCheckItemCheckItems> boChecklisteCheckListe_boCheckItemCheckItemss { get { return GetCollection<boChecklisteCheckListe_boCheckItemCheckItems>("boChecklisteCheckListe_boCheckItemCheckItemss"); } }
    }

}
