//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boCheckItemValue : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        MediaDataObject fIcon;
        [Association(@"boCheckItemValueReferencesMediaDataObject")]
        public MediaDataObject Icon
        {
            get { return fIcon; }
            set { SetPropertyValue<MediaDataObject>("Icon", ref fIcon, value); }
        }
        [Association(@"boCheckItemValuelstItemValues_boCheckItemlstCheckItemsReferencesboCheckItemValue")]
        public XPCollection<boCheckItemValuelstItemValues_boCheckItemlstCheckItems> boCheckItemValuelstItemValues_boCheckItemlstCheckItemss { get { return GetCollection<boCheckItemValuelstItemValues_boCheckItemlstCheckItems>("boCheckItemValuelstItemValues_boCheckItemlstCheckItemss"); } }
    }

}
