//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boDatenItem : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boDatenKategorie fDatenItem_Kategorie;
        [Association(@"boDatenItemReferencesboDatenKategorie")]
        public boDatenKategorie DatenItem_Kategorie
        {
            get { return fDatenItem_Kategorie; }
            set { SetPropertyValue<boDatenKategorie>("DatenItem_Kategorie", ref fDatenItem_Kategorie, value); }
        }
        string fDatenItem_Bezeichnung;
        public string DatenItem_Bezeichnung
        {
            get { return fDatenItem_Bezeichnung; }
            set { SetPropertyValue<string>("DatenItem_Bezeichnung", ref fDatenItem_Bezeichnung, value); }
        }
        boEinheit fDatenItem_Einheit;
        [Association(@"boDatenItemReferencesboEinheit")]
        public boEinheit DatenItem_Einheit
        {
            get { return fDatenItem_Einheit; }
            set { SetPropertyValue<boEinheit>("DatenItem_Einheit", ref fDatenItem_Einheit, value); }
        }
        [Association(@"boANDatenEntryReferencesboDatenItem")]
        public XPCollection<boANDatenEntry> boANDatenEntries { get { return GetCollection<boANDatenEntry>("boANDatenEntries"); } }
        [Association(@"boANDatenItemReferencesboDatenItem")]
        public XPCollection<boANDatenItem> boANDatenItems { get { return GetCollection<boANDatenItem>("boANDatenItems"); } }
        [Association(@"boDatenValueItemlstDatenValueItems_boDatenItemlstDatenItemsReferencesboDatenItem")]
        public XPCollection<boDatenValueItemlstDatenValueItems_boDatenItemlstDatenItems> boDatenValueItemlstDatenValueItems_boDatenItemlstDatenItemss { get { return GetCollection<boDatenValueItemlstDatenValueItems_boDatenItemlstDatenItems>("boDatenValueItemlstDatenValueItems_boDatenItemlstDatenItemss"); } }
        [Association(@"boFIObjektlstFIObjekte_boDatenItemlstDatenFelderReferencesboDatenItem")]
        public XPCollection<boFIObjektlstFIObjekte_boDatenItemlstDatenFelder> boFIObjektlstFIObjekte_boDatenItemlstDatenFelders { get { return GetCollection<boFIObjektlstFIObjekte_boDatenItemlstDatenFelder>("boFIObjektlstFIObjekte_boDatenItemlstDatenFelders"); } }
        [Association(@"boLGDatenEntryReferencesboDatenItem")]
        public XPCollection<boLGDatenEntry> boLGDatenEntries { get { return GetCollection<boLGDatenEntry>("boLGDatenEntries"); } }
        [Association(@"boMADatenEntryReferencesboDatenItem")]
        public XPCollection<boMADatenEntry> boMADatenEntries { get { return GetCollection<boMADatenEntry>("boMADatenEntries"); } }
        [Association(@"boMADatenItemReferencesboDatenItem")]
        public XPCollection<boMADatenItem> boMADatenItems { get { return GetCollection<boMADatenItem>("boMADatenItems"); } }
        [Association(@"boObjektdatenReferencesboDatenItem")]
        public XPCollection<boObjektdaten> boObjektdatens { get { return GetCollection<boObjektdaten>("boObjektdatens"); } }
    }

}
