//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boDatenKategorie : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fDatenKategorie_Bezeichnung;
        public string DatenKategorie_Bezeichnung
        {
            get { return fDatenKategorie_Bezeichnung; }
            set { SetPropertyValue<string>("DatenKategorie_Bezeichnung", ref fDatenKategorie_Bezeichnung, value); }
        }
        string fDatenKategorie_Kuerzel;
        public string DatenKategorie_Kuerzel
        {
            get { return fDatenKategorie_Kuerzel; }
            set { SetPropertyValue<string>("DatenKategorie_Kuerzel", ref fDatenKategorie_Kuerzel, value); }
        }
        MediaDataObject fDatenKategorie_Icon;
        [Association(@"boDatenKategorieReferencesMediaDataObject")]
        public MediaDataObject DatenKategorie_Icon
        {
            get { return fDatenKategorie_Icon; }
            set { SetPropertyValue<MediaDataObject>("DatenKategorie_Icon", ref fDatenKategorie_Icon, value); }
        }
        [Association(@"boDatenItemReferencesboDatenKategorie")]
        public XPCollection<boDatenItem> boDatenItems { get { return GetCollection<boDatenItem>("boDatenItems"); } }
    }

}
