//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boGeraet : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fP_bezeichnung;
        [Persistent(@"_bezeichnung")]
        public string P_bezeichnung
        {
            get { return fP_bezeichnung; }
            set { SetPropertyValue<string>("P_bezeichnung", ref fP_bezeichnung, value); }
        }
        string fP_kuerzel;
        [Persistent(@"_kuerzel")]
        public string P_kuerzel
        {
            get { return fP_kuerzel; }
            set { SetPropertyValue<string>("P_kuerzel", ref fP_kuerzel, value); }
        }
        boGeraeteart fP_geraeteart;
        [Persistent(@"_geraeteart")]
        [Association(@"boGeraetReferencesboGeraeteart")]
        public boGeraeteart P_geraeteart
        {
            get { return fP_geraeteart; }
            set { SetPropertyValue<boGeraeteart>("P_geraeteart", ref fP_geraeteart, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fKuerzel;
        public string Kuerzel
        {
            get { return fKuerzel; }
            set { SetPropertyValue<string>("Kuerzel", ref fKuerzel, value); }
        }
        boGeraeteart fGeraeteart;
        [Association(@"boGeraetReferencesboGeraeteart1")]
        public boGeraeteart Geraeteart
        {
            get { return fGeraeteart; }
            set { SetPropertyValue<boGeraeteart>("Geraeteart", ref fGeraeteart, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        [Association(@"boMessprobeReferencesboGeraet")]
        public XPCollection<boMessprobe> boMessprobes { get { return GetCollection<boMessprobe>("boMessprobes"); } }
        [Association(@"boMesstyplstMesstyp_boGeraetlstGeraeteReferencesboGeraet")]
        public XPCollection<boMesstyplstMesstyp_boGeraetlstGeraete> boMesstyplstMesstyp_boGeraetlstGeraetes { get { return GetCollection<boMesstyplstMesstyp_boGeraetlstGeraete>("boMesstyplstMesstyp_boGeraetlstGeraetes"); } }
        [Association(@"fiAnlagenGeraetReferencesboGeraet")]
        public XPCollection<fiAnlagenGeraet> fiAnlagenGeraets { get { return GetCollection<fiAnlagenGeraet>("fiAnlagenGeraets"); } }
    }

}
