//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boKuendigungsGrund : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        [Association(@"boVertragReferencesboKuendigungsGrund")]
        public XPCollection<boVertrag> boVertrags { get { return GetCollection<boVertrag>("boVertrags"); } }
        [Association(@"fiVertragReferencesboKuendigungsGrund")]
        public XPCollection<fiVertrag> fiVertrags { get { return GetCollection<fiVertrag>("fiVertrags"); } }
    }

}
