//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boLand : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        MediaDataObject fFlagge;
        [Association(@"boLandReferencesMediaDataObject")]
        public MediaDataObject Flagge
        {
            get { return fFlagge; }
            set { SetPropertyValue<MediaDataObject>("Flagge", ref fFlagge, value); }
        }
        string fKey;
        public string Key
        {
            get { return fKey; }
            set { SetPropertyValue<string>("Key", ref fKey, value); }
        }
        string fIsoKennzeichen;
        public string IsoKennzeichen
        {
            get { return fIsoKennzeichen; }
            set { SetPropertyValue<string>("IsoKennzeichen", ref fIsoKennzeichen, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fVorwahl;
        public string Vorwahl
        {
            get { return fVorwahl; }
            set { SetPropertyValue<string>("Vorwahl", ref fVorwahl, value); }
        }
        byte[] fFlag;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Flag
        {
            get { return fFlag; }
            set { SetPropertyValue<byte[]>("Flag", ref fFlag, value); }
        }
        [Association(@"boAdresseReferencesboLand")]
        public XPCollection<boAdresse> boAdresses { get { return GetCollection<boAdresse>("boAdresses"); } }
        [Association(@"boBundeslandReferencesboLand")]
        public XPCollection<boBundesland> boBundeslands { get { return GetCollection<boBundesland>("boBundeslands"); } }
        [Association(@"boMandantReferencesboLand")]
        public XPCollection<boMandant> boMandants { get { return GetCollection<boMandant>("boMandants"); } }
    }

}
