//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boLeistungskataklog : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        boMandant fMandant;
        [Association(@"boLeistungskataklogReferencesboMandant")]
        public boMandant Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<boMandant>("Mandant", ref fMandant, value); }
        }
        string fBeschreibung;
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        bool fAktiv;
        public bool Aktiv
        {
            get { return fAktiv; }
            set { SetPropertyValue<bool>("Aktiv", ref fAktiv, value); }
        }
        [Association(@"boProduktReferencesboLeistungskataklog")]
        public XPCollection<boProdukt> boProdukts { get { return GetCollection<boProdukt>("boProdukts"); } }
        [Association(@"boProduktReferencesboLeistungskataklog1")]
        public XPCollection<boProdukt> boProdukts1 { get { return GetCollection<boProdukt>("boProdukts1"); } }
    }

}
