//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boLGCheckEntry : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boLGCheckListe fLGCheckliste;
        [Association(@"boLGCheckEntryReferencesboLGCheckListe")]
        public boLGCheckListe LGCheckliste
        {
            get { return fLGCheckliste; }
            set { SetPropertyValue<boLGCheckListe>("LGCheckliste", ref fLGCheckliste, value); }
        }
        boCheckItem fcheckItem;
        [Association(@"boLGCheckEntryReferencesboCheckItem")]
        public boCheckItem checkItem
        {
            get { return fcheckItem; }
            set { SetPropertyValue<boCheckItem>("checkItem", ref fcheckItem, value); }
        }
        int fcheckResult;
        public int checkResult
        {
            get { return fcheckResult; }
            set { SetPropertyValue<int>("checkResult", ref fcheckResult, value); }
        }
        string fcheckValue;
        public string checkValue
        {
            get { return fcheckValue; }
            set { SetPropertyValue<string>("checkValue", ref fcheckValue, value); }
        }
        PermissionPolicyUser ferfasser;
        [Association(@"boLGCheckEntryReferencesPermissionPolicyUser")]
        public PermissionPolicyUser erfasser
        {
            get { return ferfasser; }
            set { SetPropertyValue<PermissionPolicyUser>("erfasser", ref ferfasser, value); }
        }
        DateTime ferfassungsdatum;
        public DateTime erfassungsdatum
        {
            get { return ferfassungsdatum; }
            set { SetPropertyValue<DateTime>("erfassungsdatum", ref ferfassungsdatum, value); }
        }
    }

}
