//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boLieferant : boAdresse
    {
        string feigneKundennummer;
        public string eigneKundennummer
        {
            get { return feigneKundennummer; }
            set { SetPropertyValue<string>("eigneKundennummer", ref feigneKundennummer, value); }
        }
        string fLieferantennummer;
        public string Lieferantennummer
        {
            get { return fLieferantennummer; }
            set { SetPropertyValue<string>("Lieferantennummer", ref fLieferantennummer, value); }
        }
    }

}
