//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMandant : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        bool fAktiv;
        public bool Aktiv
        {
            get { return fAktiv; }
            set { SetPropertyValue<bool>("Aktiv", ref fAktiv, value); }
        }
        string fSlogan;
        public string Slogan
        {
            get { return fSlogan; }
            set { SetPropertyValue<string>("Slogan", ref fSlogan, value); }
        }
        string fMandant;
        public string Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<string>("Mandant", ref fMandant, value); }
        }
        string fstrasse;
        public string strasse
        {
            get { return fstrasse; }
            set { SetPropertyValue<string>("strasse", ref fstrasse, value); }
        }
        string fhausnummer;
        public string hausnummer
        {
            get { return fhausnummer; }
            set { SetPropertyValue<string>("hausnummer", ref fhausnummer, value); }
        }
        boLand fland;
        [Association(@"boMandantReferencesboLand")]
        public boLand land
        {
            get { return fland; }
            set { SetPropertyValue<boLand>("land", ref fland, value); }
        }
        string flongitude;
        public string longitude
        {
            get { return flongitude; }
            set { SetPropertyValue<string>("longitude", ref flongitude, value); }
        }
        string flatitude;
        public string latitude
        {
            get { return flatitude; }
            set { SetPropertyValue<string>("latitude", ref flatitude, value); }
        }
        boOrt fort;
        [Association(@"boMandantReferencesboOrt")]
        public boOrt ort
        {
            get { return fort; }
            set { SetPropertyValue<boOrt>("ort", ref fort, value); }
        }
        string fplz;
        public string plz
        {
            get { return fplz; }
            set { SetPropertyValue<string>("plz", ref fplz, value); }
        }
        string fSteuernummer;
        public string Steuernummer
        {
            get { return fSteuernummer; }
            set { SetPropertyValue<string>("Steuernummer", ref fSteuernummer, value); }
        }
        string fUstId;
        public string UstId
        {
            get { return fUstId; }
            set { SetPropertyValue<string>("UstId", ref fUstId, value); }
        }
        string fRegisternummer;
        public string Registernummer
        {
            get { return fRegisternummer; }
            set { SetPropertyValue<string>("Registernummer", ref fRegisternummer, value); }
        }
        string fRegistergericht;
        public string Registergericht
        {
            get { return fRegistergericht; }
            set { SetPropertyValue<string>("Registergericht", ref fRegistergericht, value); }
        }
        string fGeschaeftsfuehrer;
        public string Geschaeftsfuehrer
        {
            get { return fGeschaeftsfuehrer; }
            set { SetPropertyValue<string>("Geschaeftsfuehrer", ref fGeschaeftsfuehrer, value); }
        }
        boAdresse fAdresse;
        [Association(@"boMandantReferencesboAdresse")]
        public boAdresse Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<boAdresse>("Adresse", ref fAdresse, value); }
        }
        byte[] fWatermark;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Watermark
        {
            get { return fWatermark; }
            set { SetPropertyValue<byte[]>("Watermark", ref fWatermark, value); }
        }
        boWatermark fWasserzeichen;
        [Association(@"boMandantReferencesboWatermark")]
        public boWatermark Wasserzeichen
        {
            get { return fWasserzeichen; }
            set { SetPropertyValue<boWatermark>("Wasserzeichen", ref fWasserzeichen, value); }
        }
        byte[] fLogo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>("Logo", ref fLogo, value); }
        }
        byte[] fBildplatzhalter;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Bildplatzhalter
        {
            get { return fBildplatzhalter; }
            set { SetPropertyValue<byte[]>("Bildplatzhalter", ref fBildplatzhalter, value); }
        }
        string fMandantenkennung;
        public string Mandantenkennung
        {
            get { return fMandantenkennung; }
            set { SetPropertyValue<string>("Mandantenkennung", ref fMandantenkennung, value); }
        }
        string fMandantenname;
        public string Mandantenname
        {
            get { return fMandantenname; }
            set { SetPropertyValue<string>("Mandantenname", ref fMandantenname, value); }
        }
        fiFremdsystem fFremdsystem;
        [Association(@"boMandantReferencesfiFremdsystem")]
        public fiFremdsystem Fremdsystem
        {
            get { return fFremdsystem; }
            set { SetPropertyValue<fiFremdsystem>("Fremdsystem", ref fFremdsystem, value); }
        }
        [Association(@"boAdresseReferencesboMandant")]
        public XPCollection<boAdresse> boAdresses { get { return GetCollection<boAdresse>("boAdresses"); } }
        [Association(@"boAttachmentReferencesboMandant")]
        public XPCollection<boAttachment> boAttachments { get { return GetCollection<boAttachment>("boAttachments"); } }
        [Association(@"boAttachmentBibliothekReferencesboMandant")]
        public XPCollection<boAttachmentBibliothek> boAttachmentBibliotheks { get { return GetCollection<boAttachmentBibliothek>("boAttachmentBibliotheks"); } }
        [Association(@"boFIObjektReferencesboMandant")]
        public XPCollection<boFIObjekt> boFIObjekts { get { return GetCollection<boFIObjekt>("boFIObjekts"); } }
        [Association(@"boHausverwalterReferencesboMandant")]
        public XPCollection<boHausverwalter> boHausverwalters { get { return GetCollection<boHausverwalter>("boHausverwalters"); } }
        [Association(@"boLeistungskataklogReferencesboMandant")]
        public XPCollection<boLeistungskataklog> boLeistungskataklogs { get { return GetCollection<boLeistungskataklog>("boLeistungskataklogs"); } }
        [Association(@"boLiegenschaftReferencesboMandant")]
        public XPCollection<boLiegenschaft> boLiegenschafts { get { return GetCollection<boLiegenschaft>("boLiegenschafts"); } }
        [Association(@"boMandantKommunikationReferencesboMandant")]
        public XPCollection<boMandantKommunikation> boMandantKommunikations { get { return GetCollection<boMandantKommunikation>("boMandantKommunikations"); } }
        [Association(@"boMesstypReferencesboMandant")]
        public XPCollection<boMesstyp> boMesstyps { get { return GetCollection<boMesstyp>("boMesstyps"); } }
        [Association(@"boMitarbeiterReferencesboMandant")]
        public XPCollection<boMitarbeiter> boMitarbeiters { get { return GetCollection<boMitarbeiter>("boMitarbeiters"); } }
        [Association(@"boNummernkreisReferencesboMandant")]
        public XPCollection<boNummernkreis> boNummernkreisCollection { get { return GetCollection<boNummernkreis>("boNummernkreisCollection"); } }
        [Association(@"boVertragReferencesboMandant")]
        public XPCollection<boVertrag> boVertrags { get { return GetCollection<boVertrag>("boVertrags"); } }
        [Association(@"boWartungszoneReferencesboMandant")]
        public XPCollection<boWartungszone> boWartungszones { get { return GetCollection<boWartungszone>("boWartungszones"); } }
        [Association(@"boWatermarkReferencesboMandant")]
        public XPCollection<boWatermark> boWatermarks { get { return GetCollection<boWatermark>("boWatermarks"); } }
        [Association(@"DebitorenkontoReferencesboMandant")]
        public XPCollection<Debitorenkonto> Debitorenkontoes { get { return GetCollection<Debitorenkonto>("Debitorenkontoes"); } }
        [Association(@"fiFremdsystemReferencesboMandant")]
        public XPCollection<fiFremdsystem> fiFremdsystems { get { return GetCollection<fiFremdsystem>("fiFremdsystems"); } }
        [Association(@"fiLeistungskatalogReferencesboMandant")]
        public XPCollection<fiLeistungskatalog> fiLeistungskatalogs { get { return GetCollection<fiLeistungskatalog>("fiLeistungskatalogs"); } }
        [Association(@"fiServicePaketReferencesboMandant")]
        public XPCollection<fiServicePaket> fiServicePakets { get { return GetCollection<fiServicePaket>("fiServicePakets"); } }
        [Association(@"fiVertragReferencesboMandant")]
        public XPCollection<fiVertrag> fiVertrags { get { return GetCollection<fiVertrag>("fiVertrags"); } }
        [Association(@"HausbetreuerReferencesboMandant")]
        public XPCollection<Hausbetreuer> Hausbetreuers { get { return GetCollection<Hausbetreuer>("Hausbetreuers"); } }
        [Association(@"KreditorenkontoReferencesboMandant")]
        public XPCollection<Kreditorenkonto> Kreditorenkontoes { get { return GetCollection<Kreditorenkonto>("Kreditorenkontoes"); } }
        [Association(@"KwpWartungsAuftragReferencesboMandant")]
        public XPCollection<KwpWartungsAuftrag> KwpWartungsAuftrags { get { return GetCollection<KwpWartungsAuftrag>("KwpWartungsAuftrags"); } }
        [Association(@"KwpWartungsVertragReferencesboMandant")]
        public XPCollection<KwpWartungsVertrag> KwpWartungsVertrags { get { return GetCollection<KwpWartungsVertrag>("KwpWartungsVertrags"); } }
    }

}
