//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMAAttachment : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boMassnahme fMassnahme;
        [Association(@"boMAAttachmentReferencesboMassnahme")]
        public boMassnahme Massnahme
        {
            get { return fMassnahme; }
            set { SetPropertyValue<boMassnahme>("Massnahme", ref fMassnahme, value); }
        }
    }

}
