//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMADatenEntry : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boDatenValueItem fEintragswertValueItem;
        [Association(@"boMADatenEntryReferencesboDatenValueItem")]
        public boDatenValueItem EintragswertValueItem
        {
            get { return fEintragswertValueItem; }
            set { SetPropertyValue<boDatenValueItem>("EintragswertValueItem", ref fEintragswertValueItem, value); }
        }
        string fEintragswertLang;
        [Size(500)]
        public string EintragswertLang
        {
            get { return fEintragswertLang; }
            set { SetPropertyValue<string>("EintragswertLang", ref fEintragswertLang, value); }
        }
        string fEintragswertKurz;
        public string EintragswertKurz
        {
            get { return fEintragswertKurz; }
            set { SetPropertyValue<string>("EintragswertKurz", ref fEintragswertKurz, value); }
        }
        string fEintragswertSecure;
        public string EintragswertSecure
        {
            get { return fEintragswertSecure; }
            set { SetPropertyValue<string>("EintragswertSecure", ref fEintragswertSecure, value); }
        }
        boMassnahme fMassnahme;
        [Association(@"boMADatenEntryReferencesboMassnahme")]
        public boMassnahme Massnahme
        {
            get { return fMassnahme; }
            set { SetPropertyValue<boMassnahme>("Massnahme", ref fMassnahme, value); }
        }
        boDatenItem fDatenfeld;
        [Association(@"boMADatenEntryReferencesboDatenItem")]
        public boDatenItem Datenfeld
        {
            get { return fDatenfeld; }
            set { SetPropertyValue<boDatenItem>("Datenfeld", ref fDatenfeld, value); }
        }
    }

}
