//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMessItem : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fKurzbezeichnung;
        public string Kurzbezeichnung
        {
            get { return fKurzbezeichnung; }
            set { SetPropertyValue<string>("Kurzbezeichnung", ref fKurzbezeichnung, value); }
        }
        boEinheit fEinheit;
        [Association(@"boMessItemReferencesboEinheit")]
        public boEinheit Einheit
        {
            get { return fEinheit; }
            set { SetPropertyValue<boEinheit>("Einheit", ref fEinheit, value); }
        }
        AnPruefPunkt fPruefpunkt;
        [Association(@"boMessItemReferencesAnPruefPunkt")]
        public AnPruefPunkt Pruefpunkt
        {
            get { return fPruefpunkt; }
            set { SetPropertyValue<AnPruefPunkt>("Pruefpunkt", ref fPruefpunkt, value); }
        }
        [Association(@"boMessitemEntryReferencesboMessItem")]
        public XPCollection<boMessitemEntry> boMessitemEntries { get { return GetCollection<boMessitemEntry>("boMessitemEntries"); } }
    }

}
