//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMessItemData : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boMessprobe fMessprobe;
        [Association(@"boMessItemDataReferencesboMessprobe")]
        public boMessprobe Messprobe
        {
            get { return fMessprobe; }
            set { SetPropertyValue<boMessprobe>("Messprobe", ref fMessprobe, value); }
        }
        boMessitemEntry fMessItemEntry;
        [Association(@"boMessItemDataReferencesboMessitemEntry")]
        public boMessitemEntry MessItemEntry
        {
            get { return fMessItemEntry; }
            set { SetPropertyValue<boMessitemEntry>("MessItemEntry", ref fMessItemEntry, value); }
        }
        decimal fMesswert;
        public decimal Messwert
        {
            get { return fMesswert; }
            set { SetPropertyValue<decimal>("Messwert", ref fMesswert, value); }
        }
    }

}
