//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMesstyplstMesstyp_boGeraetlstGeraete : XPBaseObject
    {
        boGeraet flstGeraete;
        [Indexed(@"lstMesstyp", Name = @"ilstGeraetelstMesstyp_boMesstyplstMesstyp_boGeraetlstGeraete", Unique = true)]
        [Association(@"boMesstyplstMesstyp_boGeraetlstGeraeteReferencesboGeraet")]
        public boGeraet lstGeraete
        {
            get { return flstGeraete; }
            set { SetPropertyValue<boGeraet>("lstGeraete", ref flstGeraete, value); }
        }
        boMesstyp flstMesstyp;
        [Association(@"boMesstyplstMesstyp_boGeraetlstGeraeteReferencesboMesstyp")]
        public boMesstyp lstMesstyp
        {
            get { return flstMesstyp; }
            set { SetPropertyValue<boMesstyp>("lstMesstyp", ref flstMesstyp, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
