//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boMitarbeiter : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        PermissionPolicyUser fSystembenutzer;
        [Association(@"boMitarbeiterReferencesPermissionPolicyUser")]
        public PermissionPolicyUser Systembenutzer
        {
            get { return fSystembenutzer; }
            set { SetPropertyValue<PermissionPolicyUser>("Systembenutzer", ref fSystembenutzer, value); }
        }
        DateTime fGeburtsdatum;
        public DateTime Geburtsdatum
        {
            get { return fGeburtsdatum; }
            set { SetPropertyValue<DateTime>("Geburtsdatum", ref fGeburtsdatum, value); }
        }
        DateTime fEintrittsdatum;
        public DateTime Eintrittsdatum
        {
            get { return fEintrittsdatum; }
            set { SetPropertyValue<DateTime>("Eintrittsdatum", ref fEintrittsdatum, value); }
        }
        DateTime fAustrittsdatum;
        public DateTime Austrittsdatum
        {
            get { return fAustrittsdatum; }
            set { SetPropertyValue<DateTime>("Austrittsdatum", ref fAustrittsdatum, value); }
        }
        string fFremdsystemID;
        public string FremdsystemID
        {
            get { return fFremdsystemID; }
            set { SetPropertyValue<string>("FremdsystemID", ref fFremdsystemID, value); }
        }
        string fPersonalnummer;
        public string Personalnummer
        {
            get { return fPersonalnummer; }
            set { SetPropertyValue<string>("Personalnummer", ref fPersonalnummer, value); }
        }
        boMandant fMandant;
        [Association(@"boMitarbeiterReferencesboMandant")]
        public boMandant Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<boMandant>("Mandant", ref fMandant, value); }
        }
        string fKuerzel;
        [Size(4)]
        public string Kuerzel
        {
            get { return fKuerzel; }
            set { SetPropertyValue<string>("Kuerzel", ref fKuerzel, value); }
        }
        bool fExtern;
        public bool Extern
        {
            get { return fExtern; }
            set { SetPropertyValue<bool>("Extern", ref fExtern, value); }
        }
        boAdresse fAdresse;
        [Association(@"boMitarbeiterReferencesboAdresse")]
        public boAdresse Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<boAdresse>("Adresse", ref fAdresse, value); }
        }
        [Association(@"foHiebReferencesboMitarbeiter")]
        public XPCollection<foHieb> foHiebs { get { return GetCollection<foHieb>("foHiebs"); } }
        [Association(@"foHiebReferencesboMitarbeiter1")]
        public XPCollection<foHieb> foHiebs1 { get { return GetCollection<foHieb>("foHiebs1"); } }
    }

}
