//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boNummernkreis : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        int fFortlaufendeNummer;
        public int FortlaufendeNummer
        {
            get { return fFortlaufendeNummer; }
            set { SetPropertyValue<int>("FortlaufendeNummer", ref fFortlaufendeNummer, value); }
        }
        boMandant fMandant;
        [Association(@"boNummernkreisReferencesboMandant")]
        public boMandant Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<boMandant>("Mandant", ref fMandant, value); }
        }
        DateTime fGueltigAb;
        public DateTime GueltigAb
        {
            get { return fGueltigAb; }
            set { SetPropertyValue<DateTime>("GueltigAb", ref fGueltigAb, value); }
        }
        DateTime fGueltigBis;
        public DateTime GueltigBis
        {
            get { return fGueltigBis; }
            set { SetPropertyValue<DateTime>("GueltigBis", ref fGueltigBis, value); }
        }
        string fPraefix;
        public string Praefix
        {
            get { return fPraefix; }
            set { SetPropertyValue<string>("Praefix", ref fPraefix, value); }
        }
        string fSuffix;
        public string Suffix
        {
            get { return fSuffix; }
            set { SetPropertyValue<string>("Suffix", ref fSuffix, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fObjekt;
        public string Objekt
        {
            get { return fObjekt; }
            set { SetPropertyValue<string>("Objekt", ref fObjekt, value); }
        }
    }

}
