//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boOrtsteil : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        boOrt fOrt;
        [Association(@"boOrtsteilReferencesboOrt")]
        public boOrt Ort
        {
            get { return fOrt; }
            set { SetPropertyValue<boOrt>("Ort", ref fOrt, value); }
        }
        string fVorwahl;
        public string Vorwahl
        {
            get { return fVorwahl; }
            set { SetPropertyValue<string>("Vorwahl", ref fVorwahl, value); }
        }
        [Association(@"boAdresseReferencesboOrtsteil")]
        public XPCollection<boAdresse> boAdresses { get { return GetCollection<boAdresse>("boAdresses"); } }
        [Association(@"boWartungszonelstWartungszonen_boOrtsteillstOrtsteileReferencesboOrtsteil")]
        public XPCollection<boWartungszonelstWartungszonen_boOrtsteillstOrtsteile> boWartungszonelstWartungszonen_boOrtsteillstOrtsteiles { get { return GetCollection<boWartungszonelstWartungszonen_boOrtsteillstOrtsteile>("boWartungszonelstWartungszonen_boOrtsteillstOrtsteiles"); } }
    }

}
