//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boOrt : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boBundesland fBundesland;
        [Association(@"boOrtReferencesboBundesland")]
        public boBundesland Bundesland
        {
            get { return fBundesland; }
            set { SetPropertyValue<boBundesland>("Bundesland", ref fBundesland, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fPLZ;
        public string PLZ
        {
            get { return fPLZ; }
            set { SetPropertyValue<string>("PLZ", ref fPLZ, value); }
        }
        string fKeyNational;
        public string KeyNational
        {
            get { return fKeyNational; }
            set { SetPropertyValue<string>("KeyNational", ref fKeyNational, value); }
        }
        string fKeyInternational;
        public string KeyInternational
        {
            get { return fKeyInternational; }
            set { SetPropertyValue<string>("KeyInternational", ref fKeyInternational, value); }
        }
        string fFremdsystemID;
        public string FremdsystemID
        {
            get { return fFremdsystemID; }
            set { SetPropertyValue<string>("FremdsystemID", ref fFremdsystemID, value); }
        }
        boOrt fParentOrt;
        [Association(@"boOrtReferencesboOrt")]
        public boOrt ParentOrt
        {
            get { return fParentOrt; }
            set { SetPropertyValue<boOrt>("ParentOrt", ref fParentOrt, value); }
        }
        string fKey;
        public string Key
        {
            get { return fKey; }
            set { SetPropertyValue<string>("Key", ref fKey, value); }
        }
        boWartungszone fWartungsZone;
        [Association(@"boOrtReferencesboWartungszone")]
        public boWartungszone WartungsZone
        {
            get { return fWartungsZone; }
            set { SetPropertyValue<boWartungszone>("WartungsZone", ref fWartungsZone, value); }
        }
        [Association(@"boAdresseReferencesboOrt")]
        public XPCollection<boAdresse> boAdresses { get { return GetCollection<boAdresse>("boAdresses"); } }
        [Association(@"boMandantReferencesboOrt")]
        public XPCollection<boMandant> boMandants { get { return GetCollection<boMandant>("boMandants"); } }
        [Association(@"boOrtReferencesboOrt")]
        public XPCollection<boOrt> boOrtCollection { get { return GetCollection<boOrt>("boOrtCollection"); } }
        [Association(@"boOrtsteilReferencesboOrt")]
        public XPCollection<boOrtsteil> boOrtsteils { get { return GetCollection<boOrtsteil>("boOrtsteils"); } }
        [Association(@"boWartungszonelstWartungszonen_boOrtlstOrteReferencesboOrt")]
        public XPCollection<boWartungszonelstWartungszonen_boOrtlstOrte> boWartungszonelstWartungszonen_boOrtlstOrtes { get { return GetCollection<boWartungszonelstWartungszonen_boOrtlstOrte>("boWartungszonelstWartungszonen_boOrtlstOrtes"); } }
        [Association(@"Iadresse_DataReferencesboOrt")]
        public XPCollection<Iadresse_Data> Iadresse_Datas { get { return GetCollection<Iadresse_Data>("Iadresse_Datas"); } }
    }

}
