//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boServiceItemResult : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        MediaDataObject fIcon;
        [Association(@"boServiceItemResultReferencesMediaDataObject")]
        public MediaDataObject Icon
        {
            get { return fIcon; }
            set { SetPropertyValue<MediaDataObject>("Icon", ref fIcon, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        [Association(@"boServiceItemEntryReferencesboServiceItemResult")]
        public XPCollection<boServiceItemEntry> boServiceItemEntries { get { return GetCollection<boServiceItemEntry>("boServiceItemEntries"); } }
        [Association(@"boServiceItemResultlstServiceItemResults_boServiceItemlstServiceItemsReferencesboServiceItemResult")]
        public XPCollection<boServiceItemResultlstServiceItemResults_boServiceItemlstServiceItems> boServiceItemResultlstServiceItemResults_boServiceItemlstServiceItemss { get { return GetCollection<boServiceItemResultlstServiceItemResults_boServiceItemlstServiceItems>("boServiceItemResultlstServiceItemResults_boServiceItemlstServiceItemss"); } }
    }

}
