//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boService : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        DateTime fPlandatum;
        public DateTime Plandatum
        {
            get { return fPlandatum; }
            set { SetPropertyValue<DateTime>("Plandatum", ref fPlandatum, value); }
        }
        DateTime fWartungsdatum;
        public DateTime Wartungsdatum
        {
            get { return fWartungsdatum; }
            set { SetPropertyValue<DateTime>("Wartungsdatum", ref fWartungsdatum, value); }
        }
        PermissionPolicyUser fDurchfuehrender;
        [Association(@"boServiceReferencesPermissionPolicyUser")]
        public PermissionPolicyUser Durchfuehrender
        {
            get { return fDurchfuehrender; }
            set { SetPropertyValue<PermissionPolicyUser>("Durchfuehrender", ref fDurchfuehrender, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>("Status", ref fStatus, value); }
        }
        [Association(@"boServiceItemEntryReferencesboService")]
        public XPCollection<boServiceItemEntry> boServiceItemEntries { get { return GetCollection<boServiceItemEntry>("boServiceItemEntries"); } }
    }

}
