//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boVertrag : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fVertragsnummer;
        public string Vertragsnummer
        {
            get { return fVertragsnummer; }
            set { SetPropertyValue<string>("Vertragsnummer", ref fVertragsnummer, value); }
        }
        boKunde fKunde;
        [Association(@"boVertragReferencesboKunde")]
        public boKunde Kunde
        {
            get { return fKunde; }
            set { SetPropertyValue<boKunde>("Kunde", ref fKunde, value); }
        }
        DateTime fLaufzeitbeginn;
        public DateTime Laufzeitbeginn
        {
            get { return fLaufzeitbeginn; }
            set { SetPropertyValue<DateTime>("Laufzeitbeginn", ref fLaufzeitbeginn, value); }
        }
        int fLaufzeit;
        public int Laufzeit
        {
            get { return fLaufzeit; }
            set { SetPropertyValue<int>("Laufzeit", ref fLaufzeit, value); }
        }
        int fVertzragsstatus;
        public int Vertzragsstatus
        {
            get { return fVertzragsstatus; }
            set { SetPropertyValue<int>("Vertzragsstatus", ref fVertzragsstatus, value); }
        }
        DateTime fLaufzeitende;
        public DateTime Laufzeitende
        {
            get { return fLaufzeitende; }
            set { SetPropertyValue<DateTime>("Laufzeitende", ref fLaufzeitende, value); }
        }
        boKuendigungsGrund fKuendigungsgrund;
        [Association(@"boVertragReferencesboKuendigungsGrund")]
        public boKuendigungsGrund Kuendigungsgrund
        {
            get { return fKuendigungsgrund; }
            set { SetPropertyValue<boKuendigungsGrund>("Kuendigungsgrund", ref fKuendigungsgrund, value); }
        }
        DateTime fAbschlussdatum;
        public DateTime Abschlussdatum
        {
            get { return fAbschlussdatum; }
            set { SetPropertyValue<DateTime>("Abschlussdatum", ref fAbschlussdatum, value); }
        }
        int fMindestlaufzeit;
        public int Mindestlaufzeit
        {
            get { return fMindestlaufzeit; }
            set { SetPropertyValue<int>("Mindestlaufzeit", ref fMindestlaufzeit, value); }
        }
        int fVertragsstatus;
        public int Vertragsstatus
        {
            get { return fVertragsstatus; }
            set { SetPropertyValue<int>("Vertragsstatus", ref fVertragsstatus, value); }
        }
        int fKuendigungsfrist;
        public int Kuendigungsfrist
        {
            get { return fKuendigungsfrist; }
            set { SetPropertyValue<int>("Kuendigungsfrist", ref fKuendigungsfrist, value); }
        }
        DateTime fKuendigungsdatum;
        public DateTime Kuendigungsdatum
        {
            get { return fKuendigungsdatum; }
            set { SetPropertyValue<DateTime>("Kuendigungsdatum", ref fKuendigungsdatum, value); }
        }
        boMandant fMandant;
        [Association(@"boVertragReferencesboMandant")]
        public boMandant Mandant
        {
            get { return fMandant; }
            set { SetPropertyValue<boMandant>("Mandant", ref fMandant, value); }
        }
        [Association(@"boVertragsleistungReferencesboVertrag")]
        public XPCollection<boVertragsleistung> boVertragsleistungs { get { return GetCollection<boVertragsleistung>("boVertragsleistungs"); } }
    }

}
