//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class boWartungszonelstWartungszonen_boOrtlstOrte : XPBaseObject
    {
        boOrt flstOrte;
        [Indexed(@"lstWartungszonen", Name = @"ilstOrtelstWartungszonen_boWartungszonelstWartungszonen_boOrtlstOrte", Unique = true)]
        [Association(@"boWartungszonelstWartungszonen_boOrtlstOrteReferencesboOrt")]
        public boOrt lstOrte
        {
            get { return flstOrte; }
            set { SetPropertyValue<boOrt>("lstOrte", ref flstOrte, value); }
        }
        boWartungszone flstWartungszonen;
        [Association(@"boWartungszonelstWartungszonen_boOrtlstOrteReferencesboWartungszone")]
        public boWartungszone lstWartungszonen
        {
            get { return flstWartungszonen; }
            set { SetPropertyValue<boWartungszone>("lstWartungszonen", ref flstWartungszonen, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
