//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiAnlagenfeld : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        fiDatenfeldAntwort fDatenfeldAntwort;
        [Association(@"fiAnlagenfeldReferencesfiDatenfeldAntwort")]
        public fiDatenfeldAntwort DatenfeldAntwort
        {
            get { return fDatenfeldAntwort; }
            set { SetPropertyValue<fiDatenfeldAntwort>("DatenfeldAntwort", ref fDatenfeldAntwort, value); }
        }
        fiDatenfeldHerstellerprodukt fDatenfeldHerstellerprodukt;
        [Association(@"fiAnlagenfeldReferencesfiDatenfeldHerstellerprodukt")]
        public fiDatenfeldHerstellerprodukt DatenfeldHerstellerprodukt
        {
            get { return fDatenfeldHerstellerprodukt; }
            set { SetPropertyValue<fiDatenfeldHerstellerprodukt>("DatenfeldHerstellerprodukt", ref fDatenfeldHerstellerprodukt, value); }
        }
        boAnlage fAnlage;
        [Association(@"fiAnlagenfeldReferencesboAnlage")]
        public boAnlage Anlage
        {
            get { return fAnlage; }
            set { SetPropertyValue<boAnlage>("Anlage", ref fAnlage, value); }
        }
    }

}
