//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiAnlagenGeraet : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fEquipmentcode;
        public string Equipmentcode
        {
            get { return fEquipmentcode; }
            set { SetPropertyValue<string>("Equipmentcode", ref fEquipmentcode, value); }
        }
        boGeraet fGeraet;
        [Association(@"fiAnlagenGeraetReferencesboGeraet")]
        public boGeraet Geraet
        {
            get { return fGeraet; }
            set { SetPropertyValue<boGeraet>("Geraet", ref fGeraet, value); }
        }
        boAnlage fAnlage;
        [Association(@"fiAnlagenGeraetReferencesboAnlage")]
        public boAnlage Anlage
        {
            get { return fAnlage; }
            set { SetPropertyValue<boAnlage>("Anlage", ref fAnlage, value); }
        }
        boHersteller fHersteller;
        [Association(@"fiAnlagenGeraetReferencesboHersteller")]
        public boHersteller Hersteller
        {
            get { return fHersteller; }
            set { SetPropertyValue<boHersteller>("Hersteller", ref fHersteller, value); }
        }
        string fNotiz;
        [Size(SizeAttribute.Unlimited)]
        public string Notiz
        {
            get { return fNotiz; }
            set { SetPropertyValue<string>("Notiz", ref fNotiz, value); }
        }
        [Association(@"boMessprobeReferencesfiAnlagenGeraet")]
        public XPCollection<boMessprobe> boMessprobes { get { return GetCollection<boMessprobe>("boMessprobes"); } }
    }

}
