//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiBauteil : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        byte[] fBild;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Bild
        {
            get { return fBild; }
            set { SetPropertyValue<byte[]>("Bild", ref fBild, value); }
        }
        string fherstellernummer;
        public string herstellernummer
        {
            get { return fherstellernummer; }
            set { SetPropertyValue<string>("herstellernummer", ref fherstellernummer, value); }
        }
        boHersteller fHersteller;
        [Association(@"fiBauteilReferencesboHersteller")]
        public boHersteller Hersteller
        {
            get { return fHersteller; }
            set { SetPropertyValue<boHersteller>("Hersteller", ref fHersteller, value); }
        }
        string fBauteilkennung;
        public string Bauteilkennung
        {
            get { return fBauteilkennung; }
            set { SetPropertyValue<string>("Bauteilkennung", ref fBauteilkennung, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        fiBauteilkatalog fBauteilkatalog;
        [Association(@"fiBauteilReferencesfiBauteilkatalog")]
        public fiBauteilkatalog Bauteilkatalog
        {
            get { return fBauteilkatalog; }
            set { SetPropertyValue<fiBauteilkatalog>("Bauteilkatalog", ref fBauteilkatalog, value); }
        }
        [Association(@"fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteileReferencesfiBauteil")]
        public XPCollection<fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteile> fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteiles { get { return GetCollection<fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteile>("fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteiles"); } }
    }

}
