//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiDatenfeldAntwort : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        bool fAktiv;
        public bool Aktiv
        {
            get { return fAktiv; }
            set { SetPropertyValue<bool>("Aktiv", ref fAktiv, value); }
        }
        string fAntworttext;
        public string Antworttext
        {
            get { return fAntworttext; }
            set { SetPropertyValue<string>("Antworttext", ref fAntworttext, value); }
        }
        [Association(@"fiAnlagenfeldReferencesfiDatenfeldAntwort")]
        public XPCollection<fiAnlagenfeld> fiAnlagenfelds { get { return GetCollection<fiAnlagenfeld>("fiAnlagenfelds"); } }
        [Association(@"fiDatenfeldHerstellerproduktReferencesfiDatenfeldAntwort")]
        public XPCollection<fiDatenfeldHerstellerprodukt> fiDatenfeldHerstellerprodukts { get { return GetCollection<fiDatenfeldHerstellerprodukt>("fiDatenfeldHerstellerprodukts"); } }
        [Association(@"fiDatenFeldHerstellerProduktAntwortReferencesfiDatenfeldAntwort")]
        public XPCollection<fiDatenFeldHerstellerProduktAntwort> fiDatenFeldHerstellerProduktAntworts { get { return GetCollection<fiDatenFeldHerstellerProduktAntwort>("fiDatenFeldHerstellerProduktAntworts"); } }
        [Association(@"fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntwortenReferencesfiDatenfeldAntwort")]
        public XPCollection<fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntworten> fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntwortens { get { return GetCollection<fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntworten>("fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntwortens"); } }
    }

}
