//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntworten : XPBaseObject
    {
        fiDatenfeldAntwort flstDatenfeldAntworten;
        [Indexed(@"lstDatenfelder", Name = @"ilstDatenfeldAntwortenlstDatenfelder_fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntworten", Unique = true)]
        [Association(@"fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntwortenReferencesfiDatenfeldAntwort")]
        public fiDatenfeldAntwort lstDatenfeldAntworten
        {
            get { return flstDatenfeldAntworten; }
            set { SetPropertyValue<fiDatenfeldAntwort>("lstDatenfeldAntworten", ref flstDatenfeldAntworten, value); }
        }
        fiDatenfeld flstDatenfelder;
        [Association(@"fiDatenfeldlstDatenfelder_fiDatenfeldAntwortlstDatenfeldAntwortenReferencesfiDatenfeld")]
        public fiDatenfeld lstDatenfelder
        {
            get { return flstDatenfelder; }
            set { SetPropertyValue<fiDatenfeld>("lstDatenfelder", ref flstDatenfelder, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
