//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiEbenenart : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fP_bezeichnung;
        [Persistent(@"_bezeichnung")]
        public string P_bezeichnung
        {
            get { return fP_bezeichnung; }
            set { SetPropertyValue<string>("P_bezeichnung", ref fP_bezeichnung, value); }
        }
        string fP_beschreibung;
        [Persistent(@"_beschreibung")]
        public string P_beschreibung
        {
            get { return fP_beschreibung; }
            set { SetPropertyValue<string>("P_beschreibung", ref fP_beschreibung, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        byte[] fSymbol;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Symbol
        {
            get { return fSymbol; }
            set { SetPropertyValue<byte[]>("Symbol", ref fSymbol, value); }
        }
        string fKuerzel;
        public string Kuerzel
        {
            get { return fKuerzel; }
            set { SetPropertyValue<string>("Kuerzel", ref fKuerzel, value); }
        }
        [Association(@"fiEbeneReferencesfiEbenenart")]
        public XPCollection<fiEbene> fiEbenes { get { return GetCollection<fiEbene>("fiEbenes"); } }
    }

}
