//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiEbene : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        int fSortposition;
        public int Sortposition
        {
            get { return fSortposition; }
            set { SetPropertyValue<int>("Sortposition", ref fSortposition, value); }
        }
        fiEbenenart fArt;
        [Association(@"fiEbeneReferencesfiEbenenart")]
        public fiEbenenart Art
        {
            get { return fArt; }
            set { SetPropertyValue<fiEbenenart>("Art", ref fArt, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        fiGebaeude fGebaeude;
        [Association(@"fiEbeneReferencesfiGebaeude")]
        public fiGebaeude Gebaeude
        {
            get { return fGebaeude; }
            set { SetPropertyValue<fiGebaeude>("Gebaeude", ref fGebaeude, value); }
        }
        [Association(@"boAnlageReferencesfiEbene")]
        public XPCollection<boAnlage> boAnlages { get { return GetCollection<boAnlage>("boAnlages"); } }
        [Association(@"boMessprobeReferencesfiEbene")]
        public XPCollection<boMessprobe> boMessprobes { get { return GetCollection<boMessprobe>("boMessprobes"); } }
        [Association(@"boMessprobeReferencesfiEbene1")]
        public XPCollection<boMessprobe> boMessprobes1 { get { return GetCollection<boMessprobe>("boMessprobes1"); } }
        [Association(@"fiRaumReferencesfiEbene")]
        public XPCollection<fiRaum> fiRaums { get { return GetCollection<fiRaum>("fiRaums"); } }
        [Association(@"LgHaustechnikKomponenteReferencesfiEbene")]
        public XPCollection<LgHaustechnikKomponente> LgHaustechnikKomponentes { get { return GetCollection<LgHaustechnikKomponente>("LgHaustechnikKomponentes"); } }
    }

}
