//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiFremdsystemTabelle : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        fiFremdsystem fFremdsystem;
        [Association(@"fiFremdsystemTabelleReferencesfiFremdsystem")]
        public fiFremdsystem Fremdsystem
        {
            get { return fFremdsystem; }
            set { SetPropertyValue<fiFremdsystem>("Fremdsystem", ref fFremdsystem, value); }
        }
        string fTabellenname;
        public string Tabellenname
        {
            get { return fTabellenname; }
            set { SetPropertyValue<string>("Tabellenname", ref fTabellenname, value); }
        }
        string fIdSpalte;
        public string IdSpalte
        {
            get { return fIdSpalte; }
            set { SetPropertyValue<string>("IdSpalte", ref fIdSpalte, value); }
        }
        string fObjekttyp;
        public string Objekttyp
        {
            get { return fObjekttyp; }
            set { SetPropertyValue<string>("Objekttyp", ref fObjekttyp, value); }
        }
    }

}
