//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiGebaeude : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fNotiz;
        [Size(SizeAttribute.Unlimited)]
        public string Notiz
        {
            get { return fNotiz; }
            set { SetPropertyValue<string>("Notiz", ref fNotiz, value); }
        }
        string fBauteilnummer;
        public string Bauteilnummer
        {
            get { return fBauteilnummer; }
            set { SetPropertyValue<string>("Bauteilnummer", ref fBauteilnummer, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fBeschreibung;
        [Size(SizeAttribute.Unlimited)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        boLiegenschaft fLiegenschaft;
        [Association(@"fiGebaeudeReferencesboLiegenschaft")]
        public boLiegenschaft Liegenschaft
        {
            get { return fLiegenschaft; }
            set { SetPropertyValue<boLiegenschaft>("Liegenschaft", ref fLiegenschaft, value); }
        }
        boAdresse fAdresse;
        [Association(@"fiGebaeudeReferencesboAdresse")]
        public boAdresse Adresse
        {
            get { return fAdresse; }
            set { SetPropertyValue<boAdresse>("Adresse", ref fAdresse, value); }
        }
        [Association(@"boAnlageReferencesfiGebaeude")]
        public XPCollection<boAnlage> boAnlages { get { return GetCollection<boAnlage>("boAnlages"); } }
        [Association(@"boMessprobeReferencesfiGebaeude")]
        public XPCollection<boMessprobe> boMessprobes { get { return GetCollection<boMessprobe>("boMessprobes"); } }
        [Association(@"fiEbeneReferencesfiGebaeude")]
        public XPCollection<fiEbene> fiEbenes { get { return GetCollection<fiEbene>("fiEbenes"); } }
        [Association(@"fiRaumReferencesfiGebaeude")]
        public XPCollection<fiRaum> fiRaums { get { return GetCollection<fiRaum>("fiRaums"); } }
        [Association(@"LgHaustechnikKomponenteReferencesfiGebaeude")]
        public XPCollection<LgHaustechnikKomponente> LgHaustechnikKomponentes { get { return GetCollection<LgHaustechnikKomponente>("LgHaustechnikKomponentes"); } }
    }

}
