//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiHerstellerProduktgruppe : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fNotiz;
        [Size(SizeAttribute.Unlimited)]
        public string Notiz
        {
            get { return fNotiz; }
            set { SetPropertyValue<string>("Notiz", ref fNotiz, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        byte[] fIcon;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Icon
        {
            get { return fIcon; }
            set { SetPropertyValue<byte[]>("Icon", ref fIcon, value); }
        }
        [Association(@"fiHerstellerProduktReferencesfiHerstellerProduktgruppe")]
        public XPCollection<fiHerstellerProdukt> fiHerstellerProdukts { get { return GetCollection<fiHerstellerProdukt>("fiHerstellerProdukts"); } }
        [Association(@"fiHerstellerProduktgruppelstHerstellerproduktgruppen_fiDatenfeldProduktgruppelstDatenfeldProduktgruppeReferencesfiHerstellerProduktgruppe")]
        public XPCollection<fiHerstellerProduktgruppelstHerstellerproduktgruppen_fiDatenfeldProduktgruppelstDatenfeldProduktgruppe> fiHerstellerProduktgruppelstHerstellerproduktgruppen_fiDatenfeldProduktgruppelstDatenfeldProduktgruppes { get { return GetCollection<fiHerstellerProduktgruppelstHerstellerproduktgruppen_fiDatenfeldProduktgruppelstDatenfeldProduktgruppe>("fiHerstellerProduktgruppelstHerstellerproduktgruppen_fiDatenfeldProduktgruppelstDatenfeldProduktgruppes"); } }
    }

}
