//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiHerstellerProduktAttachment : boAttachment
    {
        fiHerstellerProdukt fProdukt;
        [Association(@"fiHerstellerProduktAttachmentReferencesfiHerstellerProdukt")]
        public fiHerstellerProdukt Produkt
        {
            get { return fProdukt; }
            set { SetPropertyValue<fiHerstellerProdukt>("Produkt", ref fProdukt, value); }
        }
        [Association(@"fiHerstellerProduktlstHerstellerprodukte_fiHerstellerProduktAttachmentlstDokumenteReferencesfiHerstellerProduktAttachment")]
        public XPCollection<fiHerstellerProduktlstHerstellerprodukte_fiHerstellerProduktAttachmentlstDokumente> fiHerstellerProduktlstHerstellerprodukte_fiHerstellerProduktAttachmentlstDokumentes { get { return GetCollection<fiHerstellerProduktlstHerstellerprodukte_fiHerstellerProduktAttachmentlstDokumente>("fiHerstellerProduktlstHerstellerprodukte_fiHerstellerProduktAttachmentlstDokumentes"); } }
    }

}
