//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteile : XPBaseObject
    {
        fiBauteil flstBauteile;
        [Indexed(@"lstHerstellerprodukte", Name = @"ilstBauteilelstHerstellerprodukte_fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteile", Unique = true)]
        [Association(@"fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteileReferencesfiBauteil")]
        public fiBauteil lstBauteile
        {
            get { return flstBauteile; }
            set { SetPropertyValue<fiBauteil>("lstBauteile", ref flstBauteile, value); }
        }
        fiHerstellerProdukt flstHerstellerprodukte;
        [Association(@"fiHerstellerProduktlstHerstellerprodukte_fiBauteillstBauteileReferencesfiHerstellerProdukt")]
        public fiHerstellerProdukt lstHerstellerprodukte
        {
            get { return flstHerstellerprodukte; }
            set { SetPropertyValue<fiHerstellerProdukt>("lstHerstellerprodukte", ref flstHerstellerprodukte, value); }
        }
        Guid fOID;
        [Key(true)]
        public Guid OID
        {
            get { return fOID; }
            set { SetPropertyValue<Guid>("OID", ref fOID, value); }
        }
    }

}
