//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class FileData : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        int fsize;
        public int size
        {
            get { return fsize; }
            set { SetPropertyValue<int>("size", ref fsize, value); }
        }
        string fFileName;
        [Size(260)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>("FileName", ref fFileName, value); }
        }
        byte[] fContent;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Content
        {
            get { return fContent; }
            set { SetPropertyValue<byte[]>("Content", ref fContent, value); }
        }
        [Association(@"AttachmentReferencesFileData")]
        public XPCollection<Attachment> Attachments { get { return GetCollection<Attachment>("Attachments"); } }
        [Association(@"boAttachmentReferencesFileData")]
        public XPCollection<boAttachment> boAttachments { get { return GetCollection<boAttachment>("boAttachments"); } }
    }

}
