//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiRaum : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        fiEbene fEbene;
        [Association(@"fiRaumReferencesfiEbene")]
        public fiEbene Ebene
        {
            get { return fEbene; }
            set { SetPropertyValue<fiEbene>("Ebene", ref fEbene, value); }
        }
        string fRaumnummer;
        public string Raumnummer
        {
            get { return fRaumnummer; }
            set { SetPropertyValue<string>("Raumnummer", ref fRaumnummer, value); }
        }
        string fTuerschild;
        public string Tuerschild
        {
            get { return fTuerschild; }
            set { SetPropertyValue<string>("Tuerschild", ref fTuerschild, value); }
        }
        fiRaumart fRaumart;
        [Association(@"fiRaumReferencesfiRaumart")]
        public fiRaumart Raumart
        {
            get { return fRaumart; }
            set { SetPropertyValue<fiRaumart>("Raumart", ref fRaumart, value); }
        }
        string fNotiz;
        [Size(SizeAttribute.Unlimited)]
        public string Notiz
        {
            get { return fNotiz; }
            set { SetPropertyValue<string>("Notiz", ref fNotiz, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        fiGebaeude fGebaeude;
        [Association(@"fiRaumReferencesfiGebaeude")]
        public fiGebaeude Gebaeude
        {
            get { return fGebaeude; }
            set { SetPropertyValue<fiGebaeude>("Gebaeude", ref fGebaeude, value); }
        }
        [Association(@"boAnlageReferencesfiRaum")]
        public XPCollection<boAnlage> boAnlages { get { return GetCollection<boAnlage>("boAnlages"); } }
        [Association(@"boMessprobeReferencesfiRaum")]
        public XPCollection<boMessprobe> boMessprobes { get { return GetCollection<boMessprobe>("boMessprobes"); } }
        [Association(@"LgHaustechnikKomponenteReferencesfiRaum")]
        public XPCollection<LgHaustechnikKomponente> LgHaustechnikKomponentes { get { return GetCollection<LgHaustechnikKomponente>("LgHaustechnikKomponentes"); } }
    }

}
