//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiTechnikeinheit : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fBeschreibung;
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        bool fAktiv;
        public bool Aktiv
        {
            get { return fAktiv; }
            set { SetPropertyValue<bool>("Aktiv", ref fAktiv, value); }
        }
        boAnlagenArt fBasisanlage;
        [Association(@"fiTechnikeinheitReferencesboAnlagenArt")]
        public boAnlagenArt Basisanlage
        {
            get { return fBasisanlage; }
            set { SetPropertyValue<boAnlagenArt>("Basisanlage", ref fBasisanlage, value); }
        }
        string fSystemBezeichnung;
        public string SystemBezeichnung
        {
            get { return fSystemBezeichnung; }
            set { SetPropertyValue<string>("SystemBezeichnung", ref fSystemBezeichnung, value); }
        }
        [Association(@"fiTechnikDefinitionReferencesfiTechnikeinheit")]
        public XPCollection<fiTechnikDefinition> fiTechnikDefinitions { get { return GetCollection<fiTechnikDefinition>("fiTechnikDefinitions"); } }
        [Association(@"fiTechnikeinheitlstTechnikeinheit_boAnlagenArtlstAnlagenartenReferencesfiTechnikeinheit")]
        public XPCollection<fiTechnikeinheitlstTechnikeinheit_boAnlagenArtlstAnlagenarten> fiTechnikeinheitlstTechnikeinheit_boAnlagenArtlstAnlagenartens { get { return GetCollection<fiTechnikeinheitlstTechnikeinheit_boAnlagenArtlstAnlagenarten>("fiTechnikeinheitlstTechnikeinheit_boAnlagenArtlstAnlagenartens"); } }
        [Association(@"LgHaustechnikKomponenteReferencesfiTechnikeinheit")]
        public XPCollection<LgHaustechnikKomponente> LgHaustechnikKomponentes { get { return GetCollection<LgHaustechnikKomponente>("LgHaustechnikKomponentes"); } }
    }

}
