//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class fiZugang : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        fiZugangsTyp fTyp;
        [Association(@"fiZugangReferencesfiZugangsTyp")]
        public fiZugangsTyp Typ
        {
            get { return fTyp; }
            set { SetPropertyValue<fiZugangsTyp>("Typ", ref fTyp, value); }
        }
        fiZugangBeschreibung fBeschreibung;
        [Association(@"fiZugangReferencesfiZugangBeschreibung")]
        public fiZugangBeschreibung Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<fiZugangBeschreibung>("Beschreibung", ref fBeschreibung, value); }
        }
        string fBemerkung;
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        string fWert;
        public string Wert
        {
            get { return fWert; }
            set { SetPropertyValue<string>("Wert", ref fWert, value); }
        }
    }

}
