//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class foStamm : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        foBaumart fBaumart;
        [Association(@"foStammReferencesfoBaumart")]
        public foBaumart Baumart
        {
            get { return fBaumart; }
            set { SetPropertyValue<foBaumart>("Baumart", ref fBaumart, value); }
        }
        decimal fDurchmesser;
        public decimal Durchmesser
        {
            get { return fDurchmesser; }
            set { SetPropertyValue<decimal>("Durchmesser", ref fDurchmesser, value); }
        }
        decimal fLaenge;
        public decimal Laenge
        {
            get { return fLaenge; }
            set { SetPropertyValue<decimal>("Laenge", ref fLaenge, value); }
        }
        foHieb fHieb;
        [Association(@"foStammReferencesfoHieb")]
        public foHieb Hieb
        {
            get { return fHieb; }
            set { SetPropertyValue<foHieb>("Hieb", ref fHieb, value); }
        }
        foPolter fPolter;
        [Association(@"foStammReferencesfoPolter")]
        public foPolter Polter
        {
            get { return fPolter; }
            set { SetPropertyValue<foPolter>("Polter", ref fPolter, value); }
        }
        string fStammnummer;
        public string Stammnummer
        {
            get { return fStammnummer; }
            set { SetPropertyValue<string>("Stammnummer", ref fStammnummer, value); }
        }
    }

}
