//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class KwpWartungsAnlage : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        boLiegenschaft fLiegenschaft;
        [Association(@"KwpWartungsAnlageReferencesboLiegenschaft")]
        public boLiegenschaft Liegenschaft
        {
            get { return fLiegenschaft; }
            set { SetPropertyValue<boLiegenschaft>("Liegenschaft", ref fLiegenschaft, value); }
        }
        string fFremdsystemId;
        public string FremdsystemId
        {
            get { return fFremdsystemId; }
            set { SetPropertyValue<string>("FremdsystemId", ref fFremdsystemId, value); }
        }
        boAdresse fAnlagenAdresse;
        [Association(@"KwpWartungsAnlageReferencesboAdresse")]
        public boAdresse AnlagenAdresse
        {
            get { return fAnlagenAdresse; }
            set { SetPropertyValue<boAdresse>("AnlagenAdresse", ref fAnlagenAdresse, value); }
        }
        boHausverwalter fHausverwalter;
        [Association(@"KwpWartungsAnlageReferencesboHausverwalter")]
        public boHausverwalter Hausverwalter
        {
            get { return fHausverwalter; }
            set { SetPropertyValue<boHausverwalter>("Hausverwalter", ref fHausverwalter, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fAnlagenOrt;
        public string AnlagenOrt
        {
            get { return fAnlagenOrt; }
            set { SetPropertyValue<string>("AnlagenOrt", ref fAnlagenOrt, value); }
        }
        string fMonteur;
        public string Monteur
        {
            get { return fMonteur; }
            set { SetPropertyValue<string>("Monteur", ref fMonteur, value); }
        }
        string fBrennstoffArt;
        public string BrennstoffArt
        {
            get { return fBrennstoffArt; }
            set { SetPropertyValue<string>("BrennstoffArt", ref fBrennstoffArt, value); }
        }
    }

}
