//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class MediaDataObject : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        byte[] fMediaData;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] MediaData
        {
            get { return fMediaData; }
            set { SetPropertyValue<byte[]>("MediaData", ref fMediaData, value); }
        }
        string fMediaDataKey;
        public string MediaDataKey
        {
            get { return fMediaDataKey; }
            set { SetPropertyValue<string>("MediaDataKey", ref fMediaDataKey, value); }
        }
        [Association(@"boAnlagenArtReferencesMediaDataObject")]
        public XPCollection<boAnlagenArt> boAnlagenArts { get { return GetCollection<boAnlagenArt>("boAnlagenArts"); } }
        [Association(@"boAnlagenGruppeReferencesMediaDataObject")]
        public XPCollection<boAnlagenGruppe> boAnlagenGruppes { get { return GetCollection<boAnlagenGruppe>("boAnlagenGruppes"); } }
        [Association(@"boCheckItemValueReferencesMediaDataObject")]
        public XPCollection<boCheckItemValue> boCheckItemValues { get { return GetCollection<boCheckItemValue>("boCheckItemValues"); } }
        [Association(@"boDatenKategorieReferencesMediaDataObject")]
        public XPCollection<boDatenKategorie> boDatenKategories { get { return GetCollection<boDatenKategorie>("boDatenKategories"); } }
        [Association(@"boEntnahmeStelleReferencesMediaDataObject")]
        public XPCollection<boEntnahmeStelle> boEntnahmeStelles { get { return GetCollection<boEntnahmeStelle>("boEntnahmeStelles"); } }
        [Association(@"boGeraeteartReferencesMediaDataObject")]
        public XPCollection<boGeraeteart> boGeraetearts { get { return GetCollection<boGeraeteart>("boGeraetearts"); } }
        [Association(@"boLandReferencesMediaDataObject")]
        public XPCollection<boLand> boLands { get { return GetCollection<boLand>("boLands"); } }
        [Association(@"boMassnahmenArtReferencesMediaDataObject")]
        public XPCollection<boMassnahmenArt> boMassnahmenArts { get { return GetCollection<boMassnahmenArt>("boMassnahmenArts"); } }
        [Association(@"boServiceItemResultReferencesMediaDataObject")]
        public XPCollection<boServiceItemResult> boServiceItemResults { get { return GetCollection<boServiceItemResult>("boServiceItemResults"); } }
        [Association(@"boWertebereichReferencesMediaDataObject")]
        public XPCollection<boWertebereich> boWertebereiches { get { return GetCollection<boWertebereich>("boWertebereiches"); } }
        [Association(@"boZustandReferencesMediaDataObject")]
        public XPCollection<boZustand> boZustands { get { return GetCollection<boZustand>("boZustands"); } }
    }

}
