//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    [NonPersistent]
    public partial class qry_TempFremdsystem : XPLiteObject
    {
        string fAdrFremdID;
        public string AdrFremdID
        {
            get { return fAdrFremdID; }
            set { SetPropertyValue<string>("AdrFremdID", ref fAdrFremdID, value); }
        }
        Guid fAdressOid;
        public Guid AdressOid
        {
            get { return fAdressOid; }
            set { SetPropertyValue<Guid>("AdressOid", ref fAdressOid, value); }
        }
        string ffirmenname;
        public string firmenname
        {
            get { return ffirmenname; }
            set { SetPropertyValue<string>("firmenname", ref ffirmenname, value); }
        }
        string fBezeichnung;
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        Guid fLgOid;
        public Guid LgOid
        {
            get { return fLgOid; }
            set { SetPropertyValue<Guid>("LgOid", ref fLgOid, value); }
        }
        Guid fLiegenschaftsadresse;
        public Guid Liegenschaftsadresse
        {
            get { return fLiegenschaftsadresse; }
            set { SetPropertyValue<Guid>("Liegenschaftsadresse", ref fLiegenschaftsadresse, value); }
        }
        string fLgFremdID;
        public string LgFremdID
        {
            get { return fLgFremdID; }
            set { SetPropertyValue<string>("LgFremdID", ref fLgFremdID, value); }
        }
    }

}
