//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class SecuritySystemObjectPermissionsObject : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>("Criteria", ref fCriteria, value); }
        }
        bool fAllowRead;
        public bool AllowRead
        {
            get { return fAllowRead; }
            set { SetPropertyValue<bool>("AllowRead", ref fAllowRead, value); }
        }
        bool fAllowWrite;
        public bool AllowWrite
        {
            get { return fAllowWrite; }
            set { SetPropertyValue<bool>("AllowWrite", ref fAllowWrite, value); }
        }
        bool fAllowDelete;
        public bool AllowDelete
        {
            get { return fAllowDelete; }
            set { SetPropertyValue<bool>("AllowDelete", ref fAllowDelete, value); }
        }
        bool fAllowNavigate;
        public bool AllowNavigate
        {
            get { return fAllowNavigate; }
            set { SetPropertyValue<bool>("AllowNavigate", ref fAllowNavigate, value); }
        }
        SecuritySystemTypePermissionsObject fOwner;
        [Association(@"SecuritySystemObjectPermissionsObjectReferencesSecuritySystemTypePermissionsObject")]
        public SecuritySystemTypePermissionsObject Owner
        {
            get { return fOwner; }
            set { SetPropertyValue<SecuritySystemTypePermissionsObject>("Owner", ref fOwner, value); }
        }
    }

}
