//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class SecuritySystemRole : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        bool fIsAdministrative;
        public bool IsAdministrative
        {
            get { return fIsAdministrative; }
            set { SetPropertyValue<bool>("IsAdministrative", ref fIsAdministrative, value); }
        }
        bool fCanEditModel;
        public bool CanEditModel
        {
            get { return fCanEditModel; }
            set { SetPropertyValue<bool>("CanEditModel", ref fCanEditModel, value); }
        }
        [Association(@"SecuritySystemRoleParentRoles_SecuritySystemRoleChildRolesReferencesSecuritySystemRole")]
        public XPCollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles> SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoless { get { return GetCollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles>("SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoless"); } }
        [Association(@"SecuritySystemRoleParentRoles_SecuritySystemRoleChildRolesReferencesSecuritySystemRole1")]
        public XPCollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles> SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoless1 { get { return GetCollection<SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoles>("SecuritySystemRoleParentRoles_SecuritySystemRoleChildRoless1"); } }
        [Association(@"SecuritySystemTypePermissionsObjectReferencesSecuritySystemRole")]
        public XPCollection<SecuritySystemTypePermissionsObject> SecuritySystemTypePermissionsObjects { get { return GetCollection<SecuritySystemTypePermissionsObject>("SecuritySystemTypePermissionsObjects"); } }
        [Association(@"SecuritySystemUserUsers_SecuritySystemRoleRolesReferencesSecuritySystemRole")]
        public XPCollection<SecuritySystemUserUsers_SecuritySystemRoleRoles> SecuritySystemUserUsers_SecuritySystemRoleRoless { get { return GetCollection<SecuritySystemUserUsers_SecuritySystemRoleRoles>("SecuritySystemUserUsers_SecuritySystemRoleRoless"); } }
    }

}
