//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoInstanceKey : XPObject
    {
        Guid fKeyId;
        public Guid KeyId
        {
            get { return fKeyId; }
            set { SetPropertyValue<Guid>("KeyId", ref fKeyId, value); }
        }
        Guid fInstanceId;
        public Guid InstanceId
        {
            get { return fInstanceId; }
            set { SetPropertyValue<Guid>("InstanceId", ref fInstanceId, value); }
        }
        string fProperties;
        [Size(SizeAttribute.Unlimited)]
        public string Properties
        {
            get { return fProperties; }
            set { SetPropertyValue<string>("Properties", ref fProperties, value); }
        }
    }

}
