//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoRunningWorkflowInstanceInfo : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fWorkflowName;
        [Size(255)]
        public string WorkflowName
        {
            get { return fWorkflowName; }
            set { SetPropertyValue<string>("WorkflowName", ref fWorkflowName, value); }
        }
        string fWorkflowUniqueId;
        [Size(255)]
        public string WorkflowUniqueId
        {
            get { return fWorkflowUniqueId; }
            set { SetPropertyValue<string>("WorkflowUniqueId", ref fWorkflowUniqueId, value); }
        }
        string fTargetObjectHandle;
        [Size(255)]
        public string TargetObjectHandle
        {
            get { return fTargetObjectHandle; }
            set { SetPropertyValue<string>("TargetObjectHandle", ref fTargetObjectHandle, value); }
        }
        Guid fActivityInstanceId;
        public Guid ActivityInstanceId
        {
            get { return fActivityInstanceId; }
            set { SetPropertyValue<Guid>("ActivityInstanceId", ref fActivityInstanceId, value); }
        }
        string fState;
        public string State
        {
            get { return fState; }
            set { SetPropertyValue<string>("State", ref fState, value); }
        }
    }

}
