//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoState : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>("Caption", ref fCaption, value); }
        }
        XpoStateMachine fStateMachine;
        [Association(@"XpoStateReferencesXpoStateMachine")]
        public XpoStateMachine StateMachine
        {
            get { return fStateMachine; }
            set { SetPropertyValue<XpoStateMachine>("StateMachine", ref fStateMachine, value); }
        }
        string fMarkerValue;
        public string MarkerValue
        {
            get { return fMarkerValue; }
            set { SetPropertyValue<string>("MarkerValue", ref fMarkerValue, value); }
        }
        string fTargetObjectCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string TargetObjectCriteria
        {
            get { return fTargetObjectCriteria; }
            set { SetPropertyValue<string>("TargetObjectCriteria", ref fTargetObjectCriteria, value); }
        }
        [Association(@"XpoStateAppearanceReferencesXpoState")]
        public XPCollection<XpoStateAppearance> XpoStateAppearances { get { return GetCollection<XpoStateAppearance>("XpoStateAppearances"); } }
        [Association(@"XpoStateMachineReferencesXpoState")]
        public XPCollection<XpoStateMachine> XpoStateMachines { get { return GetCollection<XpoStateMachine>("XpoStateMachines"); } }
        [Association(@"XpoTransitionReferencesXpoState")]
        public XPCollection<XpoTransition> XpoTransitions { get { return GetCollection<XpoTransition>("XpoTransitions"); } }
        [Association(@"XpoTransitionReferencesXpoState1")]
        public XPCollection<XpoTransition> XpoTransitions1 { get { return GetCollection<XpoTransition>("XpoTransitions1"); } }
    }

}
