//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoStartWorkflowRequest : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fTargetWorkflowUniqueId;
        public string TargetWorkflowUniqueId
        {
            get { return fTargetWorkflowUniqueId; }
            set { SetPropertyValue<string>("TargetWorkflowUniqueId", ref fTargetWorkflowUniqueId, value); }
        }
        string fTargetObjectKey;
        public string TargetObjectKey
        {
            get { return fTargetObjectKey; }
            set { SetPropertyValue<string>("TargetObjectKey", ref fTargetObjectKey, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>("TargetObjectType", ref fTargetObjectType, value); }
        }
    }

}
