//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoStateAppearance : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        XpoState fState;
        [Association(@"XpoStateAppearanceReferencesXpoState")]
        public XpoState State
        {
            get { return fState; }
            set { SetPropertyValue<XpoState>("State", ref fState, value); }
        }
        string fAppearanceItemType;
        public string AppearanceItemType
        {
            get { return fAppearanceItemType; }
            set { SetPropertyValue<string>("AppearanceItemType", ref fAppearanceItemType, value); }
        }
        string fContext;
        public string Context
        {
            get { return fContext; }
            set { SetPropertyValue<string>("Context", ref fContext, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>("Criteria", ref fCriteria, value); }
        }
        string fMethod;
        public string Method
        {
            get { return fMethod; }
            set { SetPropertyValue<string>("Method", ref fMethod, value); }
        }
        string fTargetItems;
        public string TargetItems
        {
            get { return fTargetItems; }
            set { SetPropertyValue<string>("TargetItems", ref fTargetItems, value); }
        }
        int fPriority;
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>("Priority", ref fPriority, value); }
        }
        int fFontColor;
        public int FontColor
        {
            get { return fFontColor; }
            set { SetPropertyValue<int>("FontColor", ref fFontColor, value); }
        }
        int fBackColor;
        public int BackColor
        {
            get { return fBackColor; }
            set { SetPropertyValue<int>("BackColor", ref fBackColor, value); }
        }
        int fFontStyle;
        public int FontStyle
        {
            get { return fFontStyle; }
            set { SetPropertyValue<int>("FontStyle", ref fFontStyle, value); }
        }
        bool fEnabled;
        public bool Enabled
        {
            get { return fEnabled; }
            set { SetPropertyValue<bool>("Enabled", ref fEnabled, value); }
        }
        int fVisibility;
        public int Visibility
        {
            get { return fVisibility; }
            set { SetPropertyValue<int>("Visibility", ref fVisibility, value); }
        }
    }

}
