//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoTransition : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fCaption;
        public string Caption
        {
            get { return fCaption; }
            set { SetPropertyValue<string>("Caption", ref fCaption, value); }
        }
        XpoState fSourceState;
        [Association(@"XpoTransitionReferencesXpoState")]
        public XpoState SourceState
        {
            get { return fSourceState; }
            set { SetPropertyValue<XpoState>("SourceState", ref fSourceState, value); }
        }
        XpoState fTargetState;
        [Association(@"XpoTransitionReferencesXpoState1")]
        public XpoState TargetState
        {
            get { return fTargetState; }
            set { SetPropertyValue<XpoState>("TargetState", ref fTargetState, value); }
        }
        int fIndex;
        public int Index
        {
            get { return fIndex; }
            set { SetPropertyValue<int>("Index", ref fIndex, value); }
        }
        bool fSaveAndCloseView;
        public bool SaveAndCloseView
        {
            get { return fSaveAndCloseView; }
            set { SetPropertyValue<bool>("SaveAndCloseView", ref fSaveAndCloseView, value); }
        }
    }

}
