//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace FacilityInfo.WebService.FacilityInfo_Data
{

    public partial class XpoWorkflowDefinition : XPCustomObject
    {
        Guid fOid;
        [Key(true)]
        public Guid Oid
        {
            get { return fOid; }
            set { SetPropertyValue<Guid>("Oid", ref fOid, value); }
        }
        string fName;
        [Size(255)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fXaml;
        [Size(SizeAttribute.Unlimited)]
        public string Xaml
        {
            get { return fXaml; }
            set { SetPropertyValue<string>("Xaml", ref fXaml, value); }
        }
        string fTargetObjectType;
        public string TargetObjectType
        {
            get { return fTargetObjectType; }
            set { SetPropertyValue<string>("TargetObjectType", ref fTargetObjectType, value); }
        }
        string fCriteria;
        [Size(SizeAttribute.Unlimited)]
        public string Criteria
        {
            get { return fCriteria; }
            set { SetPropertyValue<string>("Criteria", ref fCriteria, value); }
        }
        bool fIsActive;
        public bool IsActive
        {
            get { return fIsActive; }
            set { SetPropertyValue<bool>("IsActive", ref fIsActive, value); }
        }
        bool fAutoStartWhenObjectIsCreated;
        public bool AutoStartWhenObjectIsCreated
        {
            get { return fAutoStartWhenObjectIsCreated; }
            set { SetPropertyValue<bool>("AutoStartWhenObjectIsCreated", ref fAutoStartWhenObjectIsCreated, value); }
        }
        bool fAutoStartWhenObjectFitsCriteria;
        public bool AutoStartWhenObjectFitsCriteria
        {
            get { return fAutoStartWhenObjectFitsCriteria; }
            set { SetPropertyValue<bool>("AutoStartWhenObjectFitsCriteria", ref fAutoStartWhenObjectFitsCriteria, value); }
        }
        bool fAllowMultipleRuns;
        public bool AllowMultipleRuns
        {
            get { return fAllowMultipleRuns; }
            set { SetPropertyValue<bool>("AllowMultipleRuns", ref fAllowMultipleRuns, value); }
        }
    }

}
