//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class adrOrte : XPLiteObject
    {
        int fOrtID;
        [Key]
        public int OrtID
        {
            get { return fOrtID; }
            set { SetPropertyValue<int>("OrtID", ref fOrtID, value); }
        }
        string fLand;
        [Indexed(Name = @"IX_Land")]
        [Size(3)]
        public string Land
        {
            get { return fLand; }
            set { SetPropertyValue<string>("Land", ref fLand, value); }
        }
        string fPLZ;
        [Indexed(Name = @"IX_Plz")]
        [Size(8)]
        public string PLZ
        {
            get { return fPLZ; }
            set { SetPropertyValue<string>("PLZ", ref fPLZ, value); }
        }
        string fPLZN;
        [Indexed(Name = @"IX_PlzN")]
        [Size(8)]
        public string PLZN
        {
            get { return fPLZN; }
            set { SetPropertyValue<string>("PLZN", ref fPLZN, value); }
        }
        string fOrt;
        [Indexed(Name = @"IX_Ort")]
        [Size(40)]
        public string Ort
        {
            get { return fOrt; }
            set { SetPropertyValue<string>("Ort", ref fOrt, value); }
        }
        int fOrtTyp;
        [Indexed(Name = @"IX_OrtTyp")]
        public int OrtTyp
        {
            get { return fOrtTyp; }
            set { SetPropertyValue<int>("OrtTyp", ref fOrtTyp, value); }
        }
    }

}
