//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class adrRabatte : XPLiteObject
    {
        string fRabattKey;
        [Key]
        [Size(32)]
        public string RabattKey
        {
            get { return fRabattKey; }
            set { SetPropertyValue<string>("RabattKey", ref fRabattKey, value); }
        }
        string fAdrNrGes;
        [Indexed(Name = @"IX_AdrNrGes")]
        [Size(24)]
        public string AdrNrGes
        {
            get { return fAdrNrGes; }
            set { SetPropertyValue<string>("AdrNrGes", ref fAdrNrGes, value); }
        }
        string fKatalog;
        [Indexed(Name = @"IX_Katalog")]
        [Size(4)]
        public string Katalog
        {
            get { return fKatalog; }
            set { SetPropertyValue<string>("Katalog", ref fKatalog, value); }
        }
        string fRabattGruppe;
        [Indexed(Name = @"IX_RabattGruppe")]
        [Size(4)]
        public string RabattGruppe
        {
            get { return fRabattGruppe; }
            set { SetPropertyValue<string>("RabattGruppe", ref fRabattGruppe, value); }
        }
        float fRabatt;
        public float Rabatt
        {
            get { return fRabatt; }
            set { SetPropertyValue<float>("Rabatt", ref fRabatt, value); }
        }
        bool fcheckIndex;
        public bool checkIndex
        {
            get { return fcheckIndex; }
            set { SetPropertyValue<bool>("checkIndex", ref fcheckIndex, value); }
        }
    }

}
