//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class adrSonderPreise : XPLiteObject
    {
        string fSonderPreisKey;
        [Key]
        [Size(54)]
        public string SonderPreisKey
        {
            get { return fSonderPreisKey; }
            set { SetPropertyValue<string>("SonderPreisKey", ref fSonderPreisKey, value); }
        }
        string fAdrNrGes;
        [Indexed(Name = @"IX_AdrNrGes")]
        [Size(24)]
        public string AdrNrGes
        {
            get { return fAdrNrGes; }
            set { SetPropertyValue<string>("AdrNrGes", ref fAdrNrGes, value); }
        }
        double fSonderPreis;
        public double SonderPreis
        {
            get { return fSonderPreis; }
            set { SetPropertyValue<double>("SonderPreis", ref fSonderPreis, value); }
        }
        short fVerarbKZ;
        public short VerarbKZ
        {
            get { return fVerarbKZ; }
            set { SetPropertyValue<short>("VerarbKZ", ref fVerarbKZ, value); }
        }
        string fArtikelNr;
        [Indexed(Name = @"IX_ArtikelNr")]
        [Size(30)]
        public string ArtikelNr
        {
            get { return fArtikelNr; }
            set { SetPropertyValue<string>("ArtikelNr", ref fArtikelNr, value); }
        }
        string fGueltigBis;
        [Size(50)]
        public string GueltigBis
        {
            get { return fGueltigBis; }
            set { SetPropertyValue<string>("GueltigBis", ref fGueltigBis, value); }
        }
    }

}
