//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class adrVerteiler : XPLiteObject
    {
        int fVerteilerId;
        [Key]
        public int VerteilerId
        {
            get { return fVerteilerId; }
            set { SetPropertyValue<int>("VerteilerId", ref fVerteilerId, value); }
        }
        string fVerteiler;
        [Indexed(Name = @"IX_Verteiler")]
        [Size(50)]
        public string Verteiler
        {
            get { return fVerteiler; }
            set { SetPropertyValue<string>("Verteiler", ref fVerteiler, value); }
        }
    }

}
