//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class ArchivRelations : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        ArchivHeader ffkArchivHeader;
        [Association(@"ArchivRelationsReferencesArchivHeader")]
        public ArchivHeader fkArchivHeader
        {
            get { return ffkArchivHeader; }
            set { SetPropertyValue<ArchivHeader>("fkArchivHeader", ref ffkArchivHeader, value); }
        }
        int fBezugsArt;
        public int BezugsArt
        {
            get { return fBezugsArt; }
            set { SetPropertyValue<int>("BezugsArt", ref fBezugsArt, value); }
        }
        string fBezugsNr;
        [Size(80)]
        public string BezugsNr
        {
            get { return fBezugsNr; }
            set { SetPropertyValue<string>("BezugsNr", ref fBezugsNr, value); }
        }
        string fBezugsBemerkung;
        [Size(255)]
        public string BezugsBemerkung
        {
            get { return fBezugsBemerkung; }
            set { SetPropertyValue<string>("BezugsBemerkung", ref fBezugsBemerkung, value); }
        }
        string fGeaendertVon;
        [Size(10)]
        public string GeaendertVon
        {
            get { return fGeaendertVon; }
            set { SetPropertyValue<string>("GeaendertVon", ref fGeaendertVon, value); }
        }
        DateTime fGeaendertAm;
        public DateTime GeaendertAm
        {
            get { return fGeaendertAm; }
            set { SetPropertyValue<DateTime>("GeaendertAm", ref fGeaendertAm, value); }
        }
        string fErstelltVon;
        [Size(10)]
        public string ErstelltVon
        {
            get { return fErstelltVon; }
            set { SetPropertyValue<string>("ErstelltVon", ref fErstelltVon, value); }
        }
        DateTime fErstelltAm;
        public DateTime ErstelltAm
        {
            get { return fErstelltAm; }
            set { SetPropertyValue<DateTime>("ErstelltAm", ref fErstelltAm, value); }
        }
    }

}
