//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class ArchivVerzeichnisLink : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        ArchivHeader ffkArchivHeader;
        [Association(@"ArchivVerzeichnisLinkReferencesArchivHeader")]
        public ArchivHeader fkArchivHeader
        {
            get { return ffkArchivHeader; }
            set { SetPropertyValue<ArchivHeader>("fkArchivHeader", ref ffkArchivHeader, value); }
        }
        ArchivVerzeichnis ffkArchivVerzeichnis;
        [Association(@"ArchivVerzeichnisLinkReferencesArchivVerzeichnis")]
        public ArchivVerzeichnis fkArchivVerzeichnis
        {
            get { return ffkArchivVerzeichnis; }
            set { SetPropertyValue<ArchivVerzeichnis>("fkArchivVerzeichnis", ref ffkArchivVerzeichnis, value); }
        }
        short fLinkTyp;
        public short LinkTyp
        {
            get { return fLinkTyp; }
            set { SetPropertyValue<short>("LinkTyp", ref fLinkTyp, value); }
        }
    }

}
