//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class ArchivFilesRevision : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        ArchivFiles ffkArchivFiles;
        [Association(@"ArchivFilesRevisionReferencesArchivFiles")]
        public ArchivFiles fkArchivFiles
        {
            get { return ffkArchivFiles; }
            set { SetPropertyValue<ArchivFiles>("fkArchivFiles", ref ffkArchivFiles, value); }
        }
        Archive ffkArchive;
        [Association(@"ArchivFilesRevisionReferencesArchive")]
        public Archive fkArchive
        {
            get { return ffkArchive; }
            set { SetPropertyValue<Archive>("fkArchive", ref ffkArchive, value); }
        }
        int fRevision;
        public int Revision
        {
            get { return fRevision; }
            set { SetPropertyValue<int>("Revision", ref fRevision, value); }
        }
        string fDateiname;
        [Size(255)]
        public string Dateiname
        {
            get { return fDateiname; }
            set { SetPropertyValue<string>("Dateiname", ref fDateiname, value); }
        }
        int fDateiLfdNr;
        public int DateiLfdNr
        {
            get { return fDateiLfdNr; }
            set { SetPropertyValue<int>("DateiLfdNr", ref fDateiLfdNr, value); }
        }
        string fDateiendung;
        [Size(50)]
        public string Dateiendung
        {
            get { return fDateiendung; }
            set { SetPropertyValue<string>("Dateiendung", ref fDateiendung, value); }
        }
        string fZipName;
        [Size(255)]
        public string ZipName
        {
            get { return fZipName; }
            set { SetPropertyValue<string>("ZipName", ref fZipName, value); }
        }
        bool fZipLocked;
        public bool ZipLocked
        {
            get { return fZipLocked; }
            set { SetPropertyValue<bool>("ZipLocked", ref fZipLocked, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        string fNurLinkURL;
        [Size(255)]
        public string NurLinkURL
        {
            get { return fNurLinkURL; }
            set { SetPropertyValue<string>("NurLinkURL", ref fNurLinkURL, value); }
        }
        bool fAlt;
        public bool Alt
        {
            get { return fAlt; }
            set { SetPropertyValue<bool>("Alt", ref fAlt, value); }
        }
        string fAltURL;
        [Size(150)]
        public string AltURL
        {
            get { return fAltURL; }
            set { SetPropertyValue<string>("AltURL", ref fAltURL, value); }
        }
        string fAltInfo;
        [Size(50)]
        public string AltInfo
        {
            get { return fAltInfo; }
            set { SetPropertyValue<string>("AltInfo", ref fAltInfo, value); }
        }
        string fErstelltVon;
        [Size(10)]
        public string ErstelltVon
        {
            get { return fErstelltVon; }
            set { SetPropertyValue<string>("ErstelltVon", ref fErstelltVon, value); }
        }
        DateTime fErstelltAm;
        public DateTime ErstelltAm
        {
            get { return fErstelltAm; }
            set { SetPropertyValue<DateTime>("ErstelltAm", ref fErstelltAm, value); }
        }
    }

}
