//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class Aufmass : XPLiteObject
    {
        string fAufmassKey;
        [Key]
        [Size(60)]
        public string AufmassKey
        {
            get { return fAufmassKey; }
            set { SetPropertyValue<string>("AufmassKey", ref fAufmassKey, value); }
        }
        string fProjektNr;
        [Size(15)]
        public string ProjektNr
        {
            get { return fProjektNr; }
            set { SetPropertyValue<string>("ProjektNr", ref fProjektNr, value); }
        }
        int fNummer;
        [Indexed(Name = @"Nummer")]
        public int Nummer
        {
            get { return fNummer; }
            set { SetPropertyValue<int>("Nummer", ref fNummer, value); }
        }
        int fBlatt;
        public int Blatt
        {
            get { return fBlatt; }
            set { SetPropertyValue<int>("Blatt", ref fBlatt, value); }
        }
        int fZwBlatt;
        public int ZwBlatt
        {
            get { return fZwBlatt; }
            set { SetPropertyValue<int>("ZwBlatt", ref fZwBlatt, value); }
        }
        double fMenge;
        public double Menge
        {
            get { return fMenge; }
            set { SetPropertyValue<double>("Menge", ref fMenge, value); }
        }
        double fErgebnis;
        public double Ergebnis
        {
            get { return fErgebnis; }
            set { SetPropertyValue<double>("Ergebnis", ref fErgebnis, value); }
        }
        DateTime fErstDatum;
        public DateTime ErstDatum
        {
            get { return fErstDatum; }
            set { SetPropertyValue<DateTime>("ErstDatum", ref fErstDatum, value); }
        }
        DateTime fAendDatum;
        public DateTime AendDatum
        {
            get { return fAendDatum; }
            set { SetPropertyValue<DateTime>("AendDatum", ref fAendDatum, value); }
        }
        double fSumme;
        public double Summe
        {
            get { return fSumme; }
            set { SetPropertyValue<double>("Summe", ref fSumme, value); }
        }
        string fPosKey;
        [Indexed(Name = @"PosKey")]
        [Size(65)]
        public string PosKey
        {
            get { return fPosKey; }
            set { SetPropertyValue<string>("PosKey", ref fPosKey, value); }
        }
        string fZeile;
        [Size(10)]
        public string Zeile
        {
            get { return fZeile; }
            set { SetPropertyValue<string>("Zeile", ref fZeile, value); }
        }
        string fHeaderMK;
        [Size(1)]
        public string HeaderMK
        {
            get { return fHeaderMK; }
            set { SetPropertyValue<string>("HeaderMK", ref fHeaderMK, value); }
        }
        string fPosAnzeige;
        [Size(46)]
        public string PosAnzeige
        {
            get { return fPosAnzeige; }
            set { SetPropertyValue<string>("PosAnzeige", ref fPosAnzeige, value); }
        }
        string fTitel;
        [Size(20)]
        public string Titel
        {
            get { return fTitel; }
            set { SetPropertyValue<string>("Titel", ref fTitel, value); }
        }
        string fPosition;
        [Size(20)]
        public string Position
        {
            get { return fPosition; }
            set { SetPropertyValue<string>("Position", ref fPosition, value); }
        }
        string fUPosition;
        [Size(6)]
        public string UPosition
        {
            get { return fUPosition; }
            set { SetPropertyValue<string>("UPosition", ref fUPosition, value); }
        }
        string fErlaeuterung;
        [Indexed(Name = @"Erlaeuterung")]
        [Size(50)]
        public string Erlaeuterung
        {
            get { return fErlaeuterung; }
            set { SetPropertyValue<string>("Erlaeuterung", ref fErlaeuterung, value); }
        }
        string fRechenAnsatz;
        [Size(SizeAttribute.Unlimited)]
        public string RechenAnsatz
        {
            get { return fRechenAnsatz; }
            set { SetPropertyValue<string>("RechenAnsatz", ref fRechenAnsatz, value); }
        }
        string fFormel;
        [Size(5)]
        public string Formel
        {
            get { return fFormel; }
            set { SetPropertyValue<string>("Formel", ref fFormel, value); }
        }
        string fTextNrKey;
        [Indexed(Name = @"TextNrKey")]
        [Size(50)]
        public string TextNrKey
        {
            get { return fTextNrKey; }
            set { SetPropertyValue<string>("TextNrKey", ref fTextNrKey, value); }
        }
        string fTextNr;
        [Size(10)]
        public string TextNr
        {
            get { return fTextNr; }
            set { SetPropertyValue<string>("TextNr", ref fTextNr, value); }
        }
        string fText;
        [Size(SizeAttribute.Unlimited)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>("Text", ref fText, value); }
        }
        string fKennung;
        [Size(2)]
        public string Kennung
        {
            get { return fKennung; }
            set { SetPropertyValue<string>("Kennung", ref fKennung, value); }
        }
        string fBearbeiterErst;
        [Size(10)]
        public string BearbeiterErst
        {
            get { return fBearbeiterErst; }
            set { SetPropertyValue<string>("BearbeiterErst", ref fBearbeiterErst, value); }
        }
        string fBearbeiterAend;
        [Size(10)]
        public string BearbeiterAend
        {
            get { return fBearbeiterAend; }
            set { SetPropertyValue<string>("BearbeiterAend", ref fBearbeiterAend, value); }
        }
        string fGrunddaten;
        [Size(SizeAttribute.Unlimited)]
        public string Grunddaten
        {
            get { return fGrunddaten; }
            set { SetPropertyValue<string>("Grunddaten", ref fGrunddaten, value); }
        }
        DateTime fCheckDate;
        public DateTime CheckDate
        {
            get { return fCheckDate; }
            set { SetPropertyValue<DateTime>("CheckDate", ref fCheckDate, value); }
        }
    }

}
