//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class BASIS : XPLiteObject
    {
        float fID;
        [Key]
        public float ID
        {
            get { return fID; }
            set { SetPropertyValue<float>("ID", ref fID, value); }
        }
        float fCONNECT;
        public float CONNECT
        {
            get { return fCONNECT; }
            set { SetPropertyValue<float>("CONNECT", ref fCONNECT, value); }
        }
        string fODBCZugriff;
        [Size(50)]
        public string ODBCZugriff
        {
            get { return fODBCZugriff; }
            set { SetPropertyValue<string>("ODBCZugriff", ref fODBCZugriff, value); }
        }
        string fKATAktiv;
        [Size(20)]
        public string KATAktiv
        {
            get { return fKATAktiv; }
            set { SetPropertyValue<string>("KATAktiv", ref fKATAktiv, value); }
        }
        string fKATKurzel;
        [Size(4)]
        public string KATKurzel
        {
            get { return fKATKurzel; }
            set { SetPropertyValue<string>("KATKurzel", ref fKATKurzel, value); }
        }
        float fSchnittstelle;
        public float Schnittstelle
        {
            get { return fSchnittstelle; }
            set { SetPropertyValue<float>("Schnittstelle", ref fSchnittstelle, value); }
        }
        string fSch_Pfad1;
        [Size(50)]
        public string Sch_Pfad1
        {
            get { return fSch_Pfad1; }
            set { SetPropertyValue<string>("Sch_Pfad1", ref fSch_Pfad1, value); }
        }
        string fSch_Pfad2;
        [Size(50)]
        public string Sch_Pfad2
        {
            get { return fSch_Pfad2; }
            set { SetPropertyValue<string>("Sch_Pfad2", ref fSch_Pfad2, value); }
        }
        string fSch_Pfad3;
        [Size(50)]
        public string Sch_Pfad3
        {
            get { return fSch_Pfad3; }
            set { SetPropertyValue<string>("Sch_Pfad3", ref fSch_Pfad3, value); }
        }
        string fSch_Pfad4;
        [Size(50)]
        public string Sch_Pfad4
        {
            get { return fSch_Pfad4; }
            set { SetPropertyValue<string>("Sch_Pfad4", ref fSch_Pfad4, value); }
        }
        string fSch_Pfad5;
        [Size(50)]
        public string Sch_Pfad5
        {
            get { return fSch_Pfad5; }
            set { SetPropertyValue<string>("Sch_Pfad5", ref fSch_Pfad5, value); }
        }
        string fSch_Pfad6;
        [Size(50)]
        public string Sch_Pfad6
        {
            get { return fSch_Pfad6; }
            set { SetPropertyValue<string>("Sch_Pfad6", ref fSch_Pfad6, value); }
        }
        bool fBildubergabe;
        public bool Bildubergabe
        {
            get { return fBildubergabe; }
            set { SetPropertyValue<bool>("Bildubergabe", ref fBildubergabe, value); }
        }
        string fBasisWahrung;
        [Size(4)]
        public string BasisWahrung
        {
            get { return fBasisWahrung; }
            set { SetPropertyValue<string>("BasisWahrung", ref fBasisWahrung, value); }
        }
        string fLandesWahrung;
        [Size(4)]
        public string LandesWahrung
        {
            get { return fLandesWahrung; }
            set { SetPropertyValue<string>("LandesWahrung", ref fLandesWahrung, value); }
        }
    }

}
