//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class BauTageBuchArbZeiten : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        int fID_Bautagebuch;
        [Indexed(Name = @"IX_BauTageBuchArbZeiten")]
        public int ID_Bautagebuch
        {
            get { return fID_Bautagebuch; }
            set { SetPropertyValue<int>("ID_Bautagebuch", ref fID_Bautagebuch, value); }
        }
        int fPersNr;
        [Indexed(Name = @"IX_BauTageBuchArbZeiten_1")]
        public int PersNr
        {
            get { return fPersNr; }
            set { SetPropertyValue<int>("PersNr", ref fPersNr, value); }
        }
        int fLohnArt;
        [Indexed(Name = @"IX_BauTageBuchArbZeiten_2")]
        public int LohnArt
        {
            get { return fLohnArt; }
            set { SetPropertyValue<int>("LohnArt", ref fLohnArt, value); }
        }
        double fSollAZ;
        public double SollAZ
        {
            get { return fSollAZ; }
            set { SetPropertyValue<double>("SollAZ", ref fSollAZ, value); }
        }
        string fIstVon;
        [Size(8)]
        public string IstVon
        {
            get { return fIstVon; }
            set { SetPropertyValue<string>("IstVon", ref fIstVon, value); }
        }
        string fIstBis;
        [Size(8)]
        public string IstBis
        {
            get { return fIstBis; }
            set { SetPropertyValue<string>("IstBis", ref fIstBis, value); }
        }
        double fIstAZ;
        public double IstAZ
        {
            get { return fIstAZ; }
            set { SetPropertyValue<double>("IstAZ", ref fIstAZ, value); }
        }
        double fRegieStunden;
        public double RegieStunden
        {
            get { return fRegieStunden; }
            set { SetPropertyValue<double>("RegieStunden", ref fRegieStunden, value); }
        }
        short fRegieNrType;
        public short RegieNrType
        {
            get { return fRegieNrType; }
            set { SetPropertyValue<short>("RegieNrType", ref fRegieNrType, value); }
        }
        string fRegiePosArtNr;
        [Size(40)]
        public string RegiePosArtNr
        {
            get { return fRegiePosArtNr; }
            set { SetPropertyValue<string>("RegiePosArtNr", ref fRegiePosArtNr, value); }
        }
    }

}
