//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class BstLagerBuchung : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        BstLagerBeleg fProjektBeleg;
        [Size(35)]
        [Association(@"BstLagerBuchungReferencesBstLagerBeleg")]
        public BstLagerBeleg ProjektBeleg
        {
            get { return fProjektBeleg; }
            set { SetPropertyValue<BstLagerBeleg>("ProjektBeleg", ref fProjektBeleg, value); }
        }
        string fProjNr;
        [Indexed(Name = @"IX_BstLagerBuchung_ProjNr")]
        [Size(15)]
        public string ProjNr
        {
            get { return fProjNr; }
            set { SetPropertyValue<string>("ProjNr", ref fProjNr, value); }
        }
        string fBelegNr;
        [Size(20)]
        public string BelegNr
        {
            get { return fBelegNr; }
            set { SetPropertyValue<string>("BelegNr", ref fBelegNr, value); }
        }
        string fTitel;
        [Indexed(Name = @"IX_BstLagerBuchung_Titel")]
        [Size(20)]
        public string Titel
        {
            get { return fTitel; }
            set { SetPropertyValue<string>("Titel", ref fTitel, value); }
        }
        string fPosNr;
        [Indexed(Name = @"IX_BstLagerBuchung_PosNr")]
        [Size(20)]
        public string PosNr
        {
            get { return fPosNr; }
            set { SetPropertyValue<string>("PosNr", ref fPosNr, value); }
        }
        string fUPosNr;
        [Indexed(Name = @"IX_BstLagerBuchung_UPosNr")]
        [Size(6)]
        public string UPosNr
        {
            get { return fUPosNr; }
            set { SetPropertyValue<string>("UPosNr", ref fUPosNr, value); }
        }
        string fPosKey;
        [Indexed(Name = @"IX_BstLagerBuchung_PosKey")]
        [Size(65)]
        public string PosKey
        {
            get { return fPosKey; }
            set { SetPropertyValue<string>("PosKey", ref fPosKey, value); }
        }
        string fKatalog;
        [Indexed(Name = @"IX_BstLagerBuchung_Katalog")]
        [Size(4)]
        public string Katalog
        {
            get { return fKatalog; }
            set { SetPropertyValue<string>("Katalog", ref fKatalog, value); }
        }
        string fArtNr;
        [Indexed(Name = @"IX_BstLagerBuchung_ArtNr")]
        [Size(25)]
        public string ArtNr
        {
            get { return fArtNr; }
            set { SetPropertyValue<string>("ArtNr", ref fArtNr, value); }
        }
        string fKurztext1;
        [Indexed(Name = @"IX_BstLagerBuchung_Kurztext1")]
        [Size(50)]
        public string Kurztext1
        {
            get { return fKurztext1; }
            set { SetPropertyValue<string>("Kurztext1", ref fKurztext1, value); }
        }
        string fKurztext2;
        [Indexed(Name = @"IX_BstLagerBuchung_Kurztext2")]
        [Size(50)]
        public string Kurztext2
        {
            get { return fKurztext2; }
            set { SetPropertyValue<string>("Kurztext2", ref fKurztext2, value); }
        }
        string fBemerkungIntern;
        [Size(SizeAttribute.Unlimited)]
        public string BemerkungIntern
        {
            get { return fBemerkungIntern; }
            set { SetPropertyValue<string>("BemerkungIntern", ref fBemerkungIntern, value); }
        }
        string fLagerNr;
        [Indexed(Name = @"IX_BstLagerBuchung_LagerNr")]
        [Size(25)]
        public string LagerNr
        {
            get { return fLagerNr; }
            set { SetPropertyValue<string>("LagerNr", ref fLagerNr, value); }
        }
        string fHerkunft;
        [Indexed(Name = @"IX_BstLagerBuchung_Herkunft")]
        [Size(30)]
        public string Herkunft
        {
            get { return fHerkunft; }
            set { SetPropertyValue<string>("Herkunft", ref fHerkunft, value); }
        }
        string fHerkunftPosKey;
        [Indexed(Name = @"IX_BstLagerBuchung_HerkunftPosKey")]
        [Size(65)]
        public string HerkunftPosKey
        {
            get { return fHerkunftPosKey; }
            set { SetPropertyValue<string>("HerkunftPosKey", ref fHerkunftPosKey, value); }
        }
        string fSerienNrGUID;
        [Indexed(Name = @"IX_BstLagerBuchung_SerienNrGUID")]
        [Size(40)]
        public string SerienNrGUID
        {
            get { return fSerienNrGUID; }
            set { SetPropertyValue<string>("SerienNrGUID", ref fSerienNrGUID, value); }
        }
        string fPosBebuchLagerOrt;
        [Indexed(Name = @"IX_BstLagerBuchung_PosBebuchLagerOrt")]
        [Size(90)]
        public string PosBebuchLagerOrt
        {
            get { return fPosBebuchLagerOrt; }
            set { SetPropertyValue<string>("PosBebuchLagerOrt", ref fPosBebuchLagerOrt, value); }
        }
        string fFremdbelegBstlg;
        [Indexed(Name = @"IX_BstLagerBuchung_FremdbelegBstlg")]
        [Size(255)]
        public string FremdbelegBstlg
        {
            get { return fFremdbelegBstlg; }
            set { SetPropertyValue<string>("FremdbelegBstlg", ref fFremdbelegBstlg, value); }
        }
        short fKoArt;
        [Indexed(Name = @"IX_BstLagerBuchung_KoArt")]
        public short KoArt
        {
            get { return fKoArt; }
            set { SetPropertyValue<short>("KoArt", ref fKoArt, value); }
        }
        string fMengenEinh;
        [Size(4)]
        public string MengenEinh
        {
            get { return fMengenEinh; }
            set { SetPropertyValue<string>("MengenEinh", ref fMengenEinh, value); }
        }
        decimal fMenge;
        public decimal Menge
        {
            get { return fMenge; }
            set { SetPropertyValue<decimal>("Menge", ref fMenge, value); }
        }
        DateTime fCheckDate;
        public DateTime CheckDate
        {
            get { return fCheckDate; }
            set { SetPropertyValue<DateTime>("CheckDate", ref fCheckDate, value); }
        }
        int fPreisEH;
        public int PreisEH
        {
            get { return fPreisEH; }
            set { SetPropertyValue<int>("PreisEH", ref fPreisEH, value); }
        }
        decimal fNettoMatpEH;
        public decimal NettoMatpEH
        {
            get { return fNettoMatpEH; }
            set { SetPropertyValue<decimal>("NettoMatpEH", ref fNettoMatpEH, value); }
        }
        decimal fNettoRohstpEH;
        public decimal NettoRohstpEH
        {
            get { return fNettoRohstpEH; }
            set { SetPropertyValue<decimal>("NettoRohstpEH", ref fNettoRohstpEH, value); }
        }
        decimal fNettoMat;
        public decimal NettoMat
        {
            get { return fNettoMat; }
            set { SetPropertyValue<decimal>("NettoMat", ref fNettoMat, value); }
        }
        decimal fNettoRohst;
        public decimal NettoRohst
        {
            get { return fNettoRohst; }
            set { SetPropertyValue<decimal>("NettoRohst", ref fNettoRohst, value); }
        }
        decimal fNettoPreis;
        public decimal NettoPreis
        {
            get { return fNettoPreis; }
            set { SetPropertyValue<decimal>("NettoPreis", ref fNettoPreis, value); }
        }
        decimal fBruttoPrs;
        public decimal BruttoPrs
        {
            get { return fBruttoPrs; }
            set { SetPropertyValue<decimal>("BruttoPrs", ref fBruttoPrs, value); }
        }
        DateTime fDatumErfasst;
        public DateTime DatumErfasst
        {
            get { return fDatumErfasst; }
            set { SetPropertyValue<DateTime>("DatumErfasst", ref fDatumErfasst, value); }
        }
        string fUserErfasst;
        [Size(8)]
        public string UserErfasst
        {
            get { return fUserErfasst; }
            set { SetPropertyValue<string>("UserErfasst", ref fUserErfasst, value); }
        }
        DateTime fDatumAenderung;
        public DateTime DatumAenderung
        {
            get { return fDatumAenderung; }
            set { SetPropertyValue<DateTime>("DatumAenderung", ref fDatumAenderung, value); }
        }
        string fUserAenderung;
        [Size(8)]
        public string UserAenderung
        {
            get { return fUserAenderung; }
            set { SetPropertyValue<string>("UserAenderung", ref fUserAenderung, value); }
        }
        string fInRegieUebernommen;
        [Size(20)]
        public string InRegieUebernommen
        {
            get { return fInRegieUebernommen; }
            set { SetPropertyValue<string>("InRegieUebernommen", ref fInRegieUebernommen, value); }
        }
    }

}
