//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class BstLager : XPLiteObject
    {
        string fProjNr;
        [Indexed(Name = @"ProjNr")]
        [Size(15)]
        public string ProjNr
        {
            get { return fProjNr; }
            set { SetPropertyValue<string>("ProjNr", ref fProjNr, value); }
        }
        string fBelegNr;
        [Indexed(Name = @"BelegNr")]
        [Size(20)]
        public string BelegNr
        {
            get { return fBelegNr; }
            set { SetPropertyValue<string>("BelegNr", ref fBelegNr, value); }
        }
        string fBelegBez;
        [Size(SizeAttribute.Unlimited)]
        public string BelegBez
        {
            get { return fBelegBez; }
            set { SetPropertyValue<string>("BelegBez", ref fBelegBez, value); }
        }
        DateTime fBelegDatum;
        public DateTime BelegDatum
        {
            get { return fBelegDatum; }
            set { SetPropertyValue<DateTime>("BelegDatum", ref fBelegDatum, value); }
        }
        string fKennung;
        [Indexed(Name = @"Kennung")]
        [Size(1)]
        public string Kennung
        {
            get { return fKennung; }
            set { SetPropertyValue<string>("Kennung", ref fKennung, value); }
        }
        string fPosKey;
        [Size(65)]
        public string PosKey
        {
            get { return fPosKey; }
            set { SetPropertyValue<string>("PosKey", ref fPosKey, value); }
        }
        string fTitel;
        [Size(20)]
        public string Titel
        {
            get { return fTitel; }
            set { SetPropertyValue<string>("Titel", ref fTitel, value); }
        }
        string fPosSchluessel;
        [Size(46)]
        public string PosSchluessel
        {
            get { return fPosSchluessel; }
            set { SetPropertyValue<string>("PosSchluessel", ref fPosSchluessel, value); }
        }
        string fPosNr;
        [Size(20)]
        public string PosNr
        {
            get { return fPosNr; }
            set { SetPropertyValue<string>("PosNr", ref fPosNr, value); }
        }
        string fUPosNr;
        [Size(6)]
        public string UPosNr
        {
            get { return fUPosNr; }
            set { SetPropertyValue<string>("UPosNr", ref fUPosNr, value); }
        }
        string fKatalog;
        [Indexed(Name = @"Katalog")]
        [Size(4)]
        public string Katalog
        {
            get { return fKatalog; }
            set { SetPropertyValue<string>("Katalog", ref fKatalog, value); }
        }
        string fArtNr;
        [Indexed(Name = @"ArtNr")]
        [Size(25)]
        public string ArtNr
        {
            get { return fArtNr; }
            set { SetPropertyValue<string>("ArtNr", ref fArtNr, value); }
        }
        string fKurztext1;
        [Size(50)]
        public string Kurztext1
        {
            get { return fKurztext1; }
            set { SetPropertyValue<string>("Kurztext1", ref fKurztext1, value); }
        }
        string fKurztext2;
        [Size(50)]
        public string Kurztext2
        {
            get { return fKurztext2; }
            set { SetPropertyValue<string>("Kurztext2", ref fKurztext2, value); }
        }
        string fRabattGrp;
        [Size(10)]
        public string RabattGrp
        {
            get { return fRabattGrp; }
            set { SetPropertyValue<string>("RabattGrp", ref fRabattGrp, value); }
        }
        short fKoArt;
        public short KoArt
        {
            get { return fKoArt; }
            set { SetPropertyValue<short>("KoArt", ref fKoArt, value); }
        }
        double fRabatt1;
        public double Rabatt1
        {
            get { return fRabatt1; }
            set { SetPropertyValue<double>("Rabatt1", ref fRabatt1, value); }
        }
        decimal fSonderNettoPreis;
        public decimal SonderNettoPreis
        {
            get { return fSonderNettoPreis; }
            set { SetPropertyValue<decimal>("SonderNettoPreis", ref fSonderNettoPreis, value); }
        }
        string fMengenEinh;
        [Size(4)]
        public string MengenEinh
        {
            get { return fMengenEinh; }
            set { SetPropertyValue<string>("MengenEinh", ref fMengenEinh, value); }
        }
        double fMenge;
        public double Menge
        {
            get { return fMenge; }
            set { SetPropertyValue<double>("Menge", ref fMenge, value); }
        }
        string fAdrKuerzel;
        [Size(24)]
        public string AdrKuerzel
        {
            get { return fAdrKuerzel; }
            set { SetPropertyValue<string>("AdrKuerzel", ref fAdrKuerzel, value); }
        }
        bool fKonv2Euro;
        public bool Konv2Euro
        {
            get { return fKonv2Euro; }
            set { SetPropertyValue<bool>("Konv2Euro", ref fKonv2Euro, value); }
        }
        DateTime fCheckDate;
        public DateTime CheckDate
        {
            get { return fCheckDate; }
            set { SetPropertyValue<DateTime>("CheckDate", ref fCheckDate, value); }
        }
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        double fNettoMat;
        public double NettoMat
        {
            get { return fNettoMat; }
            set { SetPropertyValue<double>("NettoMat", ref fNettoMat, value); }
        }
        double fNettoRohst;
        public double NettoRohst
        {
            get { return fNettoRohst; }
            set { SetPropertyValue<double>("NettoRohst", ref fNettoRohst, value); }
        }
        double fNettoPreis;
        public double NettoPreis
        {
            get { return fNettoPreis; }
            set { SetPropertyValue<double>("NettoPreis", ref fNettoPreis, value); }
        }
        int fPreisEH;
        public int PreisEH
        {
            get { return fPreisEH; }
            set { SetPropertyValue<int>("PreisEH", ref fPreisEH, value); }
        }
        double fNettoMatpEH;
        public double NettoMatpEH
        {
            get { return fNettoMatpEH; }
            set { SetPropertyValue<double>("NettoMatpEH", ref fNettoMatpEH, value); }
        }
        double fNettoRohstpEH;
        public double NettoRohstpEH
        {
            get { return fNettoRohstpEH; }
            set { SetPropertyValue<double>("NettoRohstpEH", ref fNettoRohstpEH, value); }
        }
    }

}
