//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class Buchungen : XPLiteObject
    {
        int fBelegNr;
        [Indexed(Name = @"BelegNr")]
        public int BelegNr
        {
            get { return fBelegNr; }
            set { SetPropertyValue<int>("BelegNr", ref fBelegNr, value); }
        }
        string fBelegArt;
        [Indexed(Name = @"BelegArt")]
        [Size(1)]
        public string BelegArt
        {
            get { return fBelegArt; }
            set { SetPropertyValue<string>("BelegArt", ref fBelegArt, value); }
        }
        string fZahlArt;
        [Indexed(Name = @"ZahlArt")]
        [Size(1)]
        public string ZahlArt
        {
            get { return fZahlArt; }
            set { SetPropertyValue<string>("ZahlArt", ref fZahlArt, value); }
        }
        DateTime fBelegDatum;
        [Indexed(Name = @"BelegDatum")]
        public DateTime BelegDatum
        {
            get { return fBelegDatum; }
            set { SetPropertyValue<DateTime>("BelegDatum", ref fBelegDatum, value); }
        }
        DateTime fBelegUhrzeit;
        public DateTime BelegUhrzeit
        {
            get { return fBelegUhrzeit; }
            set { SetPropertyValue<DateTime>("BelegUhrzeit", ref fBelegUhrzeit, value); }
        }
        string fBenutzerID;
        [Indexed(Name = @"BenutzerID")]
        [Size(8)]
        public string BenutzerID
        {
            get { return fBenutzerID; }
            set { SetPropertyValue<string>("BenutzerID", ref fBenutzerID, value); }
        }
        string fKontoNr;
        [Size(30)]
        public string KontoNr
        {
            get { return fKontoNr; }
            set { SetPropertyValue<string>("KontoNr", ref fKontoNr, value); }
        }
        string fBemerkung;
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        string fScheckAusteller;
        [Size(50)]
        public string ScheckAusteller
        {
            get { return fScheckAusteller; }
            set { SetPropertyValue<string>("ScheckAusteller", ref fScheckAusteller, value); }
        }
        string fScheckBLZ;
        [Size(30)]
        public string ScheckBLZ
        {
            get { return fScheckBLZ; }
            set { SetPropertyValue<string>("ScheckBLZ", ref fScheckBLZ, value); }
        }
        string fScheckNr;
        [Size(40)]
        public string ScheckNr
        {
            get { return fScheckNr; }
            set { SetPropertyValue<string>("ScheckNr", ref fScheckNr, value); }
        }
        decimal fBruttoBetrag;
        public decimal BruttoBetrag
        {
            get { return fBruttoBetrag; }
            set { SetPropertyValue<decimal>("BruttoBetrag", ref fBruttoBetrag, value); }
        }
        bool fMonatsAbschluss;
        public bool MonatsAbschluss
        {
            get { return fMonatsAbschluss; }
            set { SetPropertyValue<bool>("MonatsAbschluss", ref fMonatsAbschluss, value); }
        }
        decimal fAnteilNetto1;
        public decimal AnteilNetto1
        {
            get { return fAnteilNetto1; }
            set { SetPropertyValue<decimal>("AnteilNetto1", ref fAnteilNetto1, value); }
        }
        decimal fMwstBetrag1;
        public decimal MwstBetrag1
        {
            get { return fMwstBetrag1; }
            set { SetPropertyValue<decimal>("MwstBetrag1", ref fMwstBetrag1, value); }
        }
        float fMwstSatz1;
        public float MwstSatz1
        {
            get { return fMwstSatz1; }
            set { SetPropertyValue<float>("MwstSatz1", ref fMwstSatz1, value); }
        }
        decimal fAnteilNetto2;
        public decimal AnteilNetto2
        {
            get { return fAnteilNetto2; }
            set { SetPropertyValue<decimal>("AnteilNetto2", ref fAnteilNetto2, value); }
        }
        decimal fMwstBetrag2;
        public decimal MwstBetrag2
        {
            get { return fMwstBetrag2; }
            set { SetPropertyValue<decimal>("MwstBetrag2", ref fMwstBetrag2, value); }
        }
        float fMwstSatz2;
        public float MwstSatz2
        {
            get { return fMwstSatz2; }
            set { SetPropertyValue<float>("MwstSatz2", ref fMwstSatz2, value); }
        }
        decimal fAnteilNetto3;
        public decimal AnteilNetto3
        {
            get { return fAnteilNetto3; }
            set { SetPropertyValue<decimal>("AnteilNetto3", ref fAnteilNetto3, value); }
        }
        decimal fMwstBetrag3;
        public decimal MwstBetrag3
        {
            get { return fMwstBetrag3; }
            set { SetPropertyValue<decimal>("MwstBetrag3", ref fMwstBetrag3, value); }
        }
        float fMwstSatz3;
        public float MwstSatz3
        {
            get { return fMwstSatz3; }
            set { SetPropertyValue<float>("MwstSatz3", ref fMwstSatz3, value); }
        }
        decimal fAnteilNetto4;
        public decimal AnteilNetto4
        {
            get { return fAnteilNetto4; }
            set { SetPropertyValue<decimal>("AnteilNetto4", ref fAnteilNetto4, value); }
        }
        decimal fMwstBetrag4;
        public decimal MwstBetrag4
        {
            get { return fMwstBetrag4; }
            set { SetPropertyValue<decimal>("MwstBetrag4", ref fMwstBetrag4, value); }
        }
        float fMwstSatz4;
        public float MwstSatz4
        {
            get { return fMwstSatz4; }
            set { SetPropertyValue<float>("MwstSatz4", ref fMwstSatz4, value); }
        }
        decimal fAnteilNetto5;
        public decimal AnteilNetto5
        {
            get { return fAnteilNetto5; }
            set { SetPropertyValue<decimal>("AnteilNetto5", ref fAnteilNetto5, value); }
        }
        decimal fMwstBetrag5;
        public decimal MwstBetrag5
        {
            get { return fMwstBetrag5; }
            set { SetPropertyValue<decimal>("MwstBetrag5", ref fMwstBetrag5, value); }
        }
        float fMwstSatz5;
        public float MwstSatz5
        {
            get { return fMwstSatz5; }
            set { SetPropertyValue<float>("MwstSatz5", ref fMwstSatz5, value); }
        }
        decimal fAnteilNetto6;
        public decimal AnteilNetto6
        {
            get { return fAnteilNetto6; }
            set { SetPropertyValue<decimal>("AnteilNetto6", ref fAnteilNetto6, value); }
        }
        decimal fMwstBetrag6;
        public decimal MwstBetrag6
        {
            get { return fMwstBetrag6; }
            set { SetPropertyValue<decimal>("MwstBetrag6", ref fMwstBetrag6, value); }
        }
        float fMwstSatz6;
        public float MwstSatz6
        {
            get { return fMwstSatz6; }
            set { SetPropertyValue<float>("MwstSatz6", ref fMwstSatz6, value); }
        }
        decimal fAnteilNetto7;
        public decimal AnteilNetto7
        {
            get { return fAnteilNetto7; }
            set { SetPropertyValue<decimal>("AnteilNetto7", ref fAnteilNetto7, value); }
        }
        decimal fMwstBetrag7;
        public decimal MwstBetrag7
        {
            get { return fMwstBetrag7; }
            set { SetPropertyValue<decimal>("MwstBetrag7", ref fMwstBetrag7, value); }
        }
        float fMwstSatz7;
        public float MwstSatz7
        {
            get { return fMwstSatz7; }
            set { SetPropertyValue<float>("MwstSatz7", ref fMwstSatz7, value); }
        }
        decimal fAnteilNetto8;
        public decimal AnteilNetto8
        {
            get { return fAnteilNetto8; }
            set { SetPropertyValue<decimal>("AnteilNetto8", ref fAnteilNetto8, value); }
        }
        decimal fMwstBetrag8;
        public decimal MwstBetrag8
        {
            get { return fMwstBetrag8; }
            set { SetPropertyValue<decimal>("MwstBetrag8", ref fMwstBetrag8, value); }
        }
        float fMwstSatz8;
        public float MwstSatz8
        {
            get { return fMwstSatz8; }
            set { SetPropertyValue<float>("MwstSatz8", ref fMwstSatz8, value); }
        }
        decimal fAnteilNetto9;
        public decimal AnteilNetto9
        {
            get { return fAnteilNetto9; }
            set { SetPropertyValue<decimal>("AnteilNetto9", ref fAnteilNetto9, value); }
        }
        decimal fMwstBetrag9;
        public decimal MwstBetrag9
        {
            get { return fMwstBetrag9; }
            set { SetPropertyValue<decimal>("MwstBetrag9", ref fMwstBetrag9, value); }
        }
        float fMwstSatz9;
        public float MwstSatz9
        {
            get { return fMwstSatz9; }
            set { SetPropertyValue<float>("MwstSatz9", ref fMwstSatz9, value); }
        }
        decimal fAnteilNetto10;
        public decimal AnteilNetto10
        {
            get { return fAnteilNetto10; }
            set { SetPropertyValue<decimal>("AnteilNetto10", ref fAnteilNetto10, value); }
        }
        decimal fMwstBetrag10;
        public decimal MwstBetrag10
        {
            get { return fMwstBetrag10; }
            set { SetPropertyValue<decimal>("MwstBetrag10", ref fMwstBetrag10, value); }
        }
        float fMwstSatz10;
        public float MwstSatz10
        {
            get { return fMwstSatz10; }
            set { SetPropertyValue<float>("MwstSatz10", ref fMwstSatz10, value); }
        }
        decimal fAnteilNetto11;
        public decimal AnteilNetto11
        {
            get { return fAnteilNetto11; }
            set { SetPropertyValue<decimal>("AnteilNetto11", ref fAnteilNetto11, value); }
        }
        decimal fMwstBetrag11;
        public decimal MwstBetrag11
        {
            get { return fMwstBetrag11; }
            set { SetPropertyValue<decimal>("MwstBetrag11", ref fMwstBetrag11, value); }
        }
        float fMwstSatz11;
        public float MwstSatz11
        {
            get { return fMwstSatz11; }
            set { SetPropertyValue<float>("MwstSatz11", ref fMwstSatz11, value); }
        }
        decimal fAnteilNetto12;
        public decimal AnteilNetto12
        {
            get { return fAnteilNetto12; }
            set { SetPropertyValue<decimal>("AnteilNetto12", ref fAnteilNetto12, value); }
        }
        decimal fMwstBetrag12;
        public decimal MwstBetrag12
        {
            get { return fMwstBetrag12; }
            set { SetPropertyValue<decimal>("MwstBetrag12", ref fMwstBetrag12, value); }
        }
        float fMwstSatz12;
        public float MwstSatz12
        {
            get { return fMwstSatz12; }
            set { SetPropertyValue<float>("MwstSatz12", ref fMwstSatz12, value); }
        }
        decimal fAnteilNetto13;
        public decimal AnteilNetto13
        {
            get { return fAnteilNetto13; }
            set { SetPropertyValue<decimal>("AnteilNetto13", ref fAnteilNetto13, value); }
        }
        decimal fMwstBetrag13;
        public decimal MwstBetrag13
        {
            get { return fMwstBetrag13; }
            set { SetPropertyValue<decimal>("MwstBetrag13", ref fMwstBetrag13, value); }
        }
        float fMwstSatz13;
        public float MwstSatz13
        {
            get { return fMwstSatz13; }
            set { SetPropertyValue<float>("MwstSatz13", ref fMwstSatz13, value); }
        }
        decimal fAnteilNetto14;
        public decimal AnteilNetto14
        {
            get { return fAnteilNetto14; }
            set { SetPropertyValue<decimal>("AnteilNetto14", ref fAnteilNetto14, value); }
        }
        decimal fMwstBetrag14;
        public decimal MwstBetrag14
        {
            get { return fMwstBetrag14; }
            set { SetPropertyValue<decimal>("MwstBetrag14", ref fMwstBetrag14, value); }
        }
        float fMwstSatz14;
        public float MwstSatz14
        {
            get { return fMwstSatz14; }
            set { SetPropertyValue<float>("MwstSatz14", ref fMwstSatz14, value); }
        }
        decimal fAnteilNetto15;
        public decimal AnteilNetto15
        {
            get { return fAnteilNetto15; }
            set { SetPropertyValue<decimal>("AnteilNetto15", ref fAnteilNetto15, value); }
        }
        decimal fMwstBetrag15;
        public decimal MwstBetrag15
        {
            get { return fMwstBetrag15; }
            set { SetPropertyValue<decimal>("MwstBetrag15", ref fMwstBetrag15, value); }
        }
        float fMwstSatz15;
        public float MwstSatz15
        {
            get { return fMwstSatz15; }
            set { SetPropertyValue<float>("MwstSatz15", ref fMwstSatz15, value); }
        }
        double fKoArt1;
        public double KoArt1
        {
            get { return fKoArt1; }
            set { SetPropertyValue<double>("KoArt1", ref fKoArt1, value); }
        }
        double fKoArt2;
        public double KoArt2
        {
            get { return fKoArt2; }
            set { SetPropertyValue<double>("KoArt2", ref fKoArt2, value); }
        }
        double fKoArt3;
        public double KoArt3
        {
            get { return fKoArt3; }
            set { SetPropertyValue<double>("KoArt3", ref fKoArt3, value); }
        }
        double fKoArt4;
        public double KoArt4
        {
            get { return fKoArt4; }
            set { SetPropertyValue<double>("KoArt4", ref fKoArt4, value); }
        }
        double fKoArt5;
        public double KoArt5
        {
            get { return fKoArt5; }
            set { SetPropertyValue<double>("KoArt5", ref fKoArt5, value); }
        }
        double fKoArt6;
        public double KoArt6
        {
            get { return fKoArt6; }
            set { SetPropertyValue<double>("KoArt6", ref fKoArt6, value); }
        }
        double fKoArt7;
        public double KoArt7
        {
            get { return fKoArt7; }
            set { SetPropertyValue<double>("KoArt7", ref fKoArt7, value); }
        }
        double fKoArt8;
        public double KoArt8
        {
            get { return fKoArt8; }
            set { SetPropertyValue<double>("KoArt8", ref fKoArt8, value); }
        }
        double fKoArt9;
        public double KoArt9
        {
            get { return fKoArt9; }
            set { SetPropertyValue<double>("KoArt9", ref fKoArt9, value); }
        }
        double fKoArt10;
        public double KoArt10
        {
            get { return fKoArt10; }
            set { SetPropertyValue<double>("KoArt10", ref fKoArt10, value); }
        }
        double fKoArt11;
        public double KoArt11
        {
            get { return fKoArt11; }
            set { SetPropertyValue<double>("KoArt11", ref fKoArt11, value); }
        }
        double fKoArt12;
        public double KoArt12
        {
            get { return fKoArt12; }
            set { SetPropertyValue<double>("KoArt12", ref fKoArt12, value); }
        }
        double fKoArt13;
        public double KoArt13
        {
            get { return fKoArt13; }
            set { SetPropertyValue<double>("KoArt13", ref fKoArt13, value); }
        }
        double fKoArt14;
        public double KoArt14
        {
            get { return fKoArt14; }
            set { SetPropertyValue<double>("KoArt14", ref fKoArt14, value); }
        }
        double fKoArt15;
        public double KoArt15
        {
            get { return fKoArt15; }
            set { SetPropertyValue<double>("KoArt15", ref fKoArt15, value); }
        }
        double fKoArt16;
        public double KoArt16
        {
            get { return fKoArt16; }
            set { SetPropertyValue<double>("KoArt16", ref fKoArt16, value); }
        }
        double fKoArt17;
        public double KoArt17
        {
            get { return fKoArt17; }
            set { SetPropertyValue<double>("KoArt17", ref fKoArt17, value); }
        }
        double fKoArt18;
        public double KoArt18
        {
            get { return fKoArt18; }
            set { SetPropertyValue<double>("KoArt18", ref fKoArt18, value); }
        }
        double fKoArt19;
        public double KoArt19
        {
            get { return fKoArt19; }
            set { SetPropertyValue<double>("KoArt19", ref fKoArt19, value); }
        }
        double fKoArt20;
        public double KoArt20
        {
            get { return fKoArt20; }
            set { SetPropertyValue<double>("KoArt20", ref fKoArt20, value); }
        }
        double fKoArt21;
        public double KoArt21
        {
            get { return fKoArt21; }
            set { SetPropertyValue<double>("KoArt21", ref fKoArt21, value); }
        }
        double fKoArt22;
        public double KoArt22
        {
            get { return fKoArt22; }
            set { SetPropertyValue<double>("KoArt22", ref fKoArt22, value); }
        }
        double fKoArt23;
        public double KoArt23
        {
            get { return fKoArt23; }
            set { SetPropertyValue<double>("KoArt23", ref fKoArt23, value); }
        }
        double fKoArt24;
        public double KoArt24
        {
            get { return fKoArt24; }
            set { SetPropertyValue<double>("KoArt24", ref fKoArt24, value); }
        }
        double fKoArt25;
        public double KoArt25
        {
            get { return fKoArt25; }
            set { SetPropertyValue<double>("KoArt25", ref fKoArt25, value); }
        }
        double fKoArt26;
        public double KoArt26
        {
            get { return fKoArt26; }
            set { SetPropertyValue<double>("KoArt26", ref fKoArt26, value); }
        }
        double fKoArt27;
        public double KoArt27
        {
            get { return fKoArt27; }
            set { SetPropertyValue<double>("KoArt27", ref fKoArt27, value); }
        }
        double fKoArt28;
        public double KoArt28
        {
            get { return fKoArt28; }
            set { SetPropertyValue<double>("KoArt28", ref fKoArt28, value); }
        }
        double fKoArt29;
        public double KoArt29
        {
            get { return fKoArt29; }
            set { SetPropertyValue<double>("KoArt29", ref fKoArt29, value); }
        }
        double fKoArt30;
        public double KoArt30
        {
            get { return fKoArt30; }
            set { SetPropertyValue<double>("KoArt30", ref fKoArt30, value); }
        }
        double fKoArt31;
        public double KoArt31
        {
            get { return fKoArt31; }
            set { SetPropertyValue<double>("KoArt31", ref fKoArt31, value); }
        }
        double fKoArt32;
        public double KoArt32
        {
            get { return fKoArt32; }
            set { SetPropertyValue<double>("KoArt32", ref fKoArt32, value); }
        }
        double fKoArt33;
        public double KoArt33
        {
            get { return fKoArt33; }
            set { SetPropertyValue<double>("KoArt33", ref fKoArt33, value); }
        }
        double fKoArt34;
        public double KoArt34
        {
            get { return fKoArt34; }
            set { SetPropertyValue<double>("KoArt34", ref fKoArt34, value); }
        }
        double fKoArt35;
        public double KoArt35
        {
            get { return fKoArt35; }
            set { SetPropertyValue<double>("KoArt35", ref fKoArt35, value); }
        }
        double fKoArt36;
        public double KoArt36
        {
            get { return fKoArt36; }
            set { SetPropertyValue<double>("KoArt36", ref fKoArt36, value); }
        }
        double fKoArt37;
        public double KoArt37
        {
            get { return fKoArt37; }
            set { SetPropertyValue<double>("KoArt37", ref fKoArt37, value); }
        }
        double fKoArt38;
        public double KoArt38
        {
            get { return fKoArt38; }
            set { SetPropertyValue<double>("KoArt38", ref fKoArt38, value); }
        }
        double fKoArt39;
        public double KoArt39
        {
            get { return fKoArt39; }
            set { SetPropertyValue<double>("KoArt39", ref fKoArt39, value); }
        }
        double fKoArt40;
        public double KoArt40
        {
            get { return fKoArt40; }
            set { SetPropertyValue<double>("KoArt40", ref fKoArt40, value); }
        }
        double fKoArt41;
        public double KoArt41
        {
            get { return fKoArt41; }
            set { SetPropertyValue<double>("KoArt41", ref fKoArt41, value); }
        }
        double fKoArt42;
        public double KoArt42
        {
            get { return fKoArt42; }
            set { SetPropertyValue<double>("KoArt42", ref fKoArt42, value); }
        }
        double fKoArt43;
        public double KoArt43
        {
            get { return fKoArt43; }
            set { SetPropertyValue<double>("KoArt43", ref fKoArt43, value); }
        }
        double fKoArt44;
        public double KoArt44
        {
            get { return fKoArt44; }
            set { SetPropertyValue<double>("KoArt44", ref fKoArt44, value); }
        }
        double fKoArt45;
        public double KoArt45
        {
            get { return fKoArt45; }
            set { SetPropertyValue<double>("KoArt45", ref fKoArt45, value); }
        }
        double fKoArt46;
        public double KoArt46
        {
            get { return fKoArt46; }
            set { SetPropertyValue<double>("KoArt46", ref fKoArt46, value); }
        }
        double fKoArt47;
        public double KoArt47
        {
            get { return fKoArt47; }
            set { SetPropertyValue<double>("KoArt47", ref fKoArt47, value); }
        }
        double fKoArt48;
        public double KoArt48
        {
            get { return fKoArt48; }
            set { SetPropertyValue<double>("KoArt48", ref fKoArt48, value); }
        }
        double fKoArt49;
        public double KoArt49
        {
            get { return fKoArt49; }
            set { SetPropertyValue<double>("KoArt49", ref fKoArt49, value); }
        }
        double fKoArt50;
        public double KoArt50
        {
            get { return fKoArt50; }
            set { SetPropertyValue<double>("KoArt50", ref fKoArt50, value); }
        }
        double fKoArt51;
        public double KoArt51
        {
            get { return fKoArt51; }
            set { SetPropertyValue<double>("KoArt51", ref fKoArt51, value); }
        }
        double fKoArt52;
        public double KoArt52
        {
            get { return fKoArt52; }
            set { SetPropertyValue<double>("KoArt52", ref fKoArt52, value); }
        }
        double fKoArt53;
        public double KoArt53
        {
            get { return fKoArt53; }
            set { SetPropertyValue<double>("KoArt53", ref fKoArt53, value); }
        }
        double fKoArt54;
        public double KoArt54
        {
            get { return fKoArt54; }
            set { SetPropertyValue<double>("KoArt54", ref fKoArt54, value); }
        }
        double fKoArt55;
        public double KoArt55
        {
            get { return fKoArt55; }
            set { SetPropertyValue<double>("KoArt55", ref fKoArt55, value); }
        }
        double fKoArt56;
        public double KoArt56
        {
            get { return fKoArt56; }
            set { SetPropertyValue<double>("KoArt56", ref fKoArt56, value); }
        }
        double fKoArt57;
        public double KoArt57
        {
            get { return fKoArt57; }
            set { SetPropertyValue<double>("KoArt57", ref fKoArt57, value); }
        }
        double fKoArt58;
        public double KoArt58
        {
            get { return fKoArt58; }
            set { SetPropertyValue<double>("KoArt58", ref fKoArt58, value); }
        }
        double fKoArt59;
        public double KoArt59
        {
            get { return fKoArt59; }
            set { SetPropertyValue<double>("KoArt59", ref fKoArt59, value); }
        }
        double fKoArt60;
        public double KoArt60
        {
            get { return fKoArt60; }
            set { SetPropertyValue<double>("KoArt60", ref fKoArt60, value); }
        }
        double fKoArt61;
        public double KoArt61
        {
            get { return fKoArt61; }
            set { SetPropertyValue<double>("KoArt61", ref fKoArt61, value); }
        }
        double fKoArt62;
        public double KoArt62
        {
            get { return fKoArt62; }
            set { SetPropertyValue<double>("KoArt62", ref fKoArt62, value); }
        }
        double fKoArt63;
        public double KoArt63
        {
            get { return fKoArt63; }
            set { SetPropertyValue<double>("KoArt63", ref fKoArt63, value); }
        }
        double fKoArt64;
        public double KoArt64
        {
            get { return fKoArt64; }
            set { SetPropertyValue<double>("KoArt64", ref fKoArt64, value); }
        }
        double fKoArt65;
        public double KoArt65
        {
            get { return fKoArt65; }
            set { SetPropertyValue<double>("KoArt65", ref fKoArt65, value); }
        }
        double fKoArt66;
        public double KoArt66
        {
            get { return fKoArt66; }
            set { SetPropertyValue<double>("KoArt66", ref fKoArt66, value); }
        }
        double fKoArt67;
        public double KoArt67
        {
            get { return fKoArt67; }
            set { SetPropertyValue<double>("KoArt67", ref fKoArt67, value); }
        }
        double fKoArt68;
        public double KoArt68
        {
            get { return fKoArt68; }
            set { SetPropertyValue<double>("KoArt68", ref fKoArt68, value); }
        }
        double fKoArt69;
        public double KoArt69
        {
            get { return fKoArt69; }
            set { SetPropertyValue<double>("KoArt69", ref fKoArt69, value); }
        }
        double fKoArt70;
        public double KoArt70
        {
            get { return fKoArt70; }
            set { SetPropertyValue<double>("KoArt70", ref fKoArt70, value); }
        }
        double fKoArt71;
        public double KoArt71
        {
            get { return fKoArt71; }
            set { SetPropertyValue<double>("KoArt71", ref fKoArt71, value); }
        }
        double fKoArt72;
        public double KoArt72
        {
            get { return fKoArt72; }
            set { SetPropertyValue<double>("KoArt72", ref fKoArt72, value); }
        }
        double fKoArt73;
        public double KoArt73
        {
            get { return fKoArt73; }
            set { SetPropertyValue<double>("KoArt73", ref fKoArt73, value); }
        }
        double fKoArt74;
        public double KoArt74
        {
            get { return fKoArt74; }
            set { SetPropertyValue<double>("KoArt74", ref fKoArt74, value); }
        }
        double fKoArt75;
        public double KoArt75
        {
            get { return fKoArt75; }
            set { SetPropertyValue<double>("KoArt75", ref fKoArt75, value); }
        }
        double fKoArt76;
        public double KoArt76
        {
            get { return fKoArt76; }
            set { SetPropertyValue<double>("KoArt76", ref fKoArt76, value); }
        }
        double fKoArt77;
        public double KoArt77
        {
            get { return fKoArt77; }
            set { SetPropertyValue<double>("KoArt77", ref fKoArt77, value); }
        }
        double fKoArt78;
        public double KoArt78
        {
            get { return fKoArt78; }
            set { SetPropertyValue<double>("KoArt78", ref fKoArt78, value); }
        }
        double fKoArt79;
        public double KoArt79
        {
            get { return fKoArt79; }
            set { SetPropertyValue<double>("KoArt79", ref fKoArt79, value); }
        }
        double fKoArt80;
        public double KoArt80
        {
            get { return fKoArt80; }
            set { SetPropertyValue<double>("KoArt80", ref fKoArt80, value); }
        }
        double fKoArt81;
        public double KoArt81
        {
            get { return fKoArt81; }
            set { SetPropertyValue<double>("KoArt81", ref fKoArt81, value); }
        }
        double fKoArt82;
        public double KoArt82
        {
            get { return fKoArt82; }
            set { SetPropertyValue<double>("KoArt82", ref fKoArt82, value); }
        }
        double fKoArt83;
        public double KoArt83
        {
            get { return fKoArt83; }
            set { SetPropertyValue<double>("KoArt83", ref fKoArt83, value); }
        }
        double fKoArt84;
        public double KoArt84
        {
            get { return fKoArt84; }
            set { SetPropertyValue<double>("KoArt84", ref fKoArt84, value); }
        }
        double fKoArt85;
        public double KoArt85
        {
            get { return fKoArt85; }
            set { SetPropertyValue<double>("KoArt85", ref fKoArt85, value); }
        }
        double fKoArt86;
        public double KoArt86
        {
            get { return fKoArt86; }
            set { SetPropertyValue<double>("KoArt86", ref fKoArt86, value); }
        }
        double fKoArt87;
        public double KoArt87
        {
            get { return fKoArt87; }
            set { SetPropertyValue<double>("KoArt87", ref fKoArt87, value); }
        }
        double fKoArt88;
        public double KoArt88
        {
            get { return fKoArt88; }
            set { SetPropertyValue<double>("KoArt88", ref fKoArt88, value); }
        }
        double fKoArt89;
        public double KoArt89
        {
            get { return fKoArt89; }
            set { SetPropertyValue<double>("KoArt89", ref fKoArt89, value); }
        }
        double fKoArt90;
        public double KoArt90
        {
            get { return fKoArt90; }
            set { SetPropertyValue<double>("KoArt90", ref fKoArt90, value); }
        }
        double fKoArt91;
        public double KoArt91
        {
            get { return fKoArt91; }
            set { SetPropertyValue<double>("KoArt91", ref fKoArt91, value); }
        }
        double fKoArt92;
        public double KoArt92
        {
            get { return fKoArt92; }
            set { SetPropertyValue<double>("KoArt92", ref fKoArt92, value); }
        }
        double fKoArt93;
        public double KoArt93
        {
            get { return fKoArt93; }
            set { SetPropertyValue<double>("KoArt93", ref fKoArt93, value); }
        }
        double fKoArt94;
        public double KoArt94
        {
            get { return fKoArt94; }
            set { SetPropertyValue<double>("KoArt94", ref fKoArt94, value); }
        }
        double fKoArt95;
        public double KoArt95
        {
            get { return fKoArt95; }
            set { SetPropertyValue<double>("KoArt95", ref fKoArt95, value); }
        }
        double fKoArt96;
        public double KoArt96
        {
            get { return fKoArt96; }
            set { SetPropertyValue<double>("KoArt96", ref fKoArt96, value); }
        }
        double fKoArt97;
        public double KoArt97
        {
            get { return fKoArt97; }
            set { SetPropertyValue<double>("KoArt97", ref fKoArt97, value); }
        }
        double fKoArt98;
        public double KoArt98
        {
            get { return fKoArt98; }
            set { SetPropertyValue<double>("KoArt98", ref fKoArt98, value); }
        }
        double fKoArt99;
        public double KoArt99
        {
            get { return fKoArt99; }
            set { SetPropertyValue<double>("KoArt99", ref fKoArt99, value); }
        }
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        DateTime fKaBuDatum;
        public DateTime KaBuDatum
        {
            get { return fKaBuDatum; }
            set { SetPropertyValue<DateTime>("KaBuDatum", ref fKaBuDatum, value); }
        }
    }

}
