//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class DatanormDownloadFiles : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        DatanormDownLoadFile ffkDatanormDownloadFile;
        [Association(@"DatanormDownloadFilesReferencesDatanormDownLoadFile")]
        public DatanormDownLoadFile fkDatanormDownloadFile
        {
            get { return ffkDatanormDownloadFile; }
            set { SetPropertyValue<DatanormDownLoadFile>("fkDatanormDownloadFile", ref ffkDatanormDownloadFile, value); }
        }
        string fFileName;
        [Size(50)]
        public string FileName
        {
            get { return fFileName; }
            set { SetPropertyValue<string>("FileName", ref fFileName, value); }
        }
        short fRangfolge;
        [Indexed(Name = @"IX_DatanormDownloadFilesRangfolge")]
        public short Rangfolge
        {
            get { return fRangfolge; }
            set { SetPropertyValue<short>("Rangfolge", ref fRangfolge, value); }
        }
        bool fEinlesen;
        public bool Einlesen
        {
            get { return fEinlesen; }
            set { SetPropertyValue<bool>("Einlesen", ref fEinlesen, value); }
        }
    }

}
