//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class DatanormDownLoadFile : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        DatanormDownload ffkDatanormDownload;
        [Association(@"DatanormDownLoadFileReferencesDatanormDownload")]
        public DatanormDownload fkDatanormDownload
        {
            get { return ffkDatanormDownload; }
            set { SetPropertyValue<DatanormDownload>("fkDatanormDownload", ref ffkDatanormDownload, value); }
        }
        string fDownloadFile;
        [Indexed(Name = @"IX_DatanormDownLoadFileDownLoad")]
        [Size(255)]
        public string DownloadFile
        {
            get { return fDownloadFile; }
            set { SetPropertyValue<string>("DownloadFile", ref fDownloadFile, value); }
        }
        double fWebID;
        [Indexed(Name = @"IX_DatanormDownLoadFileWebID")]
        public double WebID
        {
            get { return fWebID; }
            set { SetPropertyValue<double>("WebID", ref fWebID, value); }
        }
        bool fDownLoad;
        public bool DownLoad
        {
            get { return fDownLoad; }
            set { SetPropertyValue<bool>("DownLoad", ref fDownLoad, value); }
        }
        short fRangfolge;
        [Indexed(Name = @"IX_DatanormDownLoadFileRangfolge")]
        public short Rangfolge
        {
            get { return fRangfolge; }
            set { SetPropertyValue<short>("Rangfolge", ref fRangfolge, value); }
        }
        string fUserLastDownLoad;
        [Size(8)]
        public string UserLastDownLoad
        {
            get { return fUserLastDownLoad; }
            set { SetPropertyValue<string>("UserLastDownLoad", ref fUserLastDownLoad, value); }
        }
        DateTime fDateLastDownload;
        public DateTime DateLastDownload
        {
            get { return fDateLastDownload; }
            set { SetPropertyValue<DateTime>("DateLastDownload", ref fDateLastDownload, value); }
        }
        DateTime fFileDateLastDownload;
        public DateTime FileDateLastDownload
        {
            get { return fFileDateLastDownload; }
            set { SetPropertyValue<DateTime>("FileDateLastDownload", ref fFileDateLastDownload, value); }
        }
        [Association(@"DatanormDownloadFilesReferencesDatanormDownLoadFile")]
        public XPCollection<DatanormDownloadFiles> DatanormDownloadFilesCollection { get { return GetCollection<DatanormDownloadFiles>("DatanormDownloadFilesCollection"); } }
    }

}
