//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class EMailBuch : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        short fItemType;
        public short ItemType
        {
            get { return fItemType; }
            set { SetPropertyValue<short>("ItemType", ref fItemType, value); }
        }
        int fParentID;
        public int ParentID
        {
            get { return fParentID; }
            set { SetPropertyValue<int>("ParentID", ref fParentID, value); }
        }
        string fEigentuemer;
        [Size(15)]
        public string Eigentuemer
        {
            get { return fEigentuemer; }
            set { SetPropertyValue<string>("Eigentuemer", ref fEigentuemer, value); }
        }
        int fLinkID;
        [Indexed(Name = @"IX_EMailBuchLinkID")]
        public int LinkID
        {
            get { return fLinkID; }
            set { SetPropertyValue<int>("LinkID", ref fLinkID, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fKontakt;
        [Size(50)]
        public string Kontakt
        {
            get { return fKontakt; }
            set { SetPropertyValue<string>("Kontakt", ref fKontakt, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        int fArt;
        public int Art
        {
            get { return fArt; }
            set { SetPropertyValue<int>("Art", ref fArt, value); }
        }
        string fBenFeld;
        [Size(50)]
        public string BenFeld
        {
            get { return fBenFeld; }
            set { SetPropertyValue<string>("BenFeld", ref fBenFeld, value); }
        }
    }

}
