//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{
    [DefaultProperty("ErlGrp_MatchKey")]
    public partial class ErlGrp : XPLiteObject
    {
        int fABTNR;
        [Key]
        public int ABTNR
        {
            get { return fABTNR; }
            set { SetPropertyValue<int>("ABTNR", ref fABTNR, value); }
        }
        string fABTTEXT;
        [Size(40)]
        public string ABTTEXT
        {
            get { return fABTTEXT; }
            set { SetPropertyValue<string>("ABTTEXT", ref fABTTEXT, value); }
        }
        double fERLBETRAG1;
        public double ERLBETRAG1
        {
            get { return fERLBETRAG1; }
            set { SetPropertyValue<double>("ERLBETRAG1", ref fERLBETRAG1, value); }
        }
        double fERLBETRAG2;
        public double ERLBETRAG2
        {
            get { return fERLBETRAG2; }
            set { SetPropertyValue<double>("ERLBETRAG2", ref fERLBETRAG2, value); }
        }
        double fERLBETRAG3;
        public double ERLBETRAG3
        {
            get { return fERLBETRAG3; }
            set { SetPropertyValue<double>("ERLBETRAG3", ref fERLBETRAG3, value); }
        }
        double fERLBETRAG4;
        public double ERLBETRAG4
        {
            get { return fERLBETRAG4; }
            set { SetPropertyValue<double>("ERLBETRAG4", ref fERLBETRAG4, value); }
        }
        double fERLBETRAG5;
        public double ERLBETRAG5
        {
            get { return fERLBETRAG5; }
            set { SetPropertyValue<double>("ERLBETRAG5", ref fERLBETRAG5, value); }
        }
        double fERLBETRAG6;
        public double ERLBETRAG6
        {
            get { return fERLBETRAG6; }
            set { SetPropertyValue<double>("ERLBETRAG6", ref fERLBETRAG6, value); }
        }
        double fERLBETRAG7;
        public double ERLBETRAG7
        {
            get { return fERLBETRAG7; }
            set { SetPropertyValue<double>("ERLBETRAG7", ref fERLBETRAG7, value); }
        }
        double fERLBETRAG8;
        public double ERLBETRAG8
        {
            get { return fERLBETRAG8; }
            set { SetPropertyValue<double>("ERLBETRAG8", ref fERLBETRAG8, value); }
        }
        double fERLBETRAG9;
        public double ERLBETRAG9
        {
            get { return fERLBETRAG9; }
            set { SetPropertyValue<double>("ERLBETRAG9", ref fERLBETRAG9, value); }
        }
        double fERLBETRAG10;
        public double ERLBETRAG10
        {
            get { return fERLBETRAG10; }
            set { SetPropertyValue<double>("ERLBETRAG10", ref fERLBETRAG10, value); }
        }
        double fERLBETRAG11;
        public double ERLBETRAG11
        {
            get { return fERLBETRAG11; }
            set { SetPropertyValue<double>("ERLBETRAG11", ref fERLBETRAG11, value); }
        }
        double fERLBETRAG12;
        public double ERLBETRAG12
        {
            get { return fERLBETRAG12; }
            set { SetPropertyValue<double>("ERLBETRAG12", ref fERLBETRAG12, value); }
        }
        double fERLBETRAG13;
        public double ERLBETRAG13
        {
            get { return fERLBETRAG13; }
            set { SetPropertyValue<double>("ERLBETRAG13", ref fERLBETRAG13, value); }
        }
        double fERLBETRAG14;
        public double ERLBETRAG14
        {
            get { return fERLBETRAG14; }
            set { SetPropertyValue<double>("ERLBETRAG14", ref fERLBETRAG14, value); }
        }
        double fERLBETRAG15;
        public double ERLBETRAG15
        {
            get { return fERLBETRAG15; }
            set { SetPropertyValue<double>("ERLBETRAG15", ref fERLBETRAG15, value); }
        }
        double fERLBETRAG16;
        public double ERLBETRAG16
        {
            get { return fERLBETRAG16; }
            set { SetPropertyValue<double>("ERLBETRAG16", ref fERLBETRAG16, value); }
        }
        double fERLBETRAG17;
        public double ERLBETRAG17
        {
            get { return fERLBETRAG17; }
            set { SetPropertyValue<double>("ERLBETRAG17", ref fERLBETRAG17, value); }
        }
        double fERLBETRAG18;
        public double ERLBETRAG18
        {
            get { return fERLBETRAG18; }
            set { SetPropertyValue<double>("ERLBETRAG18", ref fERLBETRAG18, value); }
        }
        double fERLBETRAG19;
        public double ERLBETRAG19
        {
            get { return fERLBETRAG19; }
            set { SetPropertyValue<double>("ERLBETRAG19", ref fERLBETRAG19, value); }
        }
        double fERLBETRAG20;
        public double ERLBETRAG20
        {
            get { return fERLBETRAG20; }
            set { SetPropertyValue<double>("ERLBETRAG20", ref fERLBETRAG20, value); }
        }
        double fERLBETRAG21;
        public double ERLBETRAG21
        {
            get { return fERLBETRAG21; }
            set { SetPropertyValue<double>("ERLBETRAG21", ref fERLBETRAG21, value); }
        }
        double fERLBETRAG22;
        public double ERLBETRAG22
        {
            get { return fERLBETRAG22; }
            set { SetPropertyValue<double>("ERLBETRAG22", ref fERLBETRAG22, value); }
        }
        double fERLBETRAG23;
        public double ERLBETRAG23
        {
            get { return fERLBETRAG23; }
            set { SetPropertyValue<double>("ERLBETRAG23", ref fERLBETRAG23, value); }
        }
        double fERLBETRAG24;
        public double ERLBETRAG24
        {
            get { return fERLBETRAG24; }
            set { SetPropertyValue<double>("ERLBETRAG24", ref fERLBETRAG24, value); }
        }
        double fERLBETRAG25;
        public double ERLBETRAG25
        {
            get { return fERLBETRAG25; }
            set { SetPropertyValue<double>("ERLBETRAG25", ref fERLBETRAG25, value); }
        }
        double fERLBETRAG26;
        public double ERLBETRAG26
        {
            get { return fERLBETRAG26; }
            set { SetPropertyValue<double>("ERLBETRAG26", ref fERLBETRAG26, value); }
        }
        double fERLBETRAG27;
        public double ERLBETRAG27
        {
            get { return fERLBETRAG27; }
            set { SetPropertyValue<double>("ERLBETRAG27", ref fERLBETRAG27, value); }
        }
        double fERLBETRAG28;
        public double ERLBETRAG28
        {
            get { return fERLBETRAG28; }
            set { SetPropertyValue<double>("ERLBETRAG28", ref fERLBETRAG28, value); }
        }
        double fERLBETRAG29;
        public double ERLBETRAG29
        {
            get { return fERLBETRAG29; }
            set { SetPropertyValue<double>("ERLBETRAG29", ref fERLBETRAG29, value); }
        }
        double fERLBETRAG30;
        public double ERLBETRAG30
        {
            get { return fERLBETRAG30; }
            set { SetPropertyValue<double>("ERLBETRAG30", ref fERLBETRAG30, value); }
        }
        double fERLBETRAG31;
        public double ERLBETRAG31
        {
            get { return fERLBETRAG31; }
            set { SetPropertyValue<double>("ERLBETRAG31", ref fERLBETRAG31, value); }
        }
        double fERLBETRAG32;
        public double ERLBETRAG32
        {
            get { return fERLBETRAG32; }
            set { SetPropertyValue<double>("ERLBETRAG32", ref fERLBETRAG32, value); }
        }
        double fERLBETRAG33;
        public double ERLBETRAG33
        {
            get { return fERLBETRAG33; }
            set { SetPropertyValue<double>("ERLBETRAG33", ref fERLBETRAG33, value); }
        }
        double fERLBETRAG34;
        public double ERLBETRAG34
        {
            get { return fERLBETRAG34; }
            set { SetPropertyValue<double>("ERLBETRAG34", ref fERLBETRAG34, value); }
        }
        double fERLBETRAG35;
        public double ERLBETRAG35
        {
            get { return fERLBETRAG35; }
            set { SetPropertyValue<double>("ERLBETRAG35", ref fERLBETRAG35, value); }
        }
        double fERLBETRAG36;
        public double ERLBETRAG36
        {
            get { return fERLBETRAG36; }
            set { SetPropertyValue<double>("ERLBETRAG36", ref fERLBETRAG36, value); }
        }
        double fERLBETRAG37;
        public double ERLBETRAG37
        {
            get { return fERLBETRAG37; }
            set { SetPropertyValue<double>("ERLBETRAG37", ref fERLBETRAG37, value); }
        }
        double fERLBETRAG38;
        public double ERLBETRAG38
        {
            get { return fERLBETRAG38; }
            set { SetPropertyValue<double>("ERLBETRAG38", ref fERLBETRAG38, value); }
        }
        double fERLBETRAG39;
        public double ERLBETRAG39
        {
            get { return fERLBETRAG39; }
            set { SetPropertyValue<double>("ERLBETRAG39", ref fERLBETRAG39, value); }
        }
        double fERLBETRAG40;
        public double ERLBETRAG40
        {
            get { return fERLBETRAG40; }
            set { SetPropertyValue<double>("ERLBETRAG40", ref fERLBETRAG40, value); }
        }
        double fERLBETRAG41;
        public double ERLBETRAG41
        {
            get { return fERLBETRAG41; }
            set { SetPropertyValue<double>("ERLBETRAG41", ref fERLBETRAG41, value); }
        }
        double fERLBETRAG42;
        public double ERLBETRAG42
        {
            get { return fERLBETRAG42; }
            set { SetPropertyValue<double>("ERLBETRAG42", ref fERLBETRAG42, value); }
        }
        double fERLBETRAG43;
        public double ERLBETRAG43
        {
            get { return fERLBETRAG43; }
            set { SetPropertyValue<double>("ERLBETRAG43", ref fERLBETRAG43, value); }
        }
        double fERLBETRAG44;
        public double ERLBETRAG44
        {
            get { return fERLBETRAG44; }
            set { SetPropertyValue<double>("ERLBETRAG44", ref fERLBETRAG44, value); }
        }
        double fERLBETRAG45;
        public double ERLBETRAG45
        {
            get { return fERLBETRAG45; }
            set { SetPropertyValue<double>("ERLBETRAG45", ref fERLBETRAG45, value); }
        }
        double fERLBETRAG46;
        public double ERLBETRAG46
        {
            get { return fERLBETRAG46; }
            set { SetPropertyValue<double>("ERLBETRAG46", ref fERLBETRAG46, value); }
        }
        double fERLBETRAG47;
        public double ERLBETRAG47
        {
            get { return fERLBETRAG47; }
            set { SetPropertyValue<double>("ERLBETRAG47", ref fERLBETRAG47, value); }
        }
        double fERLBETRAG48;
        public double ERLBETRAG48
        {
            get { return fERLBETRAG48; }
            set { SetPropertyValue<double>("ERLBETRAG48", ref fERLBETRAG48, value); }
        }
        double fERLBETRAG49;
        public double ERLBETRAG49
        {
            get { return fERLBETRAG49; }
            set { SetPropertyValue<double>("ERLBETRAG49", ref fERLBETRAG49, value); }
        }
        double fERLBETRAG50;
        public double ERLBETRAG50
        {
            get { return fERLBETRAG50; }
            set { SetPropertyValue<double>("ERLBETRAG50", ref fERLBETRAG50, value); }
        }
        double fERLBETRAG51;
        public double ERLBETRAG51
        {
            get { return fERLBETRAG51; }
            set { SetPropertyValue<double>("ERLBETRAG51", ref fERLBETRAG51, value); }
        }
        double fERLBETRAG52;
        public double ERLBETRAG52
        {
            get { return fERLBETRAG52; }
            set { SetPropertyValue<double>("ERLBETRAG52", ref fERLBETRAG52, value); }
        }
        double fERLBETRAG53;
        public double ERLBETRAG53
        {
            get { return fERLBETRAG53; }
            set { SetPropertyValue<double>("ERLBETRAG53", ref fERLBETRAG53, value); }
        }
        double fERLBETRAG54;
        public double ERLBETRAG54
        {
            get { return fERLBETRAG54; }
            set { SetPropertyValue<double>("ERLBETRAG54", ref fERLBETRAG54, value); }
        }
        double fERLBETRAG55;
        public double ERLBETRAG55
        {
            get { return fERLBETRAG55; }
            set { SetPropertyValue<double>("ERLBETRAG55", ref fERLBETRAG55, value); }
        }
        double fERLBETRAG56;
        public double ERLBETRAG56
        {
            get { return fERLBETRAG56; }
            set { SetPropertyValue<double>("ERLBETRAG56", ref fERLBETRAG56, value); }
        }
        double fERLBETRAG57;
        public double ERLBETRAG57
        {
            get { return fERLBETRAG57; }
            set { SetPropertyValue<double>("ERLBETRAG57", ref fERLBETRAG57, value); }
        }
        double fERLBETRAG58;
        public double ERLBETRAG58
        {
            get { return fERLBETRAG58; }
            set { SetPropertyValue<double>("ERLBETRAG58", ref fERLBETRAG58, value); }
        }
        double fERLBETRAG59;
        public double ERLBETRAG59
        {
            get { return fERLBETRAG59; }
            set { SetPropertyValue<double>("ERLBETRAG59", ref fERLBETRAG59, value); }
        }
        double fERLBETRAG60;
        public double ERLBETRAG60
        {
            get { return fERLBETRAG60; }
            set { SetPropertyValue<double>("ERLBETRAG60", ref fERLBETRAG60, value); }
        }
        double fERLBETRAG61;
        public double ERLBETRAG61
        {
            get { return fERLBETRAG61; }
            set { SetPropertyValue<double>("ERLBETRAG61", ref fERLBETRAG61, value); }
        }
        double fERLBETRAG62;
        public double ERLBETRAG62
        {
            get { return fERLBETRAG62; }
            set { SetPropertyValue<double>("ERLBETRAG62", ref fERLBETRAG62, value); }
        }
        double fERLBETRAG63;
        public double ERLBETRAG63
        {
            get { return fERLBETRAG63; }
            set { SetPropertyValue<double>("ERLBETRAG63", ref fERLBETRAG63, value); }
        }
        double fERLBETRAG64;
        public double ERLBETRAG64
        {
            get { return fERLBETRAG64; }
            set { SetPropertyValue<double>("ERLBETRAG64", ref fERLBETRAG64, value); }
        }
        double fERLBETRAG65;
        public double ERLBETRAG65
        {
            get { return fERLBETRAG65; }
            set { SetPropertyValue<double>("ERLBETRAG65", ref fERLBETRAG65, value); }
        }
        double fERLBETRAG66;
        public double ERLBETRAG66
        {
            get { return fERLBETRAG66; }
            set { SetPropertyValue<double>("ERLBETRAG66", ref fERLBETRAG66, value); }
        }
        double fERLBETRAG67;
        public double ERLBETRAG67
        {
            get { return fERLBETRAG67; }
            set { SetPropertyValue<double>("ERLBETRAG67", ref fERLBETRAG67, value); }
        }
        double fERLBETRAG68;
        public double ERLBETRAG68
        {
            get { return fERLBETRAG68; }
            set { SetPropertyValue<double>("ERLBETRAG68", ref fERLBETRAG68, value); }
        }
        double fERLBETRAG69;
        public double ERLBETRAG69
        {
            get { return fERLBETRAG69; }
            set { SetPropertyValue<double>("ERLBETRAG69", ref fERLBETRAG69, value); }
        }
        double fERLBETRAG70;
        public double ERLBETRAG70
        {
            get { return fERLBETRAG70; }
            set { SetPropertyValue<double>("ERLBETRAG70", ref fERLBETRAG70, value); }
        }
        double fERLBETRAG71;
        public double ERLBETRAG71
        {
            get { return fERLBETRAG71; }
            set { SetPropertyValue<double>("ERLBETRAG71", ref fERLBETRAG71, value); }
        }
        double fERLBETRAG72;
        public double ERLBETRAG72
        {
            get { return fERLBETRAG72; }
            set { SetPropertyValue<double>("ERLBETRAG72", ref fERLBETRAG72, value); }
        }
        double fERLBETRAG73;
        public double ERLBETRAG73
        {
            get { return fERLBETRAG73; }
            set { SetPropertyValue<double>("ERLBETRAG73", ref fERLBETRAG73, value); }
        }
        double fERLBETRAG74;
        public double ERLBETRAG74
        {
            get { return fERLBETRAG74; }
            set { SetPropertyValue<double>("ERLBETRAG74", ref fERLBETRAG74, value); }
        }
        double fERLBETRAG75;
        public double ERLBETRAG75
        {
            get { return fERLBETRAG75; }
            set { SetPropertyValue<double>("ERLBETRAG75", ref fERLBETRAG75, value); }
        }
        double fERLBETRAG76;
        public double ERLBETRAG76
        {
            get { return fERLBETRAG76; }
            set { SetPropertyValue<double>("ERLBETRAG76", ref fERLBETRAG76, value); }
        }
        double fERLBETRAG77;
        public double ERLBETRAG77
        {
            get { return fERLBETRAG77; }
            set { SetPropertyValue<double>("ERLBETRAG77", ref fERLBETRAG77, value); }
        }
        double fERLBETRAG78;
        public double ERLBETRAG78
        {
            get { return fERLBETRAG78; }
            set { SetPropertyValue<double>("ERLBETRAG78", ref fERLBETRAG78, value); }
        }
        double fERLBETRAG79;
        public double ERLBETRAG79
        {
            get { return fERLBETRAG79; }
            set { SetPropertyValue<double>("ERLBETRAG79", ref fERLBETRAG79, value); }
        }
        double fERLBETRAG80;
        public double ERLBETRAG80
        {
            get { return fERLBETRAG80; }
            set { SetPropertyValue<double>("ERLBETRAG80", ref fERLBETRAG80, value); }
        }
        double fERLBETRAG81;
        public double ERLBETRAG81
        {
            get { return fERLBETRAG81; }
            set { SetPropertyValue<double>("ERLBETRAG81", ref fERLBETRAG81, value); }
        }
        double fERLBETRAG82;
        public double ERLBETRAG82
        {
            get { return fERLBETRAG82; }
            set { SetPropertyValue<double>("ERLBETRAG82", ref fERLBETRAG82, value); }
        }
        double fERLBETRAG83;
        public double ERLBETRAG83
        {
            get { return fERLBETRAG83; }
            set { SetPropertyValue<double>("ERLBETRAG83", ref fERLBETRAG83, value); }
        }
        double fERLBETRAG84;
        public double ERLBETRAG84
        {
            get { return fERLBETRAG84; }
            set { SetPropertyValue<double>("ERLBETRAG84", ref fERLBETRAG84, value); }
        }
        double fERLBETRAG85;
        public double ERLBETRAG85
        {
            get { return fERLBETRAG85; }
            set { SetPropertyValue<double>("ERLBETRAG85", ref fERLBETRAG85, value); }
        }
        double fERLBETRAG86;
        public double ERLBETRAG86
        {
            get { return fERLBETRAG86; }
            set { SetPropertyValue<double>("ERLBETRAG86", ref fERLBETRAG86, value); }
        }
        double fERLBETRAG87;
        public double ERLBETRAG87
        {
            get { return fERLBETRAG87; }
            set { SetPropertyValue<double>("ERLBETRAG87", ref fERLBETRAG87, value); }
        }
        double fERLBETRAG88;
        public double ERLBETRAG88
        {
            get { return fERLBETRAG88; }
            set { SetPropertyValue<double>("ERLBETRAG88", ref fERLBETRAG88, value); }
        }
        double fERLBETRAG89;
        public double ERLBETRAG89
        {
            get { return fERLBETRAG89; }
            set { SetPropertyValue<double>("ERLBETRAG89", ref fERLBETRAG89, value); }
        }
        double fERLBETRAG90;
        public double ERLBETRAG90
        {
            get { return fERLBETRAG90; }
            set { SetPropertyValue<double>("ERLBETRAG90", ref fERLBETRAG90, value); }
        }
        double fERLBETRAG91;
        public double ERLBETRAG91
        {
            get { return fERLBETRAG91; }
            set { SetPropertyValue<double>("ERLBETRAG91", ref fERLBETRAG91, value); }
        }
        double fERLBETRAG92;
        public double ERLBETRAG92
        {
            get { return fERLBETRAG92; }
            set { SetPropertyValue<double>("ERLBETRAG92", ref fERLBETRAG92, value); }
        }
        double fERLBETRAG93;
        public double ERLBETRAG93
        {
            get { return fERLBETRAG93; }
            set { SetPropertyValue<double>("ERLBETRAG93", ref fERLBETRAG93, value); }
        }
        double fERLBETRAG94;
        public double ERLBETRAG94
        {
            get { return fERLBETRAG94; }
            set { SetPropertyValue<double>("ERLBETRAG94", ref fERLBETRAG94, value); }
        }
        double fERLBETRAG95;
        public double ERLBETRAG95
        {
            get { return fERLBETRAG95; }
            set { SetPropertyValue<double>("ERLBETRAG95", ref fERLBETRAG95, value); }
        }
        double fERLBETRAG96;
        public double ERLBETRAG96
        {
            get { return fERLBETRAG96; }
            set { SetPropertyValue<double>("ERLBETRAG96", ref fERLBETRAG96, value); }
        }
        double fERLBETRAG97;
        public double ERLBETRAG97
        {
            get { return fERLBETRAG97; }
            set { SetPropertyValue<double>("ERLBETRAG97", ref fERLBETRAG97, value); }
        }
        double fERLBETRAG98;
        public double ERLBETRAG98
        {
            get { return fERLBETRAG98; }
            set { SetPropertyValue<double>("ERLBETRAG98", ref fERLBETRAG98, value); }
        }
        double fERLBETRAG99;
        public double ERLBETRAG99
        {
            get { return fERLBETRAG99; }
            set { SetPropertyValue<double>("ERLBETRAG99", ref fERLBETRAG99, value); }
        }
        string fA1;
        [Size(1)]
        public string A1
        {
            get { return fA1; }
            set { SetPropertyValue<string>("A1", ref fA1, value); }
        }
        string fA2;
        [Size(1)]
        public string A2
        {
            get { return fA2; }
            set { SetPropertyValue<string>("A2", ref fA2, value); }
        }
        string fA3;
        [Size(1)]
        public string A3
        {
            get { return fA3; }
            set { SetPropertyValue<string>("A3", ref fA3, value); }
        }
        string fA4;
        [Size(1)]
        public string A4
        {
            get { return fA4; }
            set { SetPropertyValue<string>("A4", ref fA4, value); }
        }
        string fA5;
        [Size(1)]
        public string A5
        {
            get { return fA5; }
            set { SetPropertyValue<string>("A5", ref fA5, value); }
        }
        string fA6;
        [Size(1)]
        public string A6
        {
            get { return fA6; }
            set { SetPropertyValue<string>("A6", ref fA6, value); }
        }
        string fA7;
        [Size(1)]
        public string A7
        {
            get { return fA7; }
            set { SetPropertyValue<string>("A7", ref fA7, value); }
        }
        string fA8;
        [Size(1)]
        public string A8
        {
            get { return fA8; }
            set { SetPropertyValue<string>("A8", ref fA8, value); }
        }
        string fA9;
        [Size(1)]
        public string A9
        {
            get { return fA9; }
            set { SetPropertyValue<string>("A9", ref fA9, value); }
        }
        string fA10;
        [Size(1)]
        public string A10
        {
            get { return fA10; }
            set { SetPropertyValue<string>("A10", ref fA10, value); }
        }
        [Association(@"AngebotReferencesErlGrp")]
        public XPCollection<Angebot> Angebots { get { return GetCollection<Angebot>("Angebots"); } }
    }

}
