//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class ErlKonten : XPLiteObject
    {
        int fAbtNr;
        [Key]
        public int AbtNr
        {
            get { return fAbtNr; }
            set { SetPropertyValue<int>("AbtNr", ref fAbtNr, value); }
        }
        string fErlBereich1;
        [Size(50)]
        public string ErlBereich1
        {
            get { return fErlBereich1; }
            set { SetPropertyValue<string>("ErlBereich1", ref fErlBereich1, value); }
        }
        string fErlBereich2;
        [Size(50)]
        public string ErlBereich2
        {
            get { return fErlBereich2; }
            set { SetPropertyValue<string>("ErlBereich2", ref fErlBereich2, value); }
        }
        string fErlBereich3;
        [Size(50)]
        public string ErlBereich3
        {
            get { return fErlBereich3; }
            set { SetPropertyValue<string>("ErlBereich3", ref fErlBereich3, value); }
        }
        string fErlBereich4;
        [Size(50)]
        public string ErlBereich4
        {
            get { return fErlBereich4; }
            set { SetPropertyValue<string>("ErlBereich4", ref fErlBereich4, value); }
        }
        string fErlBereich5;
        [Size(50)]
        public string ErlBereich5
        {
            get { return fErlBereich5; }
            set { SetPropertyValue<string>("ErlBereich5", ref fErlBereich5, value); }
        }
        string fErlBereich6;
        [Size(50)]
        public string ErlBereich6
        {
            get { return fErlBereich6; }
            set { SetPropertyValue<string>("ErlBereich6", ref fErlBereich6, value); }
        }
        string fErlBereich7;
        [Size(50)]
        public string ErlBereich7
        {
            get { return fErlBereich7; }
            set { SetPropertyValue<string>("ErlBereich7", ref fErlBereich7, value); }
        }
        string fErlBereich8;
        [Size(50)]
        public string ErlBereich8
        {
            get { return fErlBereich8; }
            set { SetPropertyValue<string>("ErlBereich8", ref fErlBereich8, value); }
        }
        string fErlBereich9;
        [Size(50)]
        public string ErlBereich9
        {
            get { return fErlBereich9; }
            set { SetPropertyValue<string>("ErlBereich9", ref fErlBereich9, value); }
        }
        string fErlBereich10;
        [Size(50)]
        public string ErlBereich10
        {
            get { return fErlBereich10; }
            set { SetPropertyValue<string>("ErlBereich10", ref fErlBereich10, value); }
        }
        string fErlBereich11;
        [Size(50)]
        public string ErlBereich11
        {
            get { return fErlBereich11; }
            set { SetPropertyValue<string>("ErlBereich11", ref fErlBereich11, value); }
        }
        string fErlBereich12;
        [Size(50)]
        public string ErlBereich12
        {
            get { return fErlBereich12; }
            set { SetPropertyValue<string>("ErlBereich12", ref fErlBereich12, value); }
        }
        string fErlBereich13;
        [Size(50)]
        public string ErlBereich13
        {
            get { return fErlBereich13; }
            set { SetPropertyValue<string>("ErlBereich13", ref fErlBereich13, value); }
        }
        string fErlBereich14;
        [Size(50)]
        public string ErlBereich14
        {
            get { return fErlBereich14; }
            set { SetPropertyValue<string>("ErlBereich14", ref fErlBereich14, value); }
        }
        string fErlBereich15;
        [Size(50)]
        public string ErlBereich15
        {
            get { return fErlBereich15; }
            set { SetPropertyValue<string>("ErlBereich15", ref fErlBereich15, value); }
        }
        string fErlBereich16;
        [Size(50)]
        public string ErlBereich16
        {
            get { return fErlBereich16; }
            set { SetPropertyValue<string>("ErlBereich16", ref fErlBereich16, value); }
        }
        string fErlBereich17;
        [Size(50)]
        public string ErlBereich17
        {
            get { return fErlBereich17; }
            set { SetPropertyValue<string>("ErlBereich17", ref fErlBereich17, value); }
        }
        string fErlBereich18;
        [Size(50)]
        public string ErlBereich18
        {
            get { return fErlBereich18; }
            set { SetPropertyValue<string>("ErlBereich18", ref fErlBereich18, value); }
        }
        string fErlBereich19;
        [Size(50)]
        public string ErlBereich19
        {
            get { return fErlBereich19; }
            set { SetPropertyValue<string>("ErlBereich19", ref fErlBereich19, value); }
        }
        string fErlBereich20;
        [Size(50)]
        public string ErlBereich20
        {
            get { return fErlBereich20; }
            set { SetPropertyValue<string>("ErlBereich20", ref fErlBereich20, value); }
        }
        string fErlBereich21;
        [Size(50)]
        public string ErlBereich21
        {
            get { return fErlBereich21; }
            set { SetPropertyValue<string>("ErlBereich21", ref fErlBereich21, value); }
        }
        string fErlBereich22;
        [Size(50)]
        public string ErlBereich22
        {
            get { return fErlBereich22; }
            set { SetPropertyValue<string>("ErlBereich22", ref fErlBereich22, value); }
        }
        string fErlBereich23;
        [Size(50)]
        public string ErlBereich23
        {
            get { return fErlBereich23; }
            set { SetPropertyValue<string>("ErlBereich23", ref fErlBereich23, value); }
        }
        string fErlBereich24;
        [Size(50)]
        public string ErlBereich24
        {
            get { return fErlBereich24; }
            set { SetPropertyValue<string>("ErlBereich24", ref fErlBereich24, value); }
        }
        string fErlBereich25;
        [Size(50)]
        public string ErlBereich25
        {
            get { return fErlBereich25; }
            set { SetPropertyValue<string>("ErlBereich25", ref fErlBereich25, value); }
        }
        string fErlBereich26;
        [Size(50)]
        public string ErlBereich26
        {
            get { return fErlBereich26; }
            set { SetPropertyValue<string>("ErlBereich26", ref fErlBereich26, value); }
        }
        string fErlBereich27;
        [Size(50)]
        public string ErlBereich27
        {
            get { return fErlBereich27; }
            set { SetPropertyValue<string>("ErlBereich27", ref fErlBereich27, value); }
        }
        string fErlBereich28;
        [Size(50)]
        public string ErlBereich28
        {
            get { return fErlBereich28; }
            set { SetPropertyValue<string>("ErlBereich28", ref fErlBereich28, value); }
        }
        string fErlBereich29;
        [Size(50)]
        public string ErlBereich29
        {
            get { return fErlBereich29; }
            set { SetPropertyValue<string>("ErlBereich29", ref fErlBereich29, value); }
        }
        string fErlBereich30;
        [Size(50)]
        public string ErlBereich30
        {
            get { return fErlBereich30; }
            set { SetPropertyValue<string>("ErlBereich30", ref fErlBereich30, value); }
        }
        string fErlBereich31;
        [Size(50)]
        public string ErlBereich31
        {
            get { return fErlBereich31; }
            set { SetPropertyValue<string>("ErlBereich31", ref fErlBereich31, value); }
        }
        string fErlBereich32;
        [Size(50)]
        public string ErlBereich32
        {
            get { return fErlBereich32; }
            set { SetPropertyValue<string>("ErlBereich32", ref fErlBereich32, value); }
        }
        string fErlBereich33;
        [Size(50)]
        public string ErlBereich33
        {
            get { return fErlBereich33; }
            set { SetPropertyValue<string>("ErlBereich33", ref fErlBereich33, value); }
        }
        string fErlBereich34;
        [Size(50)]
        public string ErlBereich34
        {
            get { return fErlBereich34; }
            set { SetPropertyValue<string>("ErlBereich34", ref fErlBereich34, value); }
        }
        string fErlBereich35;
        [Size(50)]
        public string ErlBereich35
        {
            get { return fErlBereich35; }
            set { SetPropertyValue<string>("ErlBereich35", ref fErlBereich35, value); }
        }
        string fErlBereich36;
        [Size(50)]
        public string ErlBereich36
        {
            get { return fErlBereich36; }
            set { SetPropertyValue<string>("ErlBereich36", ref fErlBereich36, value); }
        }
        string fErlBereich37;
        [Size(50)]
        public string ErlBereich37
        {
            get { return fErlBereich37; }
            set { SetPropertyValue<string>("ErlBereich37", ref fErlBereich37, value); }
        }
        string fErlBereich38;
        [Size(50)]
        public string ErlBereich38
        {
            get { return fErlBereich38; }
            set { SetPropertyValue<string>("ErlBereich38", ref fErlBereich38, value); }
        }
        string fErlBereich39;
        [Size(50)]
        public string ErlBereich39
        {
            get { return fErlBereich39; }
            set { SetPropertyValue<string>("ErlBereich39", ref fErlBereich39, value); }
        }
        string fErlBereich40;
        [Size(50)]
        public string ErlBereich40
        {
            get { return fErlBereich40; }
            set { SetPropertyValue<string>("ErlBereich40", ref fErlBereich40, value); }
        }
        string fErlBereich41;
        [Size(50)]
        public string ErlBereich41
        {
            get { return fErlBereich41; }
            set { SetPropertyValue<string>("ErlBereich41", ref fErlBereich41, value); }
        }
        string fErlBereich42;
        [Size(50)]
        public string ErlBereich42
        {
            get { return fErlBereich42; }
            set { SetPropertyValue<string>("ErlBereich42", ref fErlBereich42, value); }
        }
        string fErlBereich43;
        [Size(50)]
        public string ErlBereich43
        {
            get { return fErlBereich43; }
            set { SetPropertyValue<string>("ErlBereich43", ref fErlBereich43, value); }
        }
        string fErlBereich44;
        [Size(50)]
        public string ErlBereich44
        {
            get { return fErlBereich44; }
            set { SetPropertyValue<string>("ErlBereich44", ref fErlBereich44, value); }
        }
        string fErlBereich45;
        [Size(50)]
        public string ErlBereich45
        {
            get { return fErlBereich45; }
            set { SetPropertyValue<string>("ErlBereich45", ref fErlBereich45, value); }
        }
        string fErlBereich46;
        [Size(50)]
        public string ErlBereich46
        {
            get { return fErlBereich46; }
            set { SetPropertyValue<string>("ErlBereich46", ref fErlBereich46, value); }
        }
        string fErlBereich47;
        [Size(50)]
        public string ErlBereich47
        {
            get { return fErlBereich47; }
            set { SetPropertyValue<string>("ErlBereich47", ref fErlBereich47, value); }
        }
        string fErlBereich48;
        [Size(50)]
        public string ErlBereich48
        {
            get { return fErlBereich48; }
            set { SetPropertyValue<string>("ErlBereich48", ref fErlBereich48, value); }
        }
        string fErlBereich49;
        [Size(50)]
        public string ErlBereich49
        {
            get { return fErlBereich49; }
            set { SetPropertyValue<string>("ErlBereich49", ref fErlBereich49, value); }
        }
        string fErlBereich50;
        [Size(50)]
        public string ErlBereich50
        {
            get { return fErlBereich50; }
            set { SetPropertyValue<string>("ErlBereich50", ref fErlBereich50, value); }
        }
        string fErlBereich51;
        [Size(50)]
        public string ErlBereich51
        {
            get { return fErlBereich51; }
            set { SetPropertyValue<string>("ErlBereich51", ref fErlBereich51, value); }
        }
        string fErlBereich52;
        [Size(50)]
        public string ErlBereich52
        {
            get { return fErlBereich52; }
            set { SetPropertyValue<string>("ErlBereich52", ref fErlBereich52, value); }
        }
        string fErlBereich53;
        [Size(50)]
        public string ErlBereich53
        {
            get { return fErlBereich53; }
            set { SetPropertyValue<string>("ErlBereich53", ref fErlBereich53, value); }
        }
        string fErlBereich54;
        [Size(50)]
        public string ErlBereich54
        {
            get { return fErlBereich54; }
            set { SetPropertyValue<string>("ErlBereich54", ref fErlBereich54, value); }
        }
        string fErlBereich55;
        [Size(50)]
        public string ErlBereich55
        {
            get { return fErlBereich55; }
            set { SetPropertyValue<string>("ErlBereich55", ref fErlBereich55, value); }
        }
        string fErlBereich56;
        [Size(50)]
        public string ErlBereich56
        {
            get { return fErlBereich56; }
            set { SetPropertyValue<string>("ErlBereich56", ref fErlBereich56, value); }
        }
        string fErlBereich57;
        [Size(50)]
        public string ErlBereich57
        {
            get { return fErlBereich57; }
            set { SetPropertyValue<string>("ErlBereich57", ref fErlBereich57, value); }
        }
        string fErlBereich58;
        [Size(50)]
        public string ErlBereich58
        {
            get { return fErlBereich58; }
            set { SetPropertyValue<string>("ErlBereich58", ref fErlBereich58, value); }
        }
        string fErlBereich59;
        [Size(50)]
        public string ErlBereich59
        {
            get { return fErlBereich59; }
            set { SetPropertyValue<string>("ErlBereich59", ref fErlBereich59, value); }
        }
        string fErlBereich60;
        [Size(50)]
        public string ErlBereich60
        {
            get { return fErlBereich60; }
            set { SetPropertyValue<string>("ErlBereich60", ref fErlBereich60, value); }
        }
        string fErlBereich61;
        [Size(50)]
        public string ErlBereich61
        {
            get { return fErlBereich61; }
            set { SetPropertyValue<string>("ErlBereich61", ref fErlBereich61, value); }
        }
        string fErlBereich62;
        [Size(50)]
        public string ErlBereich62
        {
            get { return fErlBereich62; }
            set { SetPropertyValue<string>("ErlBereich62", ref fErlBereich62, value); }
        }
        string fErlBereich63;
        [Size(50)]
        public string ErlBereich63
        {
            get { return fErlBereich63; }
            set { SetPropertyValue<string>("ErlBereich63", ref fErlBereich63, value); }
        }
        string fErlBereich64;
        [Size(50)]
        public string ErlBereich64
        {
            get { return fErlBereich64; }
            set { SetPropertyValue<string>("ErlBereich64", ref fErlBereich64, value); }
        }
        string fErlBereich65;
        [Size(50)]
        public string ErlBereich65
        {
            get { return fErlBereich65; }
            set { SetPropertyValue<string>("ErlBereich65", ref fErlBereich65, value); }
        }
        string fErlBereich66;
        [Size(50)]
        public string ErlBereich66
        {
            get { return fErlBereich66; }
            set { SetPropertyValue<string>("ErlBereich66", ref fErlBereich66, value); }
        }
        string fErlBereich67;
        [Size(50)]
        public string ErlBereich67
        {
            get { return fErlBereich67; }
            set { SetPropertyValue<string>("ErlBereich67", ref fErlBereich67, value); }
        }
        string fErlBereich68;
        [Size(50)]
        public string ErlBereich68
        {
            get { return fErlBereich68; }
            set { SetPropertyValue<string>("ErlBereich68", ref fErlBereich68, value); }
        }
        string fErlBereich69;
        [Size(50)]
        public string ErlBereich69
        {
            get { return fErlBereich69; }
            set { SetPropertyValue<string>("ErlBereich69", ref fErlBereich69, value); }
        }
        string fErlBereich70;
        [Size(50)]
        public string ErlBereich70
        {
            get { return fErlBereich70; }
            set { SetPropertyValue<string>("ErlBereich70", ref fErlBereich70, value); }
        }
        string fErlBereich71;
        [Size(50)]
        public string ErlBereich71
        {
            get { return fErlBereich71; }
            set { SetPropertyValue<string>("ErlBereich71", ref fErlBereich71, value); }
        }
        string fErlBereich72;
        [Size(50)]
        public string ErlBereich72
        {
            get { return fErlBereich72; }
            set { SetPropertyValue<string>("ErlBereich72", ref fErlBereich72, value); }
        }
        string fErlBereich73;
        [Size(50)]
        public string ErlBereich73
        {
            get { return fErlBereich73; }
            set { SetPropertyValue<string>("ErlBereich73", ref fErlBereich73, value); }
        }
        string fErlBereich74;
        [Size(50)]
        public string ErlBereich74
        {
            get { return fErlBereich74; }
            set { SetPropertyValue<string>("ErlBereich74", ref fErlBereich74, value); }
        }
        string fErlBereich75;
        [Size(50)]
        public string ErlBereich75
        {
            get { return fErlBereich75; }
            set { SetPropertyValue<string>("ErlBereich75", ref fErlBereich75, value); }
        }
        string fErlBereich76;
        [Size(50)]
        public string ErlBereich76
        {
            get { return fErlBereich76; }
            set { SetPropertyValue<string>("ErlBereich76", ref fErlBereich76, value); }
        }
        string fErlBereich77;
        [Size(50)]
        public string ErlBereich77
        {
            get { return fErlBereich77; }
            set { SetPropertyValue<string>("ErlBereich77", ref fErlBereich77, value); }
        }
        string fErlBereich78;
        [Size(50)]
        public string ErlBereich78
        {
            get { return fErlBereich78; }
            set { SetPropertyValue<string>("ErlBereich78", ref fErlBereich78, value); }
        }
        string fErlBereich79;
        [Size(50)]
        public string ErlBereich79
        {
            get { return fErlBereich79; }
            set { SetPropertyValue<string>("ErlBereich79", ref fErlBereich79, value); }
        }
        string fErlBereich80;
        [Size(50)]
        public string ErlBereich80
        {
            get { return fErlBereich80; }
            set { SetPropertyValue<string>("ErlBereich80", ref fErlBereich80, value); }
        }
        string fErlBereich81;
        [Size(50)]
        public string ErlBereich81
        {
            get { return fErlBereich81; }
            set { SetPropertyValue<string>("ErlBereich81", ref fErlBereich81, value); }
        }
        string fErlBereich82;
        [Size(50)]
        public string ErlBereich82
        {
            get { return fErlBereich82; }
            set { SetPropertyValue<string>("ErlBereich82", ref fErlBereich82, value); }
        }
        string fErlBereich83;
        [Size(50)]
        public string ErlBereich83
        {
            get { return fErlBereich83; }
            set { SetPropertyValue<string>("ErlBereich83", ref fErlBereich83, value); }
        }
        string fErlBereich84;
        [Size(50)]
        public string ErlBereich84
        {
            get { return fErlBereich84; }
            set { SetPropertyValue<string>("ErlBereich84", ref fErlBereich84, value); }
        }
        string fErlBereich85;
        [Size(50)]
        public string ErlBereich85
        {
            get { return fErlBereich85; }
            set { SetPropertyValue<string>("ErlBereich85", ref fErlBereich85, value); }
        }
        string fErlBereich86;
        [Size(50)]
        public string ErlBereich86
        {
            get { return fErlBereich86; }
            set { SetPropertyValue<string>("ErlBereich86", ref fErlBereich86, value); }
        }
        string fErlBereich87;
        [Size(50)]
        public string ErlBereich87
        {
            get { return fErlBereich87; }
            set { SetPropertyValue<string>("ErlBereich87", ref fErlBereich87, value); }
        }
        string fErlBereich88;
        [Size(50)]
        public string ErlBereich88
        {
            get { return fErlBereich88; }
            set { SetPropertyValue<string>("ErlBereich88", ref fErlBereich88, value); }
        }
        string fErlBereich89;
        [Size(50)]
        public string ErlBereich89
        {
            get { return fErlBereich89; }
            set { SetPropertyValue<string>("ErlBereich89", ref fErlBereich89, value); }
        }
        string fErlBereich90;
        [Size(50)]
        public string ErlBereich90
        {
            get { return fErlBereich90; }
            set { SetPropertyValue<string>("ErlBereich90", ref fErlBereich90, value); }
        }
        string fErlBereich91;
        [Size(50)]
        public string ErlBereich91
        {
            get { return fErlBereich91; }
            set { SetPropertyValue<string>("ErlBereich91", ref fErlBereich91, value); }
        }
        string fErlBereich92;
        [Size(50)]
        public string ErlBereich92
        {
            get { return fErlBereich92; }
            set { SetPropertyValue<string>("ErlBereich92", ref fErlBereich92, value); }
        }
        string fErlBereich93;
        [Size(50)]
        public string ErlBereich93
        {
            get { return fErlBereich93; }
            set { SetPropertyValue<string>("ErlBereich93", ref fErlBereich93, value); }
        }
        string fErlBereich94;
        [Size(50)]
        public string ErlBereich94
        {
            get { return fErlBereich94; }
            set { SetPropertyValue<string>("ErlBereich94", ref fErlBereich94, value); }
        }
        string fErlBereich95;
        [Size(50)]
        public string ErlBereich95
        {
            get { return fErlBereich95; }
            set { SetPropertyValue<string>("ErlBereich95", ref fErlBereich95, value); }
        }
        string fErlBereich96;
        [Size(50)]
        public string ErlBereich96
        {
            get { return fErlBereich96; }
            set { SetPropertyValue<string>("ErlBereich96", ref fErlBereich96, value); }
        }
        string fErlBereich97;
        [Size(50)]
        public string ErlBereich97
        {
            get { return fErlBereich97; }
            set { SetPropertyValue<string>("ErlBereich97", ref fErlBereich97, value); }
        }
        string fErlBereich98;
        [Size(50)]
        public string ErlBereich98
        {
            get { return fErlBereich98; }
            set { SetPropertyValue<string>("ErlBereich98", ref fErlBereich98, value); }
        }
        string fErlBereich99;
        [Size(50)]
        public string ErlBereich99
        {
            get { return fErlBereich99; }
            set { SetPropertyValue<string>("ErlBereich99", ref fErlBereich99, value); }
        }
    }

}
