//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class LagerArtikelQuantifikation : XPLiteObject
    {
        string fLagerIDQuant;
        [Key]
        [Size(116)]
        public string LagerIDQuant
        {
            get { return fLagerIDQuant; }
            set { SetPropertyValue<string>("LagerIDQuant", ref fLagerIDQuant, value); }
        }
        string fStrukturID;
        [Indexed(Name = @"IX_StrukturID")]
        [Size(90)]
        public string StrukturID
        {
            get { return fStrukturID; }
            set { SetPropertyValue<string>("StrukturID", ref fStrukturID, value); }
        }
        string fLagerNr;
        [Indexed(Name = @"IX_LagerNr")]
        [Size(25)]
        public string LagerNr
        {
            get { return fLagerNr; }
            set { SetPropertyValue<string>("LagerNr", ref fLagerNr, value); }
        }
        int fTE;
        public int TE
        {
            get { return fTE; }
            set { SetPropertyValue<int>("TE", ref fTE, value); }
        }
        float fLagerBestand;
        public float LagerBestand
        {
            get { return fLagerBestand; }
            set { SetPropertyValue<float>("LagerBestand", ref fLagerBestand, value); }
        }
        float fInventurBestand;
        public float InventurBestand
        {
            get { return fInventurBestand; }
            set { SetPropertyValue<float>("InventurBestand", ref fInventurBestand, value); }
        }
        decimal fBewertPreis;
        public decimal BewertPreis
        {
            get { return fBewertPreis; }
            set { SetPropertyValue<decimal>("BewertPreis", ref fBewertPreis, value); }
        }
        DateTime fDateLastIn;
        public DateTime DateLastIn
        {
            get { return fDateLastIn; }
            set { SetPropertyValue<DateTime>("DateLastIn", ref fDateLastIn, value); }
        }
        DateTime fDateLastOut;
        public DateTime DateLastOut
        {
            get { return fDateLastOut; }
            set { SetPropertyValue<DateTime>("DateLastOut", ref fDateLastOut, value); }
        }
        DateTime fInventurDatum;
        public DateTime InventurDatum
        {
            get { return fInventurDatum; }
            set { SetPropertyValue<DateTime>("InventurDatum", ref fInventurDatum, value); }
        }
        float fInventurBestandStichtag;
        public float InventurBestandStichtag
        {
            get { return fInventurBestandStichtag; }
            set { SetPropertyValue<float>("InventurBestandStichtag", ref fInventurBestandStichtag, value); }
        }
        double fBuchWert;
        public double BuchWert
        {
            get { return fBuchWert; }
            set { SetPropertyValue<double>("BuchWert", ref fBuchWert, value); }
        }
        string fInfo1;
        [Size(20)]
        public string Info1
        {
            get { return fInfo1; }
            set { SetPropertyValue<string>("Info1", ref fInfo1, value); }
        }
        string fInfo2;
        [Size(20)]
        public string Info2
        {
            get { return fInfo2; }
            set { SetPropertyValue<string>("Info2", ref fInfo2, value); }
        }
        string fInfo3;
        [Size(20)]
        public string Info3
        {
            get { return fInfo3; }
            set { SetPropertyValue<string>("Info3", ref fInfo3, value); }
        }
    }

}
