//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class LohnArten : XPLiteObject
    {
        int fLohnArt;
        [Key]
        public int LohnArt
        {
            get { return fLohnArt; }
            set { SetPropertyValue<int>("LohnArt", ref fLohnArt, value); }
        }
        string fBeschriftung;
        [Size(50)]
        public string Beschriftung
        {
            get { return fBeschriftung; }
            set { SetPropertyValue<string>("Beschriftung", ref fBeschriftung, value); }
        }
        short fVerarbMerker;
        public short VerarbMerker
        {
            get { return fVerarbMerker; }
            set { SetPropertyValue<short>("VerarbMerker", ref fVerarbMerker, value); }
        }
        string fVerarbBez;
        [Size(30)]
        public string VerarbBez
        {
            get { return fVerarbBez; }
            set { SetPropertyValue<string>("VerarbBez", ref fVerarbBez, value); }
        }
        double fBewertungsFaktor;
        public double BewertungsFaktor
        {
            get { return fBewertungsFaktor; }
            set { SetPropertyValue<double>("BewertungsFaktor", ref fBewertungsFaktor, value); }
        }
        decimal fFixBetrag;
        public decimal FixBetrag
        {
            get { return fFixBetrag; }
            set { SetPropertyValue<decimal>("FixBetrag", ref fFixBetrag, value); }
        }
        bool fKonv2Euro;
        public bool Konv2Euro
        {
            get { return fKonv2Euro; }
            set { SetPropertyValue<bool>("Konv2Euro", ref fKonv2Euro, value); }
        }
        string fUserErfasst;
        [Size(8)]
        public string UserErfasst
        {
            get { return fUserErfasst; }
            set { SetPropertyValue<string>("UserErfasst", ref fUserErfasst, value); }
        }
        DateTime fDatumErfasst;
        public DateTime DatumErfasst
        {
            get { return fDatumErfasst; }
            set { SetPropertyValue<DateTime>("DatumErfasst", ref fDatumErfasst, value); }
        }
        string fUserAenderung;
        [Size(8)]
        public string UserAenderung
        {
            get { return fUserAenderung; }
            set { SetPropertyValue<string>("UserAenderung", ref fUserAenderung, value); }
        }
        DateTime fDatumAenderung;
        public DateTime DatumAenderung
        {
            get { return fDatumAenderung; }
            set { SetPropertyValue<DateTime>("DatumAenderung", ref fDatumAenderung, value); }
        }
        bool fUnproduktiv;
        public bool Unproduktiv
        {
            get { return fUnproduktiv; }
            set { SetPropertyValue<bool>("Unproduktiv", ref fUnproduktiv, value); }
        }
        bool fInaktiv;
        public bool Inaktiv
        {
            get { return fInaktiv; }
            set { SetPropertyValue<bool>("Inaktiv", ref fInaktiv, value); }
        }
    }

}
