//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MenueProgramme : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        MenueGruppen ffkMenueGruppen;
        [Association(@"MenueProgrammeReferencesMenueGruppen")]
        public MenueGruppen fkMenueGruppen
        {
            get { return ffkMenueGruppen; }
            set { SetPropertyValue<MenueGruppen>("fkMenueGruppen", ref ffkMenueGruppen, value); }
        }
        string fBezeichnung;
        [Size(50)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fLokalisierterText;
        [Size(50)]
        public string LokalisierterText
        {
            get { return fLokalisierterText; }
            set { SetPropertyValue<string>("LokalisierterText", ref fLokalisierterText, value); }
        }
        int fRibbonIndex;
        [Indexed(Name = @"IX_RibbonIndex")]
        public int RibbonIndex
        {
            get { return fRibbonIndex; }
            set { SetPropertyValue<int>("RibbonIndex", ref fRibbonIndex, value); }
        }
        string fRibbonKeytip;
        [Size(2)]
        public string RibbonKeytip
        {
            get { return fRibbonKeytip; }
            set { SetPropertyValue<string>("RibbonKeytip", ref fRibbonKeytip, value); }
        }
        int fImageIndex;
        public int ImageIndex
        {
            get { return fImageIndex; }
            set { SetPropertyValue<int>("ImageIndex", ref fImageIndex, value); }
        }
        string fMenü;
        [Size(255)]
        public string Menü
        {
            get { return fMenü; }
            set { SetPropertyValue<string>("Menü", ref fMenü, value); }
        }
        int fDarstellung;
        public int Darstellung
        {
            get { return fDarstellung; }
            set { SetPropertyValue<int>("Darstellung", ref fDarstellung, value); }
        }
        int ffkMenueProgrammeEXT;
        public int fkMenueProgrammeEXT
        {
            get { return ffkMenueProgrammeEXT; }
            set { SetPropertyValue<int>("fkMenueProgrammeEXT", ref ffkMenueProgrammeEXT, value); }
        }
        bool fMDI;
        public bool MDI
        {
            get { return fMDI; }
            set { SetPropertyValue<bool>("MDI", ref fMDI, value); }
        }
    }

}
