//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MenueProgrammeEXT : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fBezeichnung;
        [Size(50)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        int fRibbonIndex;
        [Indexed(Name = @"IX_RibbonIndex")]
        public int RibbonIndex
        {
            get { return fRibbonIndex; }
            set { SetPropertyValue<int>("RibbonIndex", ref fRibbonIndex, value); }
        }
        string fRibbonKeytip;
        [Size(2)]
        public string RibbonKeytip
        {
            get { return fRibbonKeytip; }
            set { SetPropertyValue<string>("RibbonKeytip", ref fRibbonKeytip, value); }
        }
        short fArt;
        [Indexed(Name = @"IX_Art")]
        public short Art
        {
            get { return fArt; }
            set { SetPropertyValue<short>("Art", ref fArt, value); }
        }
        string fPfadLink;
        [Size(255)]
        public string PfadLink
        {
            get { return fPfadLink; }
            set { SetPropertyValue<string>("PfadLink", ref fPfadLink, value); }
        }
        int fDarstellung;
        public int Darstellung
        {
            get { return fDarstellung; }
            set { SetPropertyValue<int>("Darstellung", ref fDarstellung, value); }
        }
        bool fMDI;
        public bool MDI
        {
            get { return fMDI; }
            set { SetPropertyValue<bool>("MDI", ref fMDI, value); }
        }
    }

}
