//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontJournPosLager : XPLiteObject
    {
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
        string ffk_PosKey;
        [Indexed(Name = @"IX_fk_PosKey")]
        public string fk_PosKey
        {
            get { return ffk_PosKey; }
            set { SetPropertyValue<string>("fk_PosKey", ref ffk_PosKey, value); }
        }
        string fPosProj;
        [Indexed(Name = @"IX_PosProj")]
        [Size(60)]
        public string PosProj
        {
            get { return fPosProj; }
            set { SetPropertyValue<string>("PosProj", ref fPosProj, value); }
        }
        int fBuchungsArt;
        public int BuchungsArt
        {
            get { return fBuchungsArt; }
            set { SetPropertyValue<int>("BuchungsArt", ref fBuchungsArt, value); }
        }
        double fBuchungsMenge;
        public double BuchungsMenge
        {
            get { return fBuchungsMenge; }
            set { SetPropertyValue<double>("BuchungsMenge", ref fBuchungsMenge, value); }
        }
        string fBstLagerProjektBeleg;
        [Size(35)]
        public string BstLagerProjektBeleg
        {
            get { return fBstLagerProjektBeleg; }
            set { SetPropertyValue<string>("BstLagerProjektBeleg", ref fBstLagerProjektBeleg, value); }
        }
        long fBstLagerBuchungID;
        public long BstLagerBuchungID
        {
            get { return fBstLagerBuchungID; }
            set { SetPropertyValue<long>("BstLagerBuchungID", ref fBstLagerBuchungID, value); }
        }
        int fBstLagerBuchungUebertragen;
        public int BstLagerBuchungUebertragen
        {
            get { return fBstLagerBuchungUebertragen; }
            set { SetPropertyValue<int>("BstLagerBuchungUebertragen", ref fBstLagerBuchungUebertragen, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
    }

}
