//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontStrgRelations : XPLiteObject
    {
        int fRelationID;
        [Key]
        public int RelationID
        {
            get { return fRelationID; }
            set { SetPropertyValue<int>("RelationID", ref fRelationID, value); }
        }
        int fPredecessor;
        [Indexed(Name = @"Predecessor")]
        public int Predecessor
        {
            get { return fPredecessor; }
            set { SetPropertyValue<int>("Predecessor", ref fPredecessor, value); }
        }
        int fSuccessor;
        [Indexed(Name = @"Successor")]
        public int Successor
        {
            get { return fSuccessor; }
            set { SetPropertyValue<int>("Successor", ref fSuccessor, value); }
        }
    }

}
