//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontStrgPers : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        int ffkTerminID;
        [Indexed(Name = @"IX_fkTerminID")]
        public int fkTerminID
        {
            get { return ffkTerminID; }
            set { SetPropertyValue<int>("fkTerminID", ref ffkTerminID, value); }
        }
        string fPersNr;
        [Size(30)]
        public string PersNr
        {
            get { return fPersNr; }
            set { SetPropertyValue<string>("PersNr", ref fPersNr, value); }
        }
        int fPersArt;
        public int PersArt
        {
            get { return fPersArt; }
            set { SetPropertyValue<int>("PersArt", ref fPersArt, value); }
        }
        DateTime fSyncDate;
        public DateTime SyncDate
        {
            get { return fSyncDate; }
            set { SetPropertyValue<DateTime>("SyncDate", ref fSyncDate, value); }
        }
    }

}
