//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontJournMonteureStundenID : XPLiteObject
    {
        int fMontJournMonteureStundenID1;
        [Key(true)]
        [Persistent(@"MontJournMonteureStundenID")]
        public int MontJournMonteureStundenID1
        {
            get { return fMontJournMonteureStundenID1; }
            set { SetPropertyValue<int>("MontJournMonteureStundenID1", ref fMontJournMonteureStundenID1, value); }
        }
        MontJourn ffkMontjournID;
        [Association(@"MontJournMonteureStundenIDReferencesMontJourn")]
        public MontJourn fkMontjournID
        {
            get { return ffkMontjournID; }
            set { SetPropertyValue<MontJourn>("fkMontjournID", ref ffkMontjournID, value); }
        }
        int fPersNr;
        public int PersNr
        {
            get { return fPersNr; }
            set { SetPropertyValue<int>("PersNr", ref fPersNr, value); }
        }
        string fPersName;
        [Size(20)]
        public string PersName
        {
            get { return fPersName; }
            set { SetPropertyValue<string>("PersName", ref fPersName, value); }
        }
        DateTime fDatum;
        public DateTime Datum
        {
            get { return fDatum; }
            set { SetPropertyValue<DateTime>("Datum", ref fDatum, value); }
        }
        double fStunden;
        public double Stunden
        {
            get { return fStunden; }
            set { SetPropertyValue<double>("Stunden", ref fStunden, value); }
        }
        string fVon;
        [Size(25)]
        public string Von
        {
            get { return fVon; }
            set { SetPropertyValue<string>("Von", ref fVon, value); }
        }
        string fBis;
        [Size(25)]
        public string Bis
        {
            get { return fBis; }
            set { SetPropertyValue<string>("Bis", ref fBis, value); }
        }
        short fLohnart;
        public short Lohnart
        {
            get { return fLohnart; }
            set { SetPropertyValue<short>("Lohnart", ref fLohnart, value); }
        }
        bool fUebergeben;
        [Indexed(Name = @"IX_Uebergeben")]
        public bool Uebergeben
        {
            get { return fUebergeben; }
            set { SetPropertyValue<bool>("Uebergeben", ref fUebergeben, value); }
        }
        string fKTR;
        [Size(10)]
        public string KTR
        {
            get { return fKTR; }
            set { SetPropertyValue<string>("KTR", ref fKTR, value); }
        }
        string fKST;
        [Size(20)]
        public string KST
        {
            get { return fKST; }
            set { SetPropertyValue<string>("KST", ref fKST, value); }
        }
        int fKoArt;
        public int KoArt
        {
            get { return fKoArt; }
            set { SetPropertyValue<int>("KoArt", ref fKoArt, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        string fCreateuser;
        [Size(8)]
        public string Createuser
        {
            get { return fCreateuser; }
            set { SetPropertyValue<string>("Createuser", ref fCreateuser, value); }
        }
        DateTime fCreatedate;
        public DateTime Createdate
        {
            get { return fCreatedate; }
            set { SetPropertyValue<DateTime>("Createdate", ref fCreatedate, value); }
        }
        string fEdituser;
        [Size(8)]
        public string Edituser
        {
            get { return fEdituser; }
            set { SetPropertyValue<string>("Edituser", ref fEdituser, value); }
        }
        DateTime fEditdate;
        public DateTime Editdate
        {
            get { return fEditdate; }
            set { SetPropertyValue<DateTime>("Editdate", ref fEditdate, value); }
        }
        string fLohnMerker;
        [Size(1)]
        public string LohnMerker
        {
            get { return fLohnMerker; }
            set { SetPropertyValue<string>("LohnMerker", ref fLohnMerker, value); }
        }
        decimal fFixBetrag;
        public decimal FixBetrag
        {
            get { return fFixBetrag; }
            set { SetPropertyValue<decimal>("FixBetrag", ref fFixBetrag, value); }
        }
        decimal fLohn;
        public decimal Lohn
        {
            get { return fLohn; }
            set { SetPropertyValue<decimal>("Lohn", ref fLohn, value); }
        }
        decimal fBewertLohn;
        public decimal BewertLohn
        {
            get { return fBewertLohn; }
            set { SetPropertyValue<decimal>("BewertLohn", ref fBewertLohn, value); }
        }
        decimal fErmBetrag;
        public decimal ErmBetrag
        {
            get { return fErmBetrag; }
            set { SetPropertyValue<decimal>("ErmBetrag", ref fErmBetrag, value); }
        }
        string fPosKey;
        [Size(65)]
        public string PosKey
        {
            get { return fPosKey; }
            set { SetPropertyValue<string>("PosKey", ref fPosKey, value); }
        }
        double fKM;
        public double KM
        {
            get { return fKM; }
            set { SetPropertyValue<double>("KM", ref fKM, value); }
        }
        double fEntfWO;
        public double EntfWO
        {
            get { return fEntfWO; }
            set { SetPropertyValue<double>("EntfWO", ref fEntfWO, value); }
        }
        int fAbwWO;
        public int AbwWO
        {
            get { return fAbwWO; }
            set { SetPropertyValue<int>("AbwWO", ref fAbwWO, value); }
        }
    }

}
