//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MonteurGruppePersonal : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        int ffkMonteurGruppe;
        [Indexed(Name = @"IX_MonteurGruppePersonalfkMonteurGruppe")]
        public int fkMonteurGruppe
        {
            get { return ffkMonteurGruppe; }
            set { SetPropertyValue<int>("fkMonteurGruppe", ref ffkMonteurGruppe, value); }
        }
        int fPersonalNr;
        [Indexed(Name = @"IX_MonteurGruppePersonalPersonalNr")]
        public int PersonalNr
        {
            get { return fPersonalNr; }
            set { SetPropertyValue<int>("PersonalNr", ref fPersonalNr, value); }
        }
    }

}
