//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontJournMobLog : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        MontJourn ffkMontjournID;
        [Association(@"MontJournMobLogReferencesMontJourn")]
        public MontJourn fkMontjournID
        {
            get { return ffkMontjournID; }
            set { SetPropertyValue<MontJourn>("fkMontjournID", ref ffkMontjournID, value); }
        }
        DateTime fZeitpunkt;
        public DateTime Zeitpunkt
        {
            get { return fZeitpunkt; }
            set { SetPropertyValue<DateTime>("Zeitpunkt", ref fZeitpunkt, value); }
        }
        string fBenutzer;
        [Size(10)]
        public string Benutzer
        {
            get { return fBenutzer; }
            set { SetPropertyValue<string>("Benutzer", ref fBenutzer, value); }
        }
        string fLogEintrag;
        [Size(255)]
        public string LogEintrag
        {
            get { return fLogEintrag; }
            set { SetPropertyValue<string>("LogEintrag", ref fLogEintrag, value); }
        }
        short fLogMOBStatusVorher;
        public short LogMOBStatusVorher
        {
            get { return fLogMOBStatusVorher; }
            set { SetPropertyValue<short>("LogMOBStatusVorher", ref fLogMOBStatusVorher, value); }
        }
        int fLogMOBStatusNachher;
        public int LogMOBStatusNachher
        {
            get { return fLogMOBStatusNachher; }
            set { SetPropertyValue<int>("LogMOBStatusNachher", ref fLogMOBStatusNachher, value); }
        }
    }

}
