//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class MontStrgEinstellungen : XPLiteObject
    {
        int fArtID;
        [Key(true)]
        public int ArtID
        {
            get { return fArtID; }
            set { SetPropertyValue<int>("ArtID", ref fArtID, value); }
        }
        byte fArt;
        public byte Art
        {
            get { return fArt; }
            set { SetPropertyValue<byte>("Art", ref fArt, value); }
        }
        string fBezeichnung;
        [Size(50)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fTextbausteinInhalt;
        [Size(255)]
        public string TextbausteinInhalt
        {
            get { return fTextbausteinInhalt; }
            set { SetPropertyValue<string>("TextbausteinInhalt", ref fTextbausteinInhalt, value); }
        }
        int fHintergrundFarbe;
        public int HintergrundFarbe
        {
            get { return fHintergrundFarbe; }
            set { SetPropertyValue<int>("HintergrundFarbe", ref fHintergrundFarbe, value); }
        }
        int fTextfarbe;
        public int Textfarbe
        {
            get { return fTextfarbe; }
            set { SetPropertyValue<int>("Textfarbe", ref fTextfarbe, value); }
        }
        bool fAnzeigen;
        public bool Anzeigen
        {
            get { return fAnzeigen; }
            set { SetPropertyValue<bool>("Anzeigen", ref fAnzeigen, value); }
        }
        int fImageIndex;
        public int ImageIndex
        {
            get { return fImageIndex; }
            set { SetPropertyValue<int>("ImageIndex", ref fImageIndex, value); }
        }
    }

}
