//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class PersonalQualifikation : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        Personal fPersonalNr;
        [Association(@"PersonalQualifikationReferencesPersonal")]
        public Personal PersonalNr
        {
            get { return fPersonalNr; }
            set { SetPropertyValue<Personal>("PersonalNr", ref fPersonalNr, value); }
        }
        DateTime fDatum;
        [Indexed(Name = @"ix_PersonalQualifikation_Datum")]
        public DateTime Datum
        {
            get { return fDatum; }
            set { SetPropertyValue<DateTime>("Datum", ref fDatum, value); }
        }
        string fBezeichnung;
        [Size(255)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        double fAnzahlTage;
        public double AnzahlTage
        {
            get { return fAnzahlTage; }
            set { SetPropertyValue<double>("AnzahlTage", ref fAnzahlTage, value); }
        }
        string fSeminarOrt;
        [Size(255)]
        public string SeminarOrt
        {
            get { return fSeminarOrt; }
            set { SetPropertyValue<string>("SeminarOrt", ref fSeminarOrt, value); }
        }
        string fAdressKuerzel;
        [Size(24)]
        public string AdressKuerzel
        {
            get { return fAdressKuerzel; }
            set { SetPropertyValue<string>("AdressKuerzel", ref fAdressKuerzel, value); }
        }
        string fSelekt1;
        [Size(20)]
        public string Selekt1
        {
            get { return fSelekt1; }
            set { SetPropertyValue<string>("Selekt1", ref fSelekt1, value); }
        }
        string fSelekt2;
        [Size(20)]
        public string Selekt2
        {
            get { return fSelekt2; }
            set { SetPropertyValue<string>("Selekt2", ref fSelekt2, value); }
        }
        string fZusatz1;
        [Size(20)]
        public string Zusatz1
        {
            get { return fZusatz1; }
            set { SetPropertyValue<string>("Zusatz1", ref fZusatz1, value); }
        }
        string fZusatz2;
        [Size(20)]
        public string Zusatz2
        {
            get { return fZusatz2; }
            set { SetPropertyValue<string>("Zusatz2", ref fZusatz2, value); }
        }
        string fZusatz3;
        [Size(20)]
        public string Zusatz3
        {
            get { return fZusatz3; }
            set { SetPropertyValue<string>("Zusatz3", ref fZusatz3, value); }
        }
        int fAbteilung;
        public int Abteilung
        {
            get { return fAbteilung; }
            set { SetPropertyValue<int>("Abteilung", ref fAbteilung, value); }
        }
        decimal fAusbildungsKosten;
        public decimal AusbildungsKosten
        {
            get { return fAusbildungsKosten; }
            set { SetPropertyValue<decimal>("AusbildungsKosten", ref fAusbildungsKosten, value); }
        }
        string fSeminarBewertung;
        [Size(SizeAttribute.Unlimited)]
        public string SeminarBewertung
        {
            get { return fSeminarBewertung; }
            set { SetPropertyValue<string>("SeminarBewertung", ref fSeminarBewertung, value); }
        }
        string fSchulungInternExtern;
        [Size(1)]
        public string SchulungInternExtern
        {
            get { return fSchulungInternExtern; }
            set { SetPropertyValue<string>("SchulungInternExtern", ref fSchulungInternExtern, value); }
        }
        decimal fInterneKosten;
        public decimal InterneKosten
        {
            get { return fInterneKosten; }
            set { SetPropertyValue<decimal>("InterneKosten", ref fInterneKosten, value); }
        }
        bool fSchulungWiederkehrend;
        public bool SchulungWiederkehrend
        {
            get { return fSchulungWiederkehrend; }
            set { SetPropertyValue<bool>("SchulungWiederkehrend", ref fSchulungWiederkehrend, value); }
        }
        string fWiederkehrendText;
        [Size(50)]
        public string WiederkehrendText
        {
            get { return fWiederkehrendText; }
            set { SetPropertyValue<string>("WiederkehrendText", ref fWiederkehrendText, value); }
        }
        string fWiederkehrendTermin;
        [Size(6)]
        public string WiederkehrendTermin
        {
            get { return fWiederkehrendTermin; }
            set { SetPropertyValue<string>("WiederkehrendTermin", ref fWiederkehrendTermin, value); }
        }
        bool fWirksamkeitGeprueft;
        public bool WirksamkeitGeprueft
        {
            get { return fWirksamkeitGeprueft; }
            set { SetPropertyValue<bool>("WirksamkeitGeprueft", ref fWirksamkeitGeprueft, value); }
        }
        string fWirksamkeitText;
        [Size(255)]
        public string WirksamkeitText
        {
            get { return fWirksamkeitText; }
            set { SetPropertyValue<string>("WirksamkeitText", ref fWirksamkeitText, value); }
        }
    }

}
