//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class Personal : XPLiteObject
    {
        Int64 fPersonalNr;
        [Key]
        public Int64 PersonalNr
        {
            get { return fPersonalNr; }
            set { SetPropertyValue<long>("PersonalNr", ref fPersonalNr, value); }
        }
        string fName;
        [Size(50)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fStrasse;
        [Size(50)]
        public string Strasse
        {
            get { return fStrasse; }
            set { SetPropertyValue<string>("Strasse", ref fStrasse, value); }
        }
        string fPlz;
        [Size(10)]
        public string Plz
        {
            get { return fPlz; }
            set { SetPropertyValue<string>("Plz", ref fPlz, value); }
        }
        string fOrt;
        [Size(50)]
        public string Ort
        {
            get { return fOrt; }
            set { SetPropertyValue<string>("Ort", ref fOrt, value); }
        }
        string fTelefon;
        [Size(30)]
        public string Telefon
        {
            get { return fTelefon; }
            set { SetPropertyValue<string>("Telefon", ref fTelefon, value); }
        }
        DateTime fGeburtstag;
        public DateTime Geburtstag
        {
            get { return fGeburtstag; }
            set { SetPropertyValue<DateTime>("Geburtstag", ref fGeburtstag, value); }
        }
        DateTime fAnstellung;
        public DateTime Anstellung
        {
            get { return fAnstellung; }
            set { SetPropertyValue<DateTime>("Anstellung", ref fAnstellung, value); }
        }
        decimal fStundensatz;
        public decimal Stundensatz
        {
            get { return fStundensatz; }
            set { SetPropertyValue<decimal>("Stundensatz", ref fStundensatz, value); }
        }
        double fInsgemeinkosten;
        public double Insgemeinkosten
        {
            get { return fInsgemeinkosten; }
            set { SetPropertyValue<double>("Insgemeinkosten", ref fInsgemeinkosten, value); }
        }
        decimal fGesStundensatz;
        public decimal GesStundensatz
        {
            get { return fGesStundensatz; }
            set { SetPropertyValue<decimal>("GesStundensatz", ref fGesStundensatz, value); }
        }
        double fStdKorrFaktor;
        public double StdKorrFaktor
        {
            get { return fStdKorrFaktor; }
            set { SetPropertyValue<double>("StdKorrFaktor", ref fStdKorrFaktor, value); }
        }
        byte[] fPersBild;
        [Size(SizeAttribute.Unlimited)]
        public byte[] PersBild
        {
            get { return fPersBild; }
            set { SetPropertyValue<byte[]>("PersBild", ref fPersBild, value); }
        }
        string fPersSozVersNr;
        [Size(30)]
        public string PersSozVersNr
        {
            get { return fPersSozVersNr; }
            set { SetPropertyValue<string>("PersSozVersNr", ref fPersSozVersNr, value); }
        }
        string fPersZusHinweis;
        [Size(SizeAttribute.Unlimited)]
        public string PersZusHinweis
        {
            get { return fPersZusHinweis; }
            set { SetPropertyValue<string>("PersZusHinweis", ref fPersZusHinweis, value); }
        }
        bool fKonv2Euro;
        public bool Konv2Euro
        {
            get { return fKonv2Euro; }
            set { SetPropertyValue<bool>("Konv2Euro", ref fKonv2Euro, value); }
        }
        DateTime fAustritt;
        public DateTime Austritt
        {
            get { return fAustritt; }
            set { SetPropertyValue<DateTime>("Austritt", ref fAustritt, value); }
        }
        string fLohnGruppe;
        [Size(10)]
        public string LohnGruppe
        {
            get { return fLohnGruppe; }
            set { SetPropertyValue<string>("LohnGruppe", ref fLohnGruppe, value); }
        }
        int fStammKST;
        public int StammKST
        {
            get { return fStammKST; }
            set { SetPropertyValue<int>("StammKST", ref fStammKST, value); }
        }
        string fArbZeitGruppe;
        [Size(20)]
        public string ArbZeitGruppe
        {
            get { return fArbZeitGruppe; }
            set { SetPropertyValue<string>("ArbZeitGruppe", ref fArbZeitGruppe, value); }
        }
        string fUserErfasst;
        [Size(8)]
        public string UserErfasst
        {
            get { return fUserErfasst; }
            set { SetPropertyValue<string>("UserErfasst", ref fUserErfasst, value); }
        }
        DateTime fDatumErfasst;
        public DateTime DatumErfasst
        {
            get { return fDatumErfasst; }
            set { SetPropertyValue<DateTime>("DatumErfasst", ref fDatumErfasst, value); }
        }
        string fUserAenderung;
        [Size(8)]
        public string UserAenderung
        {
            get { return fUserAenderung; }
            set { SetPropertyValue<string>("UserAenderung", ref fUserAenderung, value); }
        }
        DateTime fDatumAenderung;
        public DateTime DatumAenderung
        {
            get { return fDatumAenderung; }
            set { SetPropertyValue<DateTime>("DatumAenderung", ref fDatumAenderung, value); }
        }
        string fAdrKuerzel;
        [Size(24)]
        public string AdrKuerzel
        {
            get { return fAdrKuerzel; }
            set { SetPropertyValue<string>("AdrKuerzel", ref fAdrKuerzel, value); }
        }
        string fPersBemerkung1;
        [Size(30)]
        public string PersBemerkung1
        {
            get { return fPersBemerkung1; }
            set { SetPropertyValue<string>("PersBemerkung1", ref fPersBemerkung1, value); }
        }
        string fPersBemerkung2;
        [Size(30)]
        public string PersBemerkung2
        {
            get { return fPersBemerkung2; }
            set { SetPropertyValue<string>("PersBemerkung2", ref fPersBemerkung2, value); }
        }
        string fPersBemerkung3;
        [Size(30)]
        public string PersBemerkung3
        {
            get { return fPersBemerkung3; }
            set { SetPropertyValue<string>("PersBemerkung3", ref fPersBemerkung3, value); }
        }
        string fPersBemerkung4;
        [Size(30)]
        public string PersBemerkung4
        {
            get { return fPersBemerkung4; }
            set { SetPropertyValue<string>("PersBemerkung4", ref fPersBemerkung4, value); }
        }
        string fPersBemerkung5;
        [Size(30)]
        public string PersBemerkung5
        {
            get { return fPersBemerkung5; }
            set { SetPropertyValue<string>("PersBemerkung5", ref fPersBemerkung5, value); }
        }
        double fPersRestUrlaub;
        public double PersRestUrlaub
        {
            get { return fPersRestUrlaub; }
            set { SetPropertyValue<double>("PersRestUrlaub", ref fPersRestUrlaub, value); }
        }
        double fPersJahresUrlaub;
        public double PersJahresUrlaub
        {
            get { return fPersJahresUrlaub; }
            set { SetPropertyValue<double>("PersJahresUrlaub", ref fPersJahresUrlaub, value); }
        }
        double fPersUeberstundenVorjahr;
        public double PersUeberstundenVorjahr
        {
            get { return fPersUeberstundenVorjahr; }
            set { SetPropertyValue<double>("PersUeberstundenVorjahr", ref fPersUeberstundenVorjahr, value); }
        }
        double fPersUeberstundenAktivjahr;
        public double PersUeberstundenAktivjahr
        {
            get { return fPersUeberstundenAktivjahr; }
            set { SetPropertyValue<double>("PersUeberstundenAktivjahr", ref fPersUeberstundenAktivjahr, value); }
        }
        int ffkRegelarbeitszeit;
        public int fkRegelarbeitszeit
        {
            get { return ffkRegelarbeitszeit; }
            set { SetPropertyValue<int>("fkRegelarbeitszeit", ref ffkRegelarbeitszeit, value); }
        }
        string fBenutzerID;
        [Size(8)]
        public string BenutzerID
        {
            get { return fBenutzerID; }
            set { SetPropertyValue<string>("BenutzerID", ref fBenutzerID, value); }
        }
        string fPersArtikelNr;
        [Size(30)]
        public string PersArtikelNr
        {
            get { return fPersArtikelNr; }
            set { SetPropertyValue<string>("PersArtikelNr", ref fPersArtikelNr, value); }
        }
        short fNullOK;
        public short NullOK
        {
            get { return fNullOK; }
            set { SetPropertyValue<short>("NullOK", ref fNullOK, value); }
        }
        string fmobDeviceID;
        [Size(30)]
        public string mobDeviceID
        {
            get { return fmobDeviceID; }
            set { SetPropertyValue<string>("mobDeviceID", ref fmobDeviceID, value); }
        }
        string fMobMonteurLager;
        [Size(50)]
        public string MobMonteurLager
        {
            get { return fMobMonteurLager; }
            set { SetPropertyValue<string>("MobMonteurLager", ref fMobMonteurLager, value); }
        }
        string fSortIDX;
        [Size(10)]
        public string SortIDX
        {
            get { return fSortIDX; }
            set { SetPropertyValue<string>("SortIDX", ref fSortIDX, value); }
        }
        [Association(@"PersonalBewertungReferencesPersonal")]
        public XPCollection<PersonalBewertung> PersonalBewertungs { get { return GetCollection<PersonalBewertung>("PersonalBewertungs"); } }
        [Association(@"PersonalJahreswerteReferencesPersonal")]
        public XPCollection<PersonalJahreswerte> PersonalJahreswertes { get { return GetCollection<PersonalJahreswerte>("PersonalJahreswertes"); } }
        [Association(@"PersonalQualifikationReferencesPersonal")]
        public XPCollection<PersonalQualifikation> PersonalQualifikations { get { return GetCollection<PersonalQualifikation>("PersonalQualifikations"); } }
    }

}
