//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class ProjektAdressen : XPLiteObject
    {
        long fAdressId;
        [Key(true)]
        public long AdressId
        {
            get { return fAdressId; }
            set { SetPropertyValue<long>("AdressId", ref fAdressId, value); }
        }
        string fProjNr;
        [Indexed(Name = @"IX_ProjektAdressenProjNr")]
        [Size(15)]
        public string ProjNr
        {
            get { return fProjNr; }
            set { SetPropertyValue<string>("ProjNr", ref fProjNr, value); }
        }
        string fAdrNrGes;
        [Indexed(Name = @"IX_ProjektAdressenAdrNrGes")]
        [Size(24)]
        public string AdrNrGes
        {
            get { return fAdrNrGes; }
            set { SetPropertyValue<string>("AdrNrGes", ref fAdrNrGes, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
    }

}
