//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class PSBietergruppe_Bieterkopf : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        PSBietergruppen ffkGruppenID;
        [Association(@"PSBietergruppe_BieterkopfReferencesPSBietergruppen")]
        public PSBietergruppen fkGruppenID
        {
            get { return ffkGruppenID; }
            set { SetPropertyValue<PSBietergruppen>("fkGruppenID", ref ffkGruppenID, value); }
        }
        PSBieterkopf ffkBieterKopfID;
        [Association(@"PSBietergruppe_BieterkopfReferencesPSBieterkopf")]
        public PSBieterkopf fkBieterKopfID
        {
            get { return ffkBieterKopfID; }
            set { SetPropertyValue<PSBieterkopf>("fkBieterKopfID", ref ffkBieterKopfID, value); }
        }
    }

}
