//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class PSPreiseKorr : XPLiteObject
    {
        string fID;
        [Key]
        public string ID
        {
            get { return fID; }
            set { SetPropertyValue<string>("ID", ref fID, value); }
        }
        float fKorrektur;
        public float Korrektur
        {
            get { return fKorrektur; }
            set { SetPropertyValue<float>("Korrektur", ref fKorrektur, value); }
        }
        byte fKorrArt;
        public byte KorrArt
        {
            get { return fKorrArt; }
            set { SetPropertyValue<byte>("KorrArt", ref fKorrArt, value); }
        }
        DateTime fDatum;
        public DateTime Datum
        {
            get { return fDatum; }
            set { SetPropertyValue<DateTime>("Datum", ref fDatum, value); }
        }
        string fUserID;
        [Size(8)]
        public string UserID
        {
            get { return fUserID; }
            set { SetPropertyValue<string>("UserID", ref fUserID, value); }
        }
        PSPreise fPSPreiseID;
        [Size(95)]
        [Association(@"PSPreiseKorrReferencesPSPreise")]
        public PSPreise PSPreiseID
        {
            get { return fPSPreiseID; }
            set { SetPropertyValue<PSPreise>("PSPreiseID", ref fPSPreiseID, value); }
        }
    }

}
