//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class rebBemerkung : XPLiteObject
    {
        int fpkBemerkung;
        [Key(true)]
        public int pkBemerkung
        {
            get { return fpkBemerkung; }
            set { SetPropertyValue<int>("pkBemerkung", ref fpkBemerkung, value); }
        }
        int ffkER;
        public int fkER
        {
            get { return ffkER; }
            set { SetPropertyValue<int>("fkER", ref ffkER, value); }
        }
        string fFeld1;
        [Size(250)]
        public string Feld1
        {
            get { return fFeld1; }
            set { SetPropertyValue<string>("Feld1", ref fFeld1, value); }
        }
        string fFeld2;
        [Size(250)]
        public string Feld2
        {
            get { return fFeld2; }
            set { SetPropertyValue<string>("Feld2", ref fFeld2, value); }
        }
        string fFeld3;
        [Size(250)]
        public string Feld3
        {
            get { return fFeld3; }
            set { SetPropertyValue<string>("Feld3", ref fFeld3, value); }
        }
        string fFeld4;
        [Size(250)]
        public string Feld4
        {
            get { return fFeld4; }
            set { SetPropertyValue<string>("Feld4", ref fFeld4, value); }
        }
        string fFeld5;
        [Size(250)]
        public string Feld5
        {
            get { return fFeld5; }
            set { SetPropertyValue<string>("Feld5", ref fFeld5, value); }
        }
    }

}
