//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class rebBuchungTmp : XPLiteObject
    {
        int fpkBuchungTmp;
        [Key(true)]
        public int pkBuchungTmp
        {
            get { return fpkBuchungTmp; }
            set { SetPropertyValue<int>("pkBuchungTmp", ref fpkBuchungTmp, value); }
        }
        int fBuchungZeilenNr;
        public int BuchungZeilenNr
        {
            get { return fBuchungZeilenNr; }
            set { SetPropertyValue<int>("BuchungZeilenNr", ref fBuchungZeilenNr, value); }
        }
        string ffkKontoNr;
        [Size(30)]
        public string fkKontoNr
        {
            get { return ffkKontoNr; }
            set { SetPropertyValue<string>("fkKontoNr", ref ffkKontoNr, value); }
        }
        string ffkBestellNr;
        [Indexed(Name = @"IX_rebBuchungTmp_fkBestellNr")]
        [Size(20)]
        public string fkBestellNr
        {
            get { return ffkBestellNr; }
            set { SetPropertyValue<string>("fkBestellNr", ref ffkBestellNr, value); }
        }
        string fLSNr;
        [Indexed(Name = @"IX_rebBuchungTmp_LSNr")]
        [Size(30)]
        public string LSNr
        {
            get { return fLSNr; }
            set { SetPropertyValue<string>("LSNr", ref fLSNr, value); }
        }
        DateTime fMinLSDatum;
        public DateTime MinLSDatum
        {
            get { return fMinLSDatum; }
            set { SetPropertyValue<DateTime>("MinLSDatum", ref fMinLSDatum, value); }
        }
        double fSumLieferMenge;
        public double SumLieferMenge
        {
            get { return fSumLieferMenge; }
            set { SetPropertyValue<double>("SumLieferMenge", ref fSumLieferMenge, value); }
        }
        decimal fLieferPreis;
        public decimal LieferPreis
        {
            get { return fLieferPreis; }
            set { SetPropertyValue<decimal>("LieferPreis", ref fLieferPreis, value); }
        }
        string ffkProjNr;
        [Size(15)]
        public string fkProjNr
        {
            get { return ffkProjNr; }
            set { SetPropertyValue<string>("fkProjNr", ref ffkProjNr, value); }
        }
        string fUserName;
        [Size(50)]
        public string UserName
        {
            get { return fUserName; }
            set { SetPropertyValue<string>("UserName", ref fUserName, value); }
        }
        string fComputerName;
        [Size(120)]
        public string ComputerName
        {
            get { return fComputerName; }
            set { SetPropertyValue<string>("ComputerName", ref fComputerName, value); }
        }
        DateTime fZeitStempel;
        public DateTime ZeitStempel
        {
            get { return fZeitStempel; }
            set { SetPropertyValue<DateTime>("ZeitStempel", ref fZeitStempel, value); }
        }
    }

}
