//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class rebBenutzerKfg : XPLiteObject
    {
        int fpkBenutzerKfg;
        [Key(true)]
        public int pkBenutzerKfg
        {
            get { return fpkBenutzerKfg; }
            set { SetPropertyValue<int>("pkBenutzerKfg", ref fpkBenutzerKfg, value); }
        }
        bool fAllgGrdDatVerwenden;
        public bool AllgGrdDatVerwenden
        {
            get { return fAllgGrdDatVerwenden; }
            set { SetPropertyValue<bool>("AllgGrdDatVerwenden", ref fAllgGrdDatVerwenden, value); }
        }
        string fAllgFkBenutzer;
        [Indexed(Name = @"IX_rebAllgFkBenutzer_AllgFkBenutzer", Unique = true)]
        [Size(50)]
        public string AllgFkBenutzer
        {
            get { return fAllgFkBenutzer; }
            set { SetPropertyValue<string>("AllgFkBenutzer", ref fAllgFkBenutzer, value); }
        }
    }

}
