//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class rebFilterKfg : XPLiteObject
    {
        int fpkFilter;
        [Key]
        public int pkFilter
        {
            get { return fpkFilter; }
            set { SetPropertyValue<int>("pkFilter", ref fpkFilter, value); }
        }
        int fMonat;
        public int Monat
        {
            get { return fMonat; }
            set { SetPropertyValue<int>("Monat", ref fMonat, value); }
        }
        int fJahr;
        public int Jahr
        {
            get { return fJahr; }
            set { SetPropertyValue<int>("Jahr", ref fJahr, value); }
        }
        int ffkAbteilung;
        public int fkAbteilung
        {
            get { return ffkAbteilung; }
            set { SetPropertyValue<int>("fkAbteilung", ref ffkAbteilung, value); }
        }
        int ffkEinReStatus;
        public int fkEinReStatus
        {
            get { return ffkEinReStatus; }
            set { SetPropertyValue<int>("fkEinReStatus", ref ffkEinReStatus, value); }
        }
        string ffkKonto;
        [Size(30)]
        public string fkKonto
        {
            get { return ffkKonto; }
            set { SetPropertyValue<string>("fkKonto", ref ffkKonto, value); }
        }
        string ffkUserID;
        [Indexed(Name = @"IX_rebFilterKfg_fkUserID")]
        [Size(8)]
        public string fkUserID
        {
            get { return ffkUserID; }
            set { SetPropertyValue<string>("fkUserID", ref ffkUserID, value); }
        }
    }

}
