//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{
    [DevExpress.ExpressApp.DC.XafDefaultProperty("RechNr")]
    public partial class RechZahlungen : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        Rechnung fRechNr;
        [Size(18)]
        [Association(@"RechZahlungenReferencesRechnung")]
        public Rechnung RechNr
        {
            get { return fRechNr; }
            set { SetPropertyValue<Rechnung>("RechNr", ref fRechNr, value); }
        }
        DateTime fZahlDatum;
        public DateTime ZahlDatum
        {
            get { return fZahlDatum; }
            set { SetPropertyValue<DateTime>("ZahlDatum", ref fZahlDatum, value); }
        }
        double fZahlBetrag;
        public double ZahlBetrag
        {
            get { return fZahlBetrag; }
            set { SetPropertyValue<double>("ZahlBetrag", ref fZahlBetrag, value); }
        }
        double fSkonto;
        public double Skonto
        {
            get { return fSkonto; }
            set { SetPropertyValue<double>("Skonto", ref fSkonto, value); }
        }
        double fAbzugSonst;
        public double AbzugSonst
        {
            get { return fAbzugSonst; }
            set { SetPropertyValue<double>("AbzugSonst", ref fAbzugSonst, value); }
        }
        string fAbzugBem;
        [Size(255)]
        public string AbzugBem
        {
            get { return fAbzugBem; }
            set { SetPropertyValue<string>("AbzugBem", ref fAbzugBem, value); }
        }
        int fBankID;
        [Indexed(Name = @"IX_RechZahlungenBankID")]
        public int BankID
        {
            get { return fBankID; }
            set { SetPropertyValue<int>("BankID", ref fBankID, value); }
        }
        string fKtoAuszugsNr;
        [Size(20)]
        public string KtoAuszugsNr
        {
            get { return fKtoAuszugsNr; }
            set { SetPropertyValue<string>("KtoAuszugsNr", ref fKtoAuszugsNr, value); }
        }
        string fErfasstDurch;
        [Size(8)]
        public string ErfasstDurch
        {
            get { return fErfasstDurch; }
            set { SetPropertyValue<string>("ErfasstDurch", ref fErfasstDurch, value); }
        }
        DateTime fErfasstAm;
        public DateTime ErfasstAm
        {
            get { return fErfasstAm; }
            set { SetPropertyValue<DateTime>("ErfasstAm", ref fErfasstAm, value); }
        }
        string fGeaendertDurch;
        [Size(8)]
        public string GeaendertDurch
        {
            get { return fGeaendertDurch; }
            set { SetPropertyValue<string>("GeaendertDurch", ref fGeaendertDurch, value); }
        }
        DateTime fGeaendertAm;
        public DateTime GeaendertAm
        {
            get { return fGeaendertAm; }
            set { SetPropertyValue<DateTime>("GeaendertAm", ref fGeaendertAm, value); }
        }
        string fBemerkung;
        [Size(SizeAttribute.Unlimited)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
        short fAbzugKennung;
        public short AbzugKennung
        {
            get { return fAbzugKennung; }
            set { SetPropertyValue<short>("AbzugKennung", ref fAbzugKennung, value); }
        }
    }

}
