//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class RegelArbeitsZeit : XPLiteObject
    {
        int fID;
        [Key(true)]
        public int ID
        {
            get { return fID; }
            set { SetPropertyValue<int>("ID", ref fID, value); }
        }
        string fBezeichnung;
        [Size(50)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fUserErfasst;
        [Size(8)]
        public string UserErfasst
        {
            get { return fUserErfasst; }
            set { SetPropertyValue<string>("UserErfasst", ref fUserErfasst, value); }
        }
        DateTime fDatumErfasst;
        public DateTime DatumErfasst
        {
            get { return fDatumErfasst; }
            set { SetPropertyValue<DateTime>("DatumErfasst", ref fDatumErfasst, value); }
        }
        string fUserAenderung;
        [Size(8)]
        public string UserAenderung
        {
            get { return fUserAenderung; }
            set { SetPropertyValue<string>("UserAenderung", ref fUserAenderung, value); }
        }
        DateTime fDatumAenderung;
        public DateTime DatumAenderung
        {
            get { return fDatumAenderung; }
            set { SetPropertyValue<DateTime>("DatumAenderung", ref fDatumAenderung, value); }
        }
        string fMonVon1;
        [Size(5)]
        public string MonVon1
        {
            get { return fMonVon1; }
            set { SetPropertyValue<string>("MonVon1", ref fMonVon1, value); }
        }
        string fMonBis1;
        [Size(5)]
        public string MonBis1
        {
            get { return fMonBis1; }
            set { SetPropertyValue<string>("MonBis1", ref fMonBis1, value); }
        }
        string fMonVon2;
        [Size(5)]
        public string MonVon2
        {
            get { return fMonVon2; }
            set { SetPropertyValue<string>("MonVon2", ref fMonVon2, value); }
        }
        string fMonBis2;
        [Size(5)]
        public string MonBis2
        {
            get { return fMonBis2; }
            set { SetPropertyValue<string>("MonBis2", ref fMonBis2, value); }
        }
        string fMonVon3;
        [Size(5)]
        public string MonVon3
        {
            get { return fMonVon3; }
            set { SetPropertyValue<string>("MonVon3", ref fMonVon3, value); }
        }
        string fMonBis3;
        [Size(5)]
        public string MonBis3
        {
            get { return fMonBis3; }
            set { SetPropertyValue<string>("MonBis3", ref fMonBis3, value); }
        }
        double fMonArbzt;
        public double MonArbzt
        {
            get { return fMonArbzt; }
            set { SetPropertyValue<double>("MonArbzt", ref fMonArbzt, value); }
        }
        string fDieVon1;
        [Size(5)]
        public string DieVon1
        {
            get { return fDieVon1; }
            set { SetPropertyValue<string>("DieVon1", ref fDieVon1, value); }
        }
        string fDieBis1;
        [Size(5)]
        public string DieBis1
        {
            get { return fDieBis1; }
            set { SetPropertyValue<string>("DieBis1", ref fDieBis1, value); }
        }
        string fDieVon2;
        [Size(5)]
        public string DieVon2
        {
            get { return fDieVon2; }
            set { SetPropertyValue<string>("DieVon2", ref fDieVon2, value); }
        }
        string fDieBis2;
        [Size(5)]
        public string DieBis2
        {
            get { return fDieBis2; }
            set { SetPropertyValue<string>("DieBis2", ref fDieBis2, value); }
        }
        string fDieVon3;
        [Size(5)]
        public string DieVon3
        {
            get { return fDieVon3; }
            set { SetPropertyValue<string>("DieVon3", ref fDieVon3, value); }
        }
        string fDieBis3;
        [Size(5)]
        public string DieBis3
        {
            get { return fDieBis3; }
            set { SetPropertyValue<string>("DieBis3", ref fDieBis3, value); }
        }
        double fDieArbzt;
        public double DieArbzt
        {
            get { return fDieArbzt; }
            set { SetPropertyValue<double>("DieArbzt", ref fDieArbzt, value); }
        }
        string fMitVon1;
        [Size(5)]
        public string MitVon1
        {
            get { return fMitVon1; }
            set { SetPropertyValue<string>("MitVon1", ref fMitVon1, value); }
        }
        string fMitBis1;
        [Size(5)]
        public string MitBis1
        {
            get { return fMitBis1; }
            set { SetPropertyValue<string>("MitBis1", ref fMitBis1, value); }
        }
        string fMitVon2;
        [Size(5)]
        public string MitVon2
        {
            get { return fMitVon2; }
            set { SetPropertyValue<string>("MitVon2", ref fMitVon2, value); }
        }
        string fMitBis2;
        [Size(5)]
        public string MitBis2
        {
            get { return fMitBis2; }
            set { SetPropertyValue<string>("MitBis2", ref fMitBis2, value); }
        }
        string fMitVon3;
        [Size(5)]
        public string MitVon3
        {
            get { return fMitVon3; }
            set { SetPropertyValue<string>("MitVon3", ref fMitVon3, value); }
        }
        string fMitBis3;
        [Size(5)]
        public string MitBis3
        {
            get { return fMitBis3; }
            set { SetPropertyValue<string>("MitBis3", ref fMitBis3, value); }
        }
        double fMitArbzt;
        public double MitArbzt
        {
            get { return fMitArbzt; }
            set { SetPropertyValue<double>("MitArbzt", ref fMitArbzt, value); }
        }
        string fDonVon1;
        [Size(5)]
        public string DonVon1
        {
            get { return fDonVon1; }
            set { SetPropertyValue<string>("DonVon1", ref fDonVon1, value); }
        }
        string fDonBis1;
        [Size(5)]
        public string DonBis1
        {
            get { return fDonBis1; }
            set { SetPropertyValue<string>("DonBis1", ref fDonBis1, value); }
        }
        string fDonVon2;
        [Size(5)]
        public string DonVon2
        {
            get { return fDonVon2; }
            set { SetPropertyValue<string>("DonVon2", ref fDonVon2, value); }
        }
        string fDonBis2;
        [Size(5)]
        public string DonBis2
        {
            get { return fDonBis2; }
            set { SetPropertyValue<string>("DonBis2", ref fDonBis2, value); }
        }
        string fDonVon3;
        [Size(5)]
        public string DonVon3
        {
            get { return fDonVon3; }
            set { SetPropertyValue<string>("DonVon3", ref fDonVon3, value); }
        }
        string fDonBis3;
        [Size(5)]
        public string DonBis3
        {
            get { return fDonBis3; }
            set { SetPropertyValue<string>("DonBis3", ref fDonBis3, value); }
        }
        double fDonArbzt;
        public double DonArbzt
        {
            get { return fDonArbzt; }
            set { SetPropertyValue<double>("DonArbzt", ref fDonArbzt, value); }
        }
        string fFreVon1;
        [Size(5)]
        public string FreVon1
        {
            get { return fFreVon1; }
            set { SetPropertyValue<string>("FreVon1", ref fFreVon1, value); }
        }
        string fFreBis1;
        [Size(5)]
        public string FreBis1
        {
            get { return fFreBis1; }
            set { SetPropertyValue<string>("FreBis1", ref fFreBis1, value); }
        }
        string fFreVon2;
        [Size(5)]
        public string FreVon2
        {
            get { return fFreVon2; }
            set { SetPropertyValue<string>("FreVon2", ref fFreVon2, value); }
        }
        string fFreBis2;
        [Size(5)]
        public string FreBis2
        {
            get { return fFreBis2; }
            set { SetPropertyValue<string>("FreBis2", ref fFreBis2, value); }
        }
        string fFreVon3;
        [Size(5)]
        public string FreVon3
        {
            get { return fFreVon3; }
            set { SetPropertyValue<string>("FreVon3", ref fFreVon3, value); }
        }
        string fFreBis3;
        [Size(5)]
        public string FreBis3
        {
            get { return fFreBis3; }
            set { SetPropertyValue<string>("FreBis3", ref fFreBis3, value); }
        }
        double fFreArbzt;
        public double FreArbzt
        {
            get { return fFreArbzt; }
            set { SetPropertyValue<double>("FreArbzt", ref fFreArbzt, value); }
        }
        string fSamVon1;
        [Size(5)]
        public string SamVon1
        {
            get { return fSamVon1; }
            set { SetPropertyValue<string>("SamVon1", ref fSamVon1, value); }
        }
        string fSamBis1;
        [Size(5)]
        public string SamBis1
        {
            get { return fSamBis1; }
            set { SetPropertyValue<string>("SamBis1", ref fSamBis1, value); }
        }
        string fSamVon2;
        [Size(5)]
        public string SamVon2
        {
            get { return fSamVon2; }
            set { SetPropertyValue<string>("SamVon2", ref fSamVon2, value); }
        }
        string fSamBis2;
        [Size(5)]
        public string SamBis2
        {
            get { return fSamBis2; }
            set { SetPropertyValue<string>("SamBis2", ref fSamBis2, value); }
        }
        string fSamVon3;
        [Size(5)]
        public string SamVon3
        {
            get { return fSamVon3; }
            set { SetPropertyValue<string>("SamVon3", ref fSamVon3, value); }
        }
        string fSamBis3;
        [Size(5)]
        public string SamBis3
        {
            get { return fSamBis3; }
            set { SetPropertyValue<string>("SamBis3", ref fSamBis3, value); }
        }
        double fSamArbzt;
        public double SamArbzt
        {
            get { return fSamArbzt; }
            set { SetPropertyValue<double>("SamArbzt", ref fSamArbzt, value); }
        }
        string fSonVon1;
        [Size(5)]
        public string SonVon1
        {
            get { return fSonVon1; }
            set { SetPropertyValue<string>("SonVon1", ref fSonVon1, value); }
        }
        string fSonBis1;
        [Size(5)]
        public string SonBis1
        {
            get { return fSonBis1; }
            set { SetPropertyValue<string>("SonBis1", ref fSonBis1, value); }
        }
        string fSonVon2;
        [Size(5)]
        public string SonVon2
        {
            get { return fSonVon2; }
            set { SetPropertyValue<string>("SonVon2", ref fSonVon2, value); }
        }
        string fSonBis2;
        [Size(5)]
        public string SonBis2
        {
            get { return fSonBis2; }
            set { SetPropertyValue<string>("SonBis2", ref fSonBis2, value); }
        }
        string fSonVon3;
        [Size(5)]
        public string SonVon3
        {
            get { return fSonVon3; }
            set { SetPropertyValue<string>("SonVon3", ref fSonVon3, value); }
        }
        string fSonBis3;
        [Size(5)]
        public string SonBis3
        {
            get { return fSonBis3; }
            set { SetPropertyValue<string>("SonBis3", ref fSonBis3, value); }
        }
        double fSonArbzt;
        public double SonArbzt
        {
            get { return fSonArbzt; }
            set { SetPropertyValue<double>("SonArbzt", ref fSonArbzt, value); }
        }
        double fGesArbzt;
        public double GesArbzt
        {
            get { return fGesArbzt; }
            set { SetPropertyValue<double>("GesArbzt", ref fGesArbzt, value); }
        }
    }

}
