//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class Textbausteine : XPLiteObject
    {
        string fTextKey;
        [Key]
        [Size(20)]
        public string TextKey
        {
            get { return fTextKey; }
            set { SetPropertyValue<string>("TextKey", ref fTextKey, value); }
        }
        string fBeschreibung;
        [Size(255)]
        public string Beschreibung
        {
            get { return fBeschreibung; }
            set { SetPropertyValue<string>("Beschreibung", ref fBeschreibung, value); }
        }
        string fText;
        [Size(SizeAttribute.Unlimited)]
        public string Text
        {
            get { return fText; }
            set { SetPropertyValue<string>("Text", ref fText, value); }
        }
        short fKennung;
        public short Kennung
        {
            get { return fKennung; }
            set { SetPropertyValue<short>("Kennung", ref fKennung, value); }
        }
        string fBenutzerID;
        [Size(8)]
        public string BenutzerID
        {
            get { return fBenutzerID; }
            set { SetPropertyValue<string>("BenutzerID", ref fBenutzerID, value); }
        }
        short fVorgangsart;
        public short Vorgangsart
        {
            get { return fVorgangsart; }
            set { SetPropertyValue<short>("Vorgangsart", ref fVorgangsart, value); }
        }
        KategorienVerzeichnisStrukturTextbausteine ffkIDVz;
        [Association(@"TextbausteineReferencesKategorienVerzeichnisStrukturTextbausteine")]
        public KategorienVerzeichnisStrukturTextbausteine fkIDVz
        {
            get { return ffkIDVz; }
            set { SetPropertyValue<KategorienVerzeichnisStrukturTextbausteine>("fkIDVz", ref ffkIDVz, value); }
        }
        string fCreateUser;
        [Size(8)]
        public string CreateUser
        {
            get { return fCreateUser; }
            set { SetPropertyValue<string>("CreateUser", ref fCreateUser, value); }
        }
        DateTime fCreateDate;
        public DateTime CreateDate
        {
            get { return fCreateDate; }
            set { SetPropertyValue<DateTime>("CreateDate", ref fCreateDate, value); }
        }
        string fEditUser;
        [Size(8)]
        public string EditUser
        {
            get { return fEditUser; }
            set { SetPropertyValue<string>("EditUser", ref fEditUser, value); }
        }
        DateTime fEditDate;
        public DateTime EditDate
        {
            get { return fEditDate; }
            set { SetPropertyValue<DateTime>("EditDate", ref fEditDate, value); }
        }
    }

}
