//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class Vergleich : XPLiteObject
    {
        string fVerglNr;
        [Indexed(Name = @"VerglNr")]
        [Size(25)]
        public string VerglNr
        {
            get { return fVerglNr; }
            set { SetPropertyValue<string>("VerglNr", ref fVerglNr, value); }
        }
        string fKatVergl;
        [Size(10)]
        public string KatVergl
        {
            get { return fKatVergl; }
            set { SetPropertyValue<string>("KatVergl", ref fKatVergl, value); }
        }
        string fHptNr;
        [Indexed(Name = @"HptNr")]
        [Size(25)]
        public string HptNr
        {
            get { return fHptNr; }
            set { SetPropertyValue<string>("HptNr", ref fHptNr, value); }
        }
        long fID;
        [Key(true)]
        public long ID
        {
            get { return fID; }
            set { SetPropertyValue<long>("ID", ref fID, value); }
        }
    }

}
