//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class WartAnlagen : XPLiteObject
    {
        string fAnlagenNr;
        [Key]
        [Size(15)]
        public string AnlagenNr
        {
            get { return fAnlagenNr; }
            set { SetPropertyValue<string>("AnlagenNr", ref fAnlagenNr, value); }
        }
        string fAnlagenAdr;
        [Indexed(Name = @"AnlagenAdr")]
        [Size(24)]
        public string AnlagenAdr
        {
            get { return fAnlagenAdr; }
            set { SetPropertyValue<string>("AnlagenAdr", ref fAnlagenAdr, value); }
        }
        string fEigentuemerAdr;
        [Indexed(Name = @"EigentuemerAdr")]
        [Size(24)]
        public string EigentuemerAdr
        {
            get { return fEigentuemerAdr; }
            set { SetPropertyValue<string>("EigentuemerAdr", ref fEigentuemerAdr, value); }
        }
        string fMieterAdr;
        [Indexed(Name = @"MieterAdr")]
        [Size(24)]
        public string MieterAdr
        {
            get { return fMieterAdr; }
            set { SetPropertyValue<string>("MieterAdr", ref fMieterAdr, value); }
        }
        string fHausverwalterAdr;
        [Indexed(Name = @"HausverwalterAdr")]
        [Size(50)]
        public string HausverwalterAdr
        {
            get { return fHausverwalterAdr; }
            set { SetPropertyValue<string>("HausverwalterAdr", ref fHausverwalterAdr, value); }
        }
        string fHausmeisterAdr;
        [Indexed(Name = @"HausmeisterAdr")]
        [Size(50)]
        public string HausmeisterAdr
        {
            get { return fHausmeisterAdr; }
            set { SetPropertyValue<string>("HausmeisterAdr", ref fHausmeisterAdr, value); }
        }
        string fPaechterAdr;
        [Indexed(Name = @"PaechterAdr")]
        [Size(50)]
        public string PaechterAdr
        {
            get { return fPaechterAdr; }
            set { SetPropertyValue<string>("PaechterAdr", ref fPaechterAdr, value); }
        }
        string fRechnungsAdr;
        [Indexed(Name = @"RechnungsAdr")]
        [Size(50)]
        public string RechnungsAdr
        {
            get { return fRechnungsAdr; }
            set { SetPropertyValue<string>("RechnungsAdr", ref fRechnungsAdr, value); }
        }
        string fBezeichnung;
        [Size(255)]
        public string Bezeichnung
        {
            get { return fBezeichnung; }
            set { SetPropertyValue<string>("Bezeichnung", ref fBezeichnung, value); }
        }
        string fAnlagenOrt;
        [Size(255)]
        public string AnlagenOrt
        {
            get { return fAnlagenOrt; }
            set { SetPropertyValue<string>("AnlagenOrt", ref fAnlagenOrt, value); }
        }
        short fAntritt;
        public short Antritt
        {
            get { return fAntritt; }
            set { SetPropertyValue<short>("Antritt", ref fAntritt, value); }
        }
        string fSelekt;
        [Indexed(Name = @"Selekt")]
        [Size(30)]
        public string Selekt
        {
            get { return fSelekt; }
            set { SetPropertyValue<string>("Selekt", ref fSelekt, value); }
        }
        string fInfoText;
        [Size(SizeAttribute.Unlimited)]
        public string InfoText
        {
            get { return fInfoText; }
            set { SetPropertyValue<string>("InfoText", ref fInfoText, value); }
        }
        string fMonteur;
        [Size(50)]
        public string Monteur
        {
            get { return fMonteur; }
            set { SetPropertyValue<string>("Monteur", ref fMonteur, value); }
        }
        string fTextNr2Abrech;
        [Size(20)]
        public string TextNr2Abrech
        {
            get { return fTextNr2Abrech; }
            set { SetPropertyValue<string>("TextNr2Abrech", ref fTextNr2Abrech, value); }
        }
        string fBemerkungen;
        [Size(SizeAttribute.Unlimited)]
        public string Bemerkungen
        {
            get { return fBemerkungen; }
            set { SetPropertyValue<string>("Bemerkungen", ref fBemerkungen, value); }
        }
        int fAbteilungsNr;
        [Indexed(Name = @"AbteilungsNr")]
        public int AbteilungsNr
        {
            get { return fAbteilungsNr; }
            set { SetPropertyValue<int>("AbteilungsNr", ref fAbteilungsNr, value); }
        }
        string fBrennstoffart;
        [Indexed(Name = @"Brennstoffart")]
        [Size(25)]
        public string Brennstoffart
        {
            get { return fBrennstoffart; }
            set { SetPropertyValue<string>("Brennstoffart", ref fBrennstoffart, value); }
        }
        string fErfasstUser;
        [Size(8)]
        public string ErfasstUser
        {
            get { return fErfasstUser; }
            set { SetPropertyValue<string>("ErfasstUser", ref fErfasstUser, value); }
        }
        DateTime fErfasstDatum;
        public DateTime ErfasstDatum
        {
            get { return fErfasstDatum; }
            set { SetPropertyValue<DateTime>("ErfasstDatum", ref fErfasstDatum, value); }
        }
        string fGeaendertUser;
        [Size(8)]
        public string GeaendertUser
        {
            get { return fGeaendertUser; }
            set { SetPropertyValue<string>("GeaendertUser", ref fGeaendertUser, value); }
        }
        DateTime fGeaendertDatum;
        public DateTime GeaendertDatum
        {
            get { return fGeaendertDatum; }
            set { SetPropertyValue<DateTime>("GeaendertDatum", ref fGeaendertDatum, value); }
        }
        string flockedUser;
        [Size(8)]
        public string lockedUser
        {
            get { return flockedUser; }
            set { SetPropertyValue<string>("lockedUser", ref flockedUser, value); }
        }
        DateTime flockedDate;
        public DateTime lockedDate
        {
            get { return flockedDate; }
            set { SetPropertyValue<DateTime>("lockedDate", ref flockedDate, value); }
        }
        string fTempSort;
        [Indexed(Name = @"TempSort")]
        [Size(15)]
        public string TempSort
        {
            get { return fTempSort; }
            set { SetPropertyValue<string>("TempSort", ref fTempSort, value); }
        }
        string fZuProjNr;
        [Size(15)]
        public string ZuProjNr
        {
            get { return fZuProjNr; }
            set { SetPropertyValue<string>("ZuProjNr", ref fZuProjNr, value); }
        }
        string fBenutzerFeld1;
        [Size(250)]
        public string BenutzerFeld1
        {
            get { return fBenutzerFeld1; }
            set { SetPropertyValue<string>("BenutzerFeld1", ref fBenutzerFeld1, value); }
        }
        string fBenutzerFeld2;
        [Size(250)]
        public string BenutzerFeld2
        {
            get { return fBenutzerFeld2; }
            set { SetPropertyValue<string>("BenutzerFeld2", ref fBenutzerFeld2, value); }
        }
        string fBenutzerFeld3;
        [Size(250)]
        public string BenutzerFeld3
        {
            get { return fBenutzerFeld3; }
            set { SetPropertyValue<string>("BenutzerFeld3", ref fBenutzerFeld3, value); }
        }
        string fBenutzerFeld4;
        [Size(250)]
        public string BenutzerFeld4
        {
            get { return fBenutzerFeld4; }
            set { SetPropertyValue<string>("BenutzerFeld4", ref fBenutzerFeld4, value); }
        }
        string fBenutzerFeld5;
        [Size(250)]
        public string BenutzerFeld5
        {
            get { return fBenutzerFeld5; }
            set { SetPropertyValue<string>("BenutzerFeld5", ref fBenutzerFeld5, value); }
        }
        string fBenutzerFeld6;
        [Size(250)]
        public string BenutzerFeld6
        {
            get { return fBenutzerFeld6; }
            set { SetPropertyValue<string>("BenutzerFeld6", ref fBenutzerFeld6, value); }
        }
        string fBenutzerFeld7;
        [Size(250)]
        public string BenutzerFeld7
        {
            get { return fBenutzerFeld7; }
            set { SetPropertyValue<string>("BenutzerFeld7", ref fBenutzerFeld7, value); }
        }
        string fBenutzerFeld8;
        [Size(250)]
        public string BenutzerFeld8
        {
            get { return fBenutzerFeld8; }
            set { SetPropertyValue<string>("BenutzerFeld8", ref fBenutzerFeld8, value); }
        }
        string fBenutzerFeld9;
        [Size(250)]
        public string BenutzerFeld9
        {
            get { return fBenutzerFeld9; }
            set { SetPropertyValue<string>("BenutzerFeld9", ref fBenutzerFeld9, value); }
        }
        string fBenutzerFeld10;
        [Size(250)]
        public string BenutzerFeld10
        {
            get { return fBenutzerFeld10; }
            set { SetPropertyValue<string>("BenutzerFeld10", ref fBenutzerFeld10, value); }
        }
        [Association(@"WartTermineReferencesWartAnlagen")]
        public XPCollection<WartTermine> WartTermines { get { return GetCollection<WartTermine>("WartTermines"); } }
    }

}
