//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class WartAuftraegeInfo : XPLiteObject
    {
        string fInfoID;
        [Key]
        [Size(20)]
        public string InfoID
        {
            get { return fInfoID; }
            set { SetPropertyValue<string>("InfoID", ref fInfoID, value); }
        }
        string fAuftragsNr;
        [Indexed(Name = @"AuftragsNr")]
        [Size(15)]
        public string AuftragsNr
        {
            get { return fAuftragsNr; }
            set { SetPropertyValue<string>("AuftragsNr", ref fAuftragsNr, value); }
        }
        string fInfoType;
        [Indexed(Name = @"InfoType")]
        [Size(1)]
        public string InfoType
        {
            get { return fInfoType; }
            set { SetPropertyValue<string>("InfoType", ref fInfoType, value); }
        }
        string fInfo;
        [Size(SizeAttribute.Unlimited)]
        public string Info
        {
            get { return fInfo; }
            set { SetPropertyValue<string>("Info", ref fInfo, value); }
        }
    }

}
