//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class wflowAutoAktivitaetenWorkflow : XPLiteObject
    {
        string fWorkFlowKey;
        [Key]
        [Size(50)]
        public string WorkFlowKey
        {
            get { return fWorkFlowKey; }
            set { SetPropertyValue<string>("WorkFlowKey", ref fWorkFlowKey, value); }
        }
        wflowAutoAktivitaeten fAutoAktivitaetenIdParent;
        [Association(@"wflowAutoAktivitaetenWorkflowReferenceswflowAutoAktivitaeten")]
        public wflowAutoAktivitaeten AutoAktivitaetenIdParent
        {
            get { return fAutoAktivitaetenIdParent; }
            set { SetPropertyValue<wflowAutoAktivitaeten>("AutoAktivitaetenIdParent", ref fAutoAktivitaetenIdParent, value); }
        }
        wflowAutoAktivitaeten fAutoAktivitaetenIdChild;
        [Association(@"wflowAutoAktivitaetenWorkflowReferenceswflowAutoAktivitaeten1")]
        public wflowAutoAktivitaeten AutoAktivitaetenIdChild
        {
            get { return fAutoAktivitaetenIdChild; }
            set { SetPropertyValue<wflowAutoAktivitaeten>("AutoAktivitaetenIdChild", ref fAutoAktivitaetenIdChild, value); }
        }
    }

}
