//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class wflowSelekts : XPLiteObject
    {
        int fSelektID;
        [Key(true)]
        public int SelektID
        {
            get { return fSelektID; }
            set { SetPropertyValue<int>("SelektID", ref fSelektID, value); }
        }
        string fSelekt;
        [Size(20)]
        public string Selekt
        {
            get { return fSelekt; }
            set { SetPropertyValue<string>("Selekt", ref fSelekt, value); }
        }
        [Association(@"wflowAktivitaetenReferenceswflowSelekts")]
        public XPCollection<wflowAktivitaeten> wflowAktivitaetens { get { return GetCollection<wflowAktivitaeten>("wflowAktivitaetens"); } }
        [Association(@"wflowAutoAktivitaetenReferenceswflowSelekts")]
        public XPCollection<wflowAutoAktivitaeten> wflowAutoAktivitaetens { get { return GetCollection<wflowAutoAktivitaeten>("wflowAutoAktivitaetens"); } }
    }

}
