//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class wflowAutoAktivitaetenAdressen : XPLiteObject
    {
        int fAdressId;
        [Key(true)]
        public int AdressId
        {
            get { return fAdressId; }
            set { SetPropertyValue<int>("AdressId", ref fAdressId, value); }
        }
        wflowAutoAktivitaeten fAutoAktivitaetenId;
        [Association(@"wflowAutoAktivitaetenAdressenReferenceswflowAutoAktivitaeten")]
        public wflowAutoAktivitaeten AutoAktivitaetenId
        {
            get { return fAutoAktivitaetenId; }
            set { SetPropertyValue<wflowAutoAktivitaeten>("AutoAktivitaetenId", ref fAutoAktivitaetenId, value); }
        }
        string fAdrNrGes;
        [Indexed(Name = @"IX_wflowAutoAktivitaetenAdressenAdrNrGes")]
        [Size(24)]
        public string AdrNrGes
        {
            get { return fAdrNrGes; }
            set { SetPropertyValue<string>("AdrNrGes", ref fAdrNrGes, value); }
        }
        string fBemerkung;
        [Size(255)]
        public string Bemerkung
        {
            get { return fBemerkung; }
            set { SetPropertyValue<string>("Bemerkung", ref fBemerkung, value); }
        }
    }

}
