//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class wflowInfos : XPLiteObject
    {
        int fInfoId;
        [Key(true)]
        public int InfoId
        {
            get { return fInfoId; }
            set { SetPropertyValue<int>("InfoId", ref fInfoId, value); }
        }
        wflowAktivitaeten fAktivitaetenId;
        [Association(@"wflowInfosReferenceswflowAktivitaeten")]
        public wflowAktivitaeten AktivitaetenId
        {
            get { return fAktivitaetenId; }
            set { SetPropertyValue<wflowAktivitaeten>("AktivitaetenId", ref fAktivitaetenId, value); }
        }
        string fInfo;
        [Size(SizeAttribute.Unlimited)]
        public string Info
        {
            get { return fInfo; }
            set { SetPropertyValue<string>("Info", ref fInfo, value); }
        }
        string fInfoUser;
        [Size(8)]
        public string InfoUser
        {
            get { return fInfoUser; }
            set { SetPropertyValue<string>("InfoUser", ref fInfoUser, value); }
        }
        int fInfoArt;
        public int InfoArt
        {
            get { return fInfoArt; }
            set { SetPropertyValue<int>("InfoArt", ref fInfoArt, value); }
        }
        DateTime fDatumErfasst;
        public DateTime DatumErfasst
        {
            get { return fDatumErfasst; }
            set { SetPropertyValue<DateTime>("DatumErfasst", ref fDatumErfasst, value); }
        }
        string fUserErfasst;
        [Size(8)]
        public string UserErfasst
        {
            get { return fUserErfasst; }
            set { SetPropertyValue<string>("UserErfasst", ref fUserErfasst, value); }
        }
        DateTime fDatumAenderung;
        public DateTime DatumAenderung
        {
            get { return fDatumAenderung; }
            set { SetPropertyValue<DateTime>("DatumAenderung", ref fDatumAenderung, value); }
        }
        string fUserAenderung;
        [Size(8)]
        public string UserAenderung
        {
            get { return fUserAenderung; }
            set { SetPropertyValue<string>("UserAenderung", ref fUserAenderung, value); }
        }
        DateTime fInfoDatum;
        public DateTime InfoDatum
        {
            get { return fInfoDatum; }
            set { SetPropertyValue<DateTime>("InfoDatum", ref fInfoDatum, value); }
        }
    }

}
