//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace GDS.KwpAddOns.KwpData72.KwpDataModel.BNWINS_Demo_new
{

    public partial class wflowUsers : XPLiteObject
    {
        int fUserId;
        [Key(true)]
        public int UserId
        {
            get { return fUserId; }
            set { SetPropertyValue<int>("UserId", ref fUserId, value); }
        }
        string fBenutzerID;
        [Indexed(Name = @"IX_wflowUsersBenutzerID")]
        [Size(8)]
        public string BenutzerID
        {
            get { return fBenutzerID; }
            set { SetPropertyValue<string>("BenutzerID", ref fBenutzerID, value); }
        }
        wflowAktivitaeten fAktivitaetenId;
        [Association(@"wflowUsersReferenceswflowAktivitaeten")]
        public wflowAktivitaeten AktivitaetenId
        {
            get { return fAktivitaetenId; }
            set { SetPropertyValue<wflowAktivitaeten>("AktivitaetenId", ref fAktivitaetenId, value); }
        }
        bool fOK;
        public bool OK
        {
            get { return fOK; }
            set { SetPropertyValue<bool>("OK", ref fOK, value); }
        }
        bool fTerminAnlegen;
        public bool TerminAnlegen
        {
            get { return fTerminAnlegen; }
            set { SetPropertyValue<bool>("TerminAnlegen", ref fTerminAnlegen, value); }
        }
    }

}
